import { test,expect,type Page } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import { readFile,mkdir } from 'node:fs/promises';
async function ready(page:Page){await page.goto('/');await expect(page.getByRole('button',{name:'Start review'})).toBeVisible();}
async function reveal(page:Page){await page.getByRole('button',{name:'Reveal answer',exact:true}).click();await expect(page.getByRole('heading',{level:1})).toBeVisible();}
test('review, deliberate relearning, bookmarks, and refresh persistence',async({page})=>{
 await ready(page);await page.getByRole('button',{name:'Start review'}).click();const question=await page.locator('.question-button>span').innerText();await reveal(page);await page.getByRole('button',{name:'Bookmark card',exact:true}).click();await page.getByRole('button',{name:/^Again/}).click();
 for(let i=0;i<2;i++){await reveal(page);await page.getByRole('button',{name:/^Good/}).click();}
 await expect(page.locator('.question-button>span')).toHaveText(question);await expect(page.getByRole('button',{name:'Remove bookmark'})).toBeVisible();await reveal(page);await page.getByRole('button',{name:/^Easy/}).click();const next=await page.locator('.question-button>span').innerText();await page.reload();await expect(page.locator('.question-button>span')).toHaveText(next);await page.getByRole('link',{name:'Save & exit'}).click();await expect(page.getByRole('button',{name:'Continue review'})).toBeVisible();
});
test('browse filters, bookmark, suspension and issue reporting',async({page})=>{
 await ready(page);await page.getByRole('link',{name:'Browse',exact:true}).click();await page.getByRole('combobox',{name:'Card type',exact:true}).selectOption('calculation');await expect(page.locator('.browse-card').first()).toContainText('calculation');await page.getByRole('combobox',{name:'Section',exact:true}).selectOption('21');await expect(page.locator('.result-count')).toContainText('3 cards found');await page.locator('.browse-card>summary').first().click();await page.getByRole('button',{name:'Bookmark card',exact:true}).first().click();await page.getByLabel('Bookmarked',{exact:true}).check();await expect(page.locator('.result-count')).toContainText('1 cards found');await page.getByRole('button',{name:'Report content issue'}).click();await page.getByLabel('What needs checking?').fill('Please verify the tax assumptions before release.');await page.getByRole('button',{name:'Save issue'}).click();await expect(page.getByRole('status').filter({hasText:'Issue saved'})).toBeVisible();await page.getByRole('button',{name:'Suspend card'}).click();await page.getByRole('combobox',{name:'Due status',exact:true}).selectOption('suspended');await expect(page.locator('.result-count')).toContainText('1 cards found');
});
test('settings, export/import, invalid import rejection and reset',async({page})=>{
 await ready(page);await page.getByRole('button',{name:'Start review'}).click();await reveal(page);await page.getByRole('button',{name:/^Good/}).click();await page.getByRole('link',{name:'Settings',exact:true}).click();await page.getByLabel('New cards per day').fill('8');await page.getByLabel('Appearance').selectOption('dark');await page.getByRole('button',{name:'Save settings'}).click();await expect(page.locator('html')).toHaveAttribute('data-theme','dark');await page.reload();await expect(page.getByLabel('New cards per day')).toHaveValue('8');
 await page.getByLabel('Import progress file').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{"app":"wrong"}')});await expect(page.locator('.inline-error')).toContainText('not a valid');
 const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Export JSON'}).click();const download=await downloadPromise;const saved=await readFile((await download.path())!);const json=JSON.parse(saved.toString());expect(json.data.events).toHaveLength(1);
 await page.getByRole('button',{name:'Reset all progress & settings'}).click();await page.getByRole('button',{name:'Cancel',exact:true}).click();await expect(page.getByLabel('New cards per day')).toHaveValue('8');await page.getByRole('button',{name:'Reset all progress & settings'}).click();await page.getByRole('button',{name:'Confirm reset'}).click();await expect(page.getByLabel('New cards per day')).toHaveValue('20');await page.getByLabel('Import progress file').setInputFiles({name:'backup.json',mimeType:'application/json',buffer:saved});await page.getByRole('button',{name:'Replace progress'}).click();await expect(page.getByLabel('New cards per day')).toHaveValue('8');await page.getByRole('link',{name:'Progress',exact:true}).click();await expect(page.locator('.progress-stats')).toContainText('100%');
});
test('first-load precache permits unvisited routes and saved reviews offline',async({page,context})=>{
 await ready(page);await expect(page.getByText('Available offline on this device')).toBeVisible();await page.evaluate(async()=>{await navigator.serviceWorker.ready;if(!navigator.serviceWorker.controller)await new Promise<void>(resolve=>navigator.serviceWorker.addEventListener('controllerchange',()=>resolve(),{once:true}));});await context.setOffline(true);await page.goto('/browse/');await expect(page.getByRole('heading',{name:'Find the rule you need.'})).toBeVisible();await page.goto('/review/');await page.getByRole('button',{name:'Start review',exact:true}).click();await reveal(page);await page.getByRole('button',{name:/^Good/}).click();const next=await page.locator('.question-button>span').innerText();await page.reload();await expect(page.locator('.question-button>span')).toHaveText(next);await page.getByRole('link',{name:'Progress',exact:true}).click();await expect(page.locator('.progress-stats')).toContainText('100%');
});
test('keyboard review shortcuts work without intercepting form input',async({page})=>{
 await ready(page);await page.getByRole('button',{name:'Start review'}).click();await page.locator('body').click({position:{x:2,y:150}});await page.keyboard.press('Space');await expect(page.locator('.answer-text')).toBeVisible();await page.keyboard.press('3');await expect(page.locator('.question-button')).toBeVisible();
});
test('phone and desktop layouts, dark theme, reduced motion, and accessibility',async({page})=>{
 await mkdir('test-results/visual',{recursive:true});
 for(const width of [390,1440]){
  await page.setViewportSize({width,height:width===390?844:1000});await ready(page);
  await page.screenshot({path:`test-results/visual/dashboard-${width}.png`,fullPage:true});
  const report=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();expect(report.violations).toEqual([]);
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 }
 await page.getByRole('button',{name:'Start review'}).click();await page.setViewportSize({width:390,height:844});await page.screenshot({path:'test-results/visual/review-phone.png',fullPage:true});await reveal(page);await page.screenshot({path:'test-results/visual/answer-phone.png',fullPage:true});expect((await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations).toEqual([]);
 for(const route of ['/browse/','/settings/','/progress/','/about/','/faq/']){await page.goto(route);await expect(page.locator('h1')).toBeVisible();expect((await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}
 await page.goto('/settings/');await page.getByLabel('Appearance').selectOption('dark');await page.getByRole('button',{name:'Save settings'}).click();await page.emulateMedia({reducedMotion:'reduce'});await page.goto('/');await expect(page.locator('html')).toHaveAttribute('data-theme','dark');await page.screenshot({path:'test-results/visual/dark-phone.png',fullPage:true});expect((await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations).toEqual([]);
});
test('AEO content is server-rendered, schema matches visible FAQ, and draft indexing stays blocked',async({page,request})=>{
 const response=await request.get('/faq/');const html=await response.text();expect(html).toContain('What is Series 65 Review?');expect(html).toContain('application/ld+json');expect(html).toContain('noindex');await page.goto('/faq/');const data=JSON.parse(await page.locator('script[type="application/ld+json"]').innerText());expect(data['@type']).toBe('FAQPage');expect(data.mainEntity).toHaveLength(8);for(const item of data.mainEntity){await expect(page.getByRole('heading',{name:item.name})).toBeVisible();await expect(page.getByText(item.acceptedAnswer.text,{exact:true})).toBeVisible();}expect(await (await request.get('/robots.txt')).text()).toContain('Disallow: /');const manifest=await (await request.get('/manifest.webmanifest')).json();expect(manifest.icons).toHaveLength(3);for(const icon of manifest.icons)expect((await request.get(icon.src)).ok()).toBe(true);expect((await request.get('/favicon.ico')).ok()).toBe(true);
});
