import type { ApplicationSeed } from './applications';
import type { officialSources } from './official-sources';

/** Independently authored exam-outline coverage added September 13, 2026.
 * Fills NASAA Series 65 outline topics that had no cards: economics, fixed income,
 * fund share classes, trading and portfolio strategy, estate transfer, and conduct rules.
 * Every rule has a recall and a complete contrast pair. All cards remain draft.
 */
export interface CoverageRule {
 section:number; key:string; topic:string; sources:(keyof typeof officialSources)[];
 front:string; answer:string; trap:string; explanation:string;
 contrast:{front:string;answer:string};
 application?:Omit<ApplicationSeed,'section'|'key'>;
}
export const coverageRules:CoverageRule[] = [
 // Economic factors and business information
 {section:23,key:'business-cycle',topic:'Business cycle',sources:['nber'],
  front:'What are the four phases of the business cycle, in order?',
  answer:'Expansion, peak, contraction, and trough.',
  trap:'A recession is officially defined as two consecutive quarters of falling GDP.',
  explanation:'The cycle repeats: growth rises to a peak, activity contracts, bottoms at a trough, and expansion resumes. In the United States, the NBER dates recessions using a broad set of indicators.',
  contrast:{front:'Is a U.S. recession officially defined as two consecutive quarters of falling GDP?',answer:'No. The NBER dates recessions from broad measures of activity; two negative quarters is only a rule of thumb.'}},
 {section:23,key:'gdp',topic:'Gross domestic product',sources:['gdp'],
  front:'What does gross domestic product (GDP) measure?',
  answer:'The market value of final goods and services produced within a country during a period.',
  trap:'GDP adds intermediate goods separately to final goods.',
  explanation:'Counting intermediate goods separately would double count the same production. GDP is the broadest single measure of economic output.',
  contrast:{front:'Does GDP add the value of intermediate goods on top of the final goods they become?',answer:'No. That would double count; GDP measures final goods and services only.'}},
 {section:23,key:'real-gdp',topic:'Real versus nominal',sources:['gdp'],
  front:'How does real GDP differ from nominal GDP?',
  answer:'Real GDP removes the effect of price changes; nominal GDP uses current prices.',
  trap:'Nominal growth equals real growth even when prices are rising.',
  explanation:'Real figures show changes in the quantity of output. Approximate real growth as nominal growth minus inflation.',
  contrast:{front:'Nominal GDP rises 6% while prices rise 2.5%. Did real output grow 6%?',answer:'No. Real growth is roughly 3.5% after removing the price increase.'},
  application:{type:'calculation',front:'Nominal GDP grows 5% and the price level rises 3%. What is the approximate real growth rate?',answer:'About 2%.',explanation:'Approximate real growth = nominal growth − inflation = 5% − 3% = 2%.'}},
 {section:23,key:'cpi',topic:'Consumer Price Index',sources:['cpi'],
  front:'What does the Consumer Price Index (CPI) measure?',
  answer:'The average change over time in prices paid by urban consumers for a market basket of goods and services.',
  trap:'CPI measures prices received by domestic producers.',
  explanation:'CPI is the most widely cited U.S. inflation measure. The Producer Price Index tracks prices received by producers.',
  contrast:{front:'Does the Consumer Price Index measure selling prices received by domestic producers?',answer:'No. That is the Producer Price Index; CPI tracks prices paid by urban consumers.'}},
 {section:23,key:'deflation',topic:'Deflation',sources:['cpi'],
  front:'During deflation, who gains purchasing power: fixed-rate lenders or fixed-rate borrowers?',
  answer:'Fixed-rate lenders and bondholders. Borrowers repay debt with dollars that buy more.',
  trap:'Deflation makes fixed-rate debt easier to repay in real terms.',
  explanation:'Deflation is a sustained fall in the general price level. Fixed payments become worth more in real terms, raising the real burden on borrowers.',
  contrast:{front:'Does deflation make a fixed-rate borrower’s debt easier to repay in real terms?',answer:'No. The real burden of fixed debt rises when prices fall.'}},
 {section:23,key:'fed-tools',topic:'Monetary policy',sources:['fed'],
  front:'Which main tools does the Federal Reserve use to carry out monetary policy?',
  answer:'Its federal funds target range, interest on reserve balances, open market operations, and the discount rate.',
  trap:'Changing federal tax rates is a Federal Reserve tool.',
  explanation:'Monetary policy influences money and credit conditions. Taxes and government spending are fiscal policy.',
  contrast:{front:'Is changing federal tax rates a Federal Reserve monetary-policy tool?',answer:'No. Taxes and spending are fiscal policy, set by Congress and the President.'}},
 {section:23,key:'open-market',topic:'Open market operations',sources:['fed'],
  front:'To ease monetary policy through open market operations, does the Federal Reserve buy or sell securities?',
  answer:'It buys securities, adding reserves and putting downward pressure on interest rates.',
  trap:'Selling Treasury securities eases monetary policy.',
  explanation:'Purchases add bank reserves; sales drain reserves and tend to tighten credit conditions.',
  contrast:{front:'Does the Federal Reserve sell Treasury securities to ease monetary policy?',answer:'No. Selling drains reserves and tightens; buying eases.'}},
 {section:23,key:'fiscal-policy',topic:'Fiscal policy',sources:['fed'],
  front:'What is fiscal policy, and who sets it?',
  answer:'Government spending and taxation decisions, set by Congress and the President.',
  trap:'The Federal Reserve sets fiscal policy.',
  explanation:'Expansionary fiscal policy raises spending or cuts taxes; contractionary policy does the reverse. The Federal Reserve conducts monetary policy.',
  contrast:{front:'Is the Federal Reserve responsible for setting federal spending and tax policy?',answer:'No. Congress and the President set fiscal policy; the Federal Reserve sets monetary policy.'}},
 {section:23,key:'fed-funds-rate',topic:'Federal funds rate',sources:['fed'],
  front:'What is the federal funds rate?',
  answer:'The interest rate banks charge each other for overnight loans of reserves; the Federal Reserve sets a target range for it.',
  trap:'The federal funds rate is what the Federal Reserve charges banks at the discount window.',
  explanation:'The discount rate is the rate on Federal Reserve discount-window loans to eligible banks. The federal funds rate is set in the market between banks, guided by the target range.',
  contrast:{front:'Is the federal funds rate the rate the Federal Reserve charges banks that borrow at its discount window?',answer:'No. That is the discount rate; the federal funds rate is the overnight rate between banks.'}},
 {section:23,key:'yield-curve-normal',topic:'Yield curve',sources:['yieldCurve'],
  front:'What does a normal yield curve look like?',
  answer:'Upward sloping: longer maturities yield more than shorter maturities of similar credit quality.',
  trap:'A normal curve shows short-term yields above long-term yields.',
  explanation:'Investors usually demand more yield for tying up money longer. A curve with short yields above long yields is inverted.',
  contrast:{front:'Does a normal yield curve show short-term Treasury yields above long-term yields?',answer:'No. That is an inverted curve; a normal curve slopes upward.'}},
 {section:23,key:'yield-curve-inverted',topic:'Inverted yield curve',sources:['yieldCurve'],
  front:'What does an inverted yield curve show, and what is it often associated with?',
  answer:'Short-term yields above long-term yields; it is often viewed as a possible recession signal.',
  trap:'An inverted yield curve guarantees a recession will follow.',
  explanation:'Inversions have preceded many U.S. recessions, but the signal is not certain and timing varies.',
  contrast:{front:'Does an inverted yield curve guarantee that a recession will follow?',answer:'No. It has often preceded recessions but is not a certain predictor.'}},
 {section:23,key:'strong-dollar',topic:'Exchange rates',sources:['exchangeRates'],
  front:'How does a stronger U.S. dollar generally affect U.S. exports and imports?',
  answer:'Exports become more expensive for foreign buyers, and imports become cheaper for U.S. buyers.',
  trap:'A weaker dollar makes U.S. exports more expensive abroad.',
  explanation:'Exchange rates change what foreign buyers pay in their own currency. A weaker dollar generally helps exporters and makes imports costlier.',
  contrast:{front:'Does a weaker dollar make U.S. exports more expensive for foreign buyers?',answer:'No. A weaker dollar generally makes U.S. exports cheaper abroad.'}},
 {section:23,key:'currency-return',topic:'Currency risk',sources:['exchangeRates'],
  front:'A U.S. investor owns a foreign stock. If the foreign currency weakens against the dollar, what happens to the dollar return?',
  answer:'It falls, because each unit of foreign currency converts into fewer dollars.',
  trap:'Currency moves do not affect a U.S. investor’s return on foreign shares.',
  explanation:'Dollar return combines the local-market return and the currency change: (1 + local return) × (1 + currency change) − 1.',
  contrast:{front:'Does a rising foreign stock guarantee a positive dollar return for a U.S. investor?',answer:'No. A large enough decline in that currency can turn a local gain into a dollar loss.'},
  application:{type:'calculation',front:'A foreign stock gains 10% in its local currency while that currency falls 5% against the dollar. What is the approximate dollar return?',answer:'4.5%.',explanation:'1.10 × 0.95 − 1 = 0.045, or 4.5%.'}},
 {section:23,key:'future-value',topic:'Time value of money',sources:['cashflows'],
  front:'How is the future value of a lump sum with annual compounding calculated?',
  answer:'Present value × (1 + rate) raised to the number of years.',
  trap:'Compound growth equals the rate times the number of years, with no interest on interest.',
  explanation:'Compounding earns interest on prior interest, so growth exceeds simple interest over multiple periods.',
  contrast:{front:'Does $10,000 at 6% compounded annually for two years grow to exactly $11,200?',answer:'No. It grows to $11,236 because the second year earns interest on the first year’s interest.'},
  application:{type:'calculation',front:'An investor deposits $10,000 at 6% compounded annually. What is the value after two years?',answer:'$11,236.',explanation:'$10,000 × 1.06² = $10,000 × 1.1236 = $11,236.'}},
 {section:23,key:'present-value',topic:'Present value',sources:['cashflows'],
  front:'How does a higher discount rate or a longer wait affect the present value of a future payment?',
  answer:'Both lower the present value.',
  trap:'A higher discount rate raises the present value of a future payment.',
  explanation:'Present value = future value ÷ (1 + rate) raised to the number of periods. A larger denominator means a smaller present value.',
  contrast:{front:'Does raising the discount rate increase the present value of a fixed future payment?',answer:'No. A higher discount rate reduces present value.'},
  application:{type:'calculation',front:'What is the present value of $1,100 received in one year at a 10% discount rate?',answer:'$1,000.',explanation:'$1,100 ÷ 1.10 = $1,000.'}},
 {section:23,key:'rule-of-72',topic:'Rule of 72',sources:['cashflows'],
  front:'How does the Rule of 72 estimate how long an investment takes to double?',
  answer:'Divide 72 by the annual percentage return.',
  trap:'Multiply 72 by the annual return.',
  explanation:'It is a quick approximation for compound growth; it works best for moderate rates.',
  contrast:{front:'At an 8% annual return, does the Rule of 72 estimate doubling in 576 years?',answer:'No. Divide, don’t multiply: 72 ÷ 8 = about 9 years.'},
  application:{type:'calculation',front:'Using the Rule of 72, about how long does money take to double at a 6% annual return?',answer:'About 12 years.',explanation:'72 ÷ 6 = 12.'}},
 {section:23,key:'beta',topic:'Beta',sources:['beta'],
  front:'What does beta measure?',
  answer:'A security’s sensitivity to overall market movements, which is systematic risk. A beta of 1 moves with the market.',
  trap:'Beta measures a stock’s total risk, including company-specific risk.',
  explanation:'A beta above 1 suggests larger swings than the market; below 1, smaller swings. Standard deviation measures total volatility.',
  contrast:{front:'Does beta measure total volatility, including company-specific risk?',answer:'No. Beta measures market-related (systematic) risk; standard deviation measures total volatility.'}},
 {section:23,key:'capm-formula',topic:'CAPM expected return',sources:['capm'],
  front:'What is the CAPM formula for a security’s expected return?',
  answer:'Risk-free rate + beta × (expected market return − risk-free rate).',
  trap:'Expected return equals beta × the market return, with no risk-free rate.',
  explanation:'The term in parentheses is the market risk premium. Beta scales that premium for the security’s systematic risk.',
  contrast:{front:'Under the CAPM, is expected return simply beta multiplied by the market return?',answer:'No. Add the risk-free rate to beta times the market risk premium.'},
  application:{type:'calculation',front:'The risk-free rate is 4%, the expected market return is 9%, and a stock’s beta is 0.8. What is its CAPM expected return?',answer:'8%.',explanation:'4% + 0.8 × (9% − 4%) = 4% + 4% = 8%.'}},
 {section:23,key:'alpha',topic:'Alpha',sources:['capm'],
  front:'What does a portfolio’s alpha measure?',
  answer:'The return above or below what was expected for the risk taken, often using CAPM expected return.',
  trap:'Alpha is the portfolio’s total return.',
  explanation:'Positive alpha means outperformance on a risk-adjusted basis; negative alpha means underperformance.',
  contrast:{front:'Is a portfolio with an 11% return automatically showing 11% alpha?',answer:'No. Alpha is the return beyond the risk-based expected return, not the total return.'},
  application:{type:'calculation',front:'A portfolio earned 11%. The risk-free rate is 3%, the market returned 8%, and the portfolio beta is 1.2. What is its alpha?',answer:'2%.',explanation:'Expected = 3% + 1.2 × (8% − 3%) = 9%. Alpha = 11% − 9% = 2%.'}},
 {section:23,key:'sharpe-ratio',topic:'Sharpe ratio',sources:['sharpe'],
  front:'How is the Sharpe ratio calculated, and what does a higher value mean?',
  answer:'(Portfolio return − risk-free rate) ÷ standard deviation. Higher means more excess return per unit of total risk.',
  trap:'The Sharpe ratio divides excess return by beta.',
  explanation:'Sharpe uses total risk (standard deviation). A ratio that divides by beta is the Treynor ratio.',
  contrast:{front:'Does the Sharpe ratio divide excess return by beta?',answer:'No. It divides by standard deviation; dividing by beta gives the Treynor ratio.'},
  application:{type:'calculation',front:'A portfolio returned 10% with a 16% standard deviation. The risk-free rate is 2%. What is the Sharpe ratio?',answer:'0.5.',explanation:'(10% − 2%) ÷ 16% = 0.5.'}},
 {section:23,key:'correlation-range',topic:'Correlation coefficient',sources:['diversification'],
  front:'What is the range of the correlation coefficient, and what do its ends mean?',
  answer:'From −1 to +1. +1 means returns move perfectly together; −1 means they move perfectly opposite.',
  trap:'Correlation can range from 0 to 100.',
  explanation:'A correlation of 0 means no linear relationship. Lower correlations provide more diversification benefit.',
  contrast:{front:'Can a correlation coefficient be greater than +1?',answer:'No. Correlation always falls between −1 and +1.'}},
 {section:23,key:'time-weighted',topic:'Time-weighted return',sources:['performance'],
  front:'Which return measure removes the effect of client deposits and withdrawals, making it best for judging a manager?',
  answer:'Time-weighted return.',
  trap:'Dollar-weighted return best isolates the manager’s skill.',
  explanation:'The manager does not control when the client adds or removes money. Time-weighted return links sub-period returns so cash-flow timing does not distort the result.',
  contrast:{front:'When the client controls deposits and withdrawals, is dollar-weighted return the better measure of manager skill?',answer:'No. Time-weighted return removes cash-flow timing; dollar-weighted return reflects the investor’s own timing.'}},
 {section:23,key:'dollar-weighted',topic:'Dollar-weighted return',sources:['performance'],
  front:'What is dollar-weighted return, and what does it reflect?',
  answer:'The internal rate of return on the investor’s cash flows; it reflects the timing and size of deposits and withdrawals.',
  trap:'Dollar-weighted return ignores when money was added.',
  explanation:'Large deposits made just before strong performance raise dollar-weighted return; deposits before weak performance lower it.',
  contrast:{front:'Does dollar-weighted return ignore the timing of an investor’s deposits?',answer:'No. It is sensitive to the timing and size of cash flows.'}},
 {section:23,key:'real-return',topic:'Real return',sources:['cpi'],
  front:'How is an approximate real (inflation-adjusted) return calculated?',
  answer:'Nominal return minus the inflation rate.',
  trap:'Add inflation to the nominal return.',
  explanation:'Real return shows the change in purchasing power. The exact formula is (1 + nominal) ÷ (1 + inflation) − 1.',
  contrast:{front:'With a 7% nominal return and 3% inflation, is the real return about 10%?',answer:'No. It is about 4%: subtract inflation from the nominal return.'}},
 {section:23,key:'median-mean',topic:'Mean and median',sources:['statistics'],
  front:'How does the median differ from the mean, and which is less affected by extreme values?',
  answer:'The median is the middle value after sorting; the mean is the arithmetic average. The median is less affected by outliers.',
  trap:'The mean is less sensitive to extreme values than the median.',
  explanation:'One very large observation pulls the mean toward it but may not move the median.',
  contrast:{front:'Is the arithmetic mean less sensitive to an extreme outlier than the median?',answer:'No. The median resists outliers; the mean is pulled toward them.'},
  application:{type:'calculation',front:'Returns are 2%, 4%, 4%, 9%, and 31%. What are the median and the mean?',answer:'Median 4%; mean 10%.',explanation:'Sorted middle value = 4%. Mean = (2 + 4 + 4 + 9 + 31) ÷ 5 = 50 ÷ 5 = 10%.'}},
 {section:23,key:'fundamental-technical',topic:'Fundamental and technical analysis',sources:['statements'],
  front:'How does fundamental analysis differ from technical analysis?',
  answer:'Fundamental analysis studies financial statements, industry, and the economy to estimate value; technical analysis studies price and volume patterns.',
  trap:'Technical analysis relies mainly on earnings and balance sheets.',
  explanation:'A fundamental analyst asks what a company is worth. A technical analyst looks at charts, trends, support, and resistance.',
  contrast:{front:'Does a technical analyst rely mainly on a company’s balance sheet and earnings reports?',answer:'No. That is fundamental analysis; technical analysis focuses on price and volume data.'}},
 {section:22,key:'pe-ratio',topic:'Price-to-earnings ratio',sources:['statements'],
  front:'How is the price-to-earnings (P/E) ratio calculated?',
  answer:'Market price per share ÷ earnings per share.',
  trap:'Divide earnings per share by the share price.',
  explanation:'A high P/E often signals expected growth (growth stock); a low P/E can signal a value stock.',
  contrast:{front:'Is the P/E ratio earnings per share divided by the stock price?',answer:'No. That is the earnings yield; P/E is price divided by earnings per share.'},
  application:{type:'calculation',front:'A stock trades at $60 and has earnings per share of $4. What is its P/E ratio?',answer:'15.',explanation:'$60 ÷ $4 = 15.'}},
 {section:22,key:'dividend-yield',topic:'Dividend yield',sources:['statements'],
  front:'How is a stock’s dividend yield calculated?',
  answer:'Annual dividends per share ÷ current market price per share.',
  trap:'Dividend yield uses earnings per share in the numerator.',
  explanation:'Dividend yield is a current-income measure. The payout ratio compares dividends with earnings.',
  contrast:{front:'If a stock’s price falls and its dividend is unchanged, does its dividend yield fall?',answer:'No. A lower price with the same dividend raises the dividend yield.'},
  application:{type:'calculation',front:'A stock pays $2 in annual dividends and trades at $50. What is its dividend yield?',answer:'4%.',explanation:'$2 ÷ $50 = 0.04 = 4%.'}},
 {section:22,key:'eps',topic:'Earnings per share',sources:['statements'],
  front:'How is basic earnings per share (EPS) calculated?',
  answer:'(Net income − preferred dividends) ÷ weighted average common shares outstanding.',
  trap:'Preferred dividends stay in the numerator for common EPS.',
  explanation:'EPS measures earnings available to common shareholders, so preferred dividends are subtracted first.',
  contrast:{front:'Should preferred dividends be included in the earnings used for common EPS?',answer:'No. Subtract preferred dividends from net income first.'},
  application:{type:'calculation',front:'Net income is $10 million, preferred dividends are $1 million, and 3 million common shares are outstanding. What is EPS?',answer:'$3.00.',explanation:'($10 million − $1 million) ÷ 3 million = $3.00.'}},
 {section:22,key:'payout-ratio',topic:'Dividend payout ratio',sources:['statements'],
  front:'What does the dividend payout ratio measure?',
  answer:'The share of earnings paid as dividends: dividends per share ÷ earnings per share.',
  trap:'The payout ratio divides dividends by the share price.',
  explanation:'Dividends ÷ price is dividend yield. Mature companies often have higher payout ratios; growth companies retain more earnings.',
  contrast:{front:'Is the dividend payout ratio dividends divided by the stock price?',answer:'No. That is dividend yield; the payout ratio divides dividends by earnings.'}},
 {section:22,key:'current-ratio',topic:'Current ratio and working capital',sources:['statements'],
  front:'How are the current ratio and working capital calculated?',
  answer:'Current ratio = current assets ÷ current liabilities. Working capital = current assets − current liabilities.',
  trap:'Working capital is current assets divided by current liabilities.',
  explanation:'Both measure short-term liquidity. The quick ratio is stricter because it excludes inventory and prepaid expenses.',
  contrast:{front:'Is working capital a ratio of current assets to current liabilities?',answer:'No. Working capital is the dollar difference; the current ratio is the ratio.'},
  application:{type:'calculation',front:'Current assets are $600,000 and current liabilities are $250,000. What are the current ratio and working capital?',answer:'Current ratio 2.4; working capital $350,000.',explanation:'$600,000 ÷ $250,000 = 2.4. $600,000 − $250,000 = $350,000.'}},
 {section:22,key:'book-value',topic:'Book value per share',sources:['statements'],
  front:'How is book value per common share calculated?',
  answer:'Common shareholders’ equity ÷ common shares outstanding.',
  trap:'Book value per share is the current market price per share.',
  explanation:'Book value comes from the balance sheet. Comparing price with book value gives the price-to-book ratio, a common value measure.',
  contrast:{front:'Is book value per share the same as the stock’s market price?',answer:'No. Book value is an accounting figure from equity; market price is set by trading.'}},

 // Investment vehicle characteristics
 {section:21,key:'treasury-bills',topic:'Treasury bills',sources:['tbills'],
  front:'How are Treasury bills issued and how does the investor earn interest?',
  answer:'They are sold at a discount and pay full face value at maturity of one year or less; the difference is the interest.',
  trap:'Treasury bills pay semiannual coupons.',
  explanation:'T-bills are short-term, backed by the U.S. government, and highly liquid, which makes them a money-market staple.',
  contrast:{front:'Do Treasury bills pay semiannual coupon interest?',answer:'No. They are sold at a discount and pay face value at maturity.'}},
 {section:21,key:'notes-bonds',topic:'Treasury notes and bonds',sources:['treasuries'],
  front:'How do Treasury notes and Treasury bonds differ in maturity, and how do they pay interest?',
  answer:'Notes mature in 2 to 10 years; bonds in 20 or 30 years. Both pay interest every six months.',
  trap:'Treasury notes are the 30-year securities.',
  explanation:'Bills are one year or less. Longer maturities carry more interest-rate risk.',
  contrast:{front:'Is a 30-year Treasury security called a Treasury note?',answer:'No. The 20- and 30-year securities are Treasury bonds; notes run 2 to 10 years.'}},
 {section:21,key:'treasury-tax',topic:'Treasury interest taxation',sources:['treasuries'],
  front:'How is interest on U.S. Treasury securities taxed?',
  answer:'Subject to federal income tax but exempt from state and local income tax.',
  trap:'Treasury interest is exempt from federal income tax.',
  explanation:'This is the reverse of most municipal bonds, whose interest is generally federally tax-exempt.',
  contrast:{front:'Is Treasury bond interest exempt from federal income tax?',answer:'No. It is federally taxable but exempt from state and local income tax.'}},
 {section:21,key:'muni-tax',topic:'Municipal bond taxation',sources:['munis'],
  front:'How are interest and capital gains on a typical municipal bond taxed federally?',
  answer:'Interest is generally exempt from federal income tax; capital gains from selling the bond are taxable.',
  trap:'All gains on a municipal bond are tax-exempt.',
  explanation:'In-state residents may also avoid state tax on the interest. Tax-exempt yields are most valuable to investors in high brackets.',
  contrast:{front:'Is a capital gain from selling a municipal bond federally tax-exempt like its interest?',answer:'No. Only the interest is generally exempt; capital gains are taxable.'}},
 {section:21,key:'go-bond',topic:'General obligation bonds',sources:['munis'],
  front:'What backs a general obligation (GO) municipal bond?',
  answer:'The full faith, credit, and taxing power of the issuing government.',
  trap:'A GO bond is repaid only from revenue of the project it finances.',
  explanation:'GO bonds often require voter approval. Analysts review the tax base, debt burden, and economy.',
  contrast:{front:'Is a general obligation bond repaid only from a specific project’s user fees?',answer:'No. That describes a revenue bond; a GO bond is backed by taxing power.'}},
 {section:21,key:'revenue-bond',topic:'Revenue bonds',sources:['munis'],
  front:'What repays a municipal revenue bond?',
  answer:'Revenue from the specific project or source it finances, such as tolls, water fees, or airport charges.',
  trap:'A revenue bond is backed by the issuer’s general taxing power.',
  explanation:'Analysts review the project’s ability to generate revenue, such as coverage ratios and usage.',
  contrast:{front:'Is a toll-road revenue bond backed by the state’s general taxing power?',answer:'No. It is repaid from the project’s revenues, not general taxes.'}},
 {section:21,key:'zero-coupon',topic:'Zero-coupon bonds',sources:['zeroCoupon'],
  front:'How does a zero-coupon bond pay the investor, and how is a taxable zero taxed?',
  answer:'It is bought at a deep discount and pays face value at maturity. Taxable zeros create annual taxable income as the discount accretes.',
  trap:'A taxable zero-coupon bond owes no tax until maturity.',
  explanation:'The annual tax on income not yet received is often called phantom income. Zeros have no reinvestment risk if held to maturity but high price sensitivity.',
  contrast:{front:'Does a taxable zero-coupon bond defer all federal tax until it matures?',answer:'No. The accreting discount is generally taxable each year even though no cash is paid.'}},
 {section:21,key:'zero-duration',topic:'Zero-coupon duration',sources:['duration'],
  front:'What is the duration of a zero-coupon bond?',
  answer:'Equal to its time to maturity, the highest duration for that maturity.',
  trap:'A zero-coupon bond has less interest-rate sensitivity than a coupon bond of the same maturity.',
  explanation:'All of a zero’s cash flow arrives at maturity. Coupon bonds return some cash earlier, lowering duration.',
  contrast:{front:'Is a 10-year zero-coupon bond less sensitive to rate changes than a 10-year coupon bond?',answer:'No. The zero is more sensitive; its duration equals its 10-year maturity.'}},
 {section:21,key:'call-risk',topic:'Callable bonds',sources:['callable'],
  front:'When interest rates fall, what risk does a callable bond’s investor face?',
  answer:'The issuer may call the bond, forcing the investor to reinvest at lower rates; price gains are also limited.',
  trap:'Falling rates always give callable bondholders unlimited price gains.',
  explanation:'Issuers call bonds to refinance at lower rates. Callable bonds usually offer higher yields to compensate for call risk.',
  contrast:{front:'Do falling interest rates help a callable bond’s investor as much as a noncallable bond’s investor?',answer:'No. The call feature limits price gains and creates reinvestment risk.'}},
 {section:21,key:'convertible',topic:'Convertible bonds',sources:['convertibles'],
  front:'What does a convertible bond allow, and how does its coupon usually compare?',
  answer:'It can be exchanged for a set number of the issuer’s common shares; its coupon is usually lower than a comparable nonconvertible bond.',
  trap:'The conversion feature makes the coupon higher than similar straight bonds.',
  explanation:'Investors accept a lower coupon in exchange for equity upside. Conversion ratio = par value ÷ conversion price.',
  contrast:{front:'Does a convertible bond usually pay a higher coupon than a comparable nonconvertible bond?',answer:'No. The conversion option usually means a lower coupon.'},
  application:{type:'calculation',front:'A $1,000 convertible bond has a $40 conversion price. The stock trades at $44. What are the conversion ratio and the bond’s parity value?',answer:'25 shares; $1,100.',explanation:'$1,000 ÷ $40 = 25 shares. 25 × $44 = $1,100.'}},
 {section:21,key:'prepayment-risk',topic:'Mortgage-backed securities',sources:['mbs'],
  front:'What risk do mortgage-backed pass-through investors face when interest rates fall?',
  answer:'Prepayment risk: homeowners refinance, returning principal early to be reinvested at lower rates.',
  trap:'Falling rates lengthen the expected life of a mortgage pass-through.',
  explanation:'When rates rise, prepayments slow and the security’s life extends, called extension risk.',
  contrast:{front:'Do falling mortgage rates usually slow prepayments on mortgage-backed securities?',answer:'No. Falling rates speed prepayments; rising rates slow them.'}},
 {section:21,key:'ginnie-mae',topic:'Agency securities',sources:['mbs'],
  front:'Which mortgage-backed securities carry the full faith and credit guarantee of the U.S. government?',
  answer:'Ginnie Mae (GNMA) securities. Fannie Mae and Freddie Mac securities do not carry that explicit guarantee.',
  trap:'Fannie Mae and Freddie Mac securities have the same explicit full-faith-and-credit backing as Ginnie Mae.',
  explanation:'Ginnie Mae is a government agency. Fannie Mae and Freddie Mac are government-sponsored enterprises.',
  contrast:{front:'Do Fannie Mae mortgage-backed securities carry the explicit full faith and credit of the U.S. government?',answer:'No. That explicit guarantee applies to Ginnie Mae securities.'}},
 {section:21,key:'adr',topic:'American depositary receipts',sources:['adr'],
  front:'What is an American depositary receipt (ADR), and does it remove currency risk?',
  answer:'A U.S.-traded certificate issued by a depositary bank representing shares of a foreign company. It does not remove currency risk.',
  trap:'Trading in dollars eliminates an ADR holder’s currency risk.',
  explanation:'ADR prices and dividends reflect the foreign share value converted into dollars, so exchange-rate moves still matter.',
  contrast:{front:'Because an ADR trades in dollars on a U.S. market, is the investor free of currency risk?',answer:'No. The underlying shares are priced in foreign currency, so exchange rates still affect value.'}},
 {section:21,key:'reit',topic:'Real estate investment trusts',sources:['reits'],
  front:'What is a real estate investment trust (REIT), and what distribution requirement applies?',
  answer:'A company that owns or finances income-producing real estate. It must distribute at least 90% of taxable income as dividends.',
  trap:'REIT dividends are generally qualified dividends taxed at long-term capital-gain rates.',
  explanation:'Most REIT dividends are taxed as ordinary income. Publicly traded REITs offer liquidity; nontraded REITs can be hard to sell.',
  contrast:{front:'Are most REIT dividends qualified dividends taxed at long-term capital-gain rates?',answer:'No. Most REIT dividends are taxed as ordinary income.'}},
 {section:21,key:'reit-losses',topic:'REITs versus DPPs',sources:['reits'],
  front:'Can a REIT pass its losses through to shareholders like a direct participation program?',
  answer:'No. A REIT passes through income, not losses.',
  trap:'REIT shareholders can deduct the trust’s operating losses on their own returns.',
  explanation:'Limited partnerships and other DPPs can pass through losses. A REIT is a corporation or trust that distributes income.',
  contrast:{front:'Does owning REIT shares let an investor deduct the REIT’s losses like a limited partner?',answer:'No. REITs do not pass through losses; DPPs can.'}},
 {section:21,key:'hedge-funds',topic:'Hedge funds',sources:['hedgeFunds'],
  front:'What features typically distinguish hedge funds from mutual funds?',
  answer:'Private offerings to accredited investors, flexible strategies with leverage and short selling, limited liquidity, and often performance fees.',
  trap:'Hedge funds are registered investment companies offering daily redemptions to retail investors.',
  explanation:'Hedge funds rely on private-offering and investment-company exclusions, so they face less regulation and disclosure than mutual funds.',
  contrast:{front:'Is a typical hedge fund a registered investment company offering daily redemption to any retail investor?',answer:'No. It is usually a private fund for accredited investors with limited redemption rights.'}},
 {section:21,key:'cumulative-preferred',topic:'Cumulative preferred stock',sources:['stocks'],
  front:'What happens to missed dividends on cumulative preferred stock?',
  answer:'They accumulate as arrears and must be paid before any common dividend.',
  trap:'Skipped cumulative preferred dividends are permanently lost.',
  explanation:'Noncumulative preferred does not accumulate missed dividends.',
  contrast:{front:'Can a company pay a common dividend while cumulative preferred dividends are in arrears?',answer:'No. The arrears and the current preferred dividend come first.'},
  application:{type:'calculation',front:'A cumulative preferred stock pays $5 a year. The company skipped two years and now wants to pay common dividends. How much per preferred share must it pay first?',answer:'$15.',explanation:'$10 in arrears (2 × $5) plus the current $5 = $15.'}},
 {section:21,key:'money-market',topic:'Money market instruments',sources:['moneyMarket'],
  front:'What instruments are in the money market, and what is their main long-term risk?',
  answer:'Short-term debt such as T-bills, commercial paper, and certificates of deposit. The main long-term risk is inflation (purchasing-power) risk.',
  trap:'A money market mutual fund is FDIC-insured.',
  explanation:'Money market investments offer liquidity and low credit risk, but returns may trail inflation. Money market funds are not bank deposits.',
  contrast:{front:'Is a money market mutual fund insured by the FDIC?',answer:'No. It is an investment, not a bank deposit, and can lose value.'}},
 {section:21,key:'current-yield',topic:'Current yield',sources:['bonds'],
  front:'How is a bond’s current yield calculated?',
  answer:'Annual interest ÷ current market price.',
  trap:'Current yield divides annual interest by par value.',
  explanation:'Annual interest ÷ par value is the coupon (nominal) rate. Current yield changes as the price changes.',
  contrast:{front:'Is a bond’s current yield annual interest divided by par value?',answer:'No. That is the coupon rate; current yield uses the market price.'},
  application:{type:'calculation',front:'A $1,000 par bond with a 5% coupon trades at $950. What is its current yield?',answer:'About 5.26%.',explanation:'$50 ÷ $950 = 0.0526, or about 5.26%.'}},
 {section:21,key:'premium-yields',topic:'Premium bond yields',sources:['bonds'],
  front:'For a bond trading at a premium, how do coupon rate, current yield, and yield to maturity rank?',
  answer:'Coupon rate is highest, then current yield, then yield to maturity.',
  trap:'Yield to maturity is highest on a premium bond.',
  explanation:'The investor pays more than par and gets back only par at maturity, which lowers yield to maturity. For discount bonds the order reverses.',
  contrast:{front:'Is yield to maturity the highest yield on a bond bought above par?',answer:'No. On a premium bond the coupon rate is highest and yield to maturity is lowest.'}},
 {section:21,key:'investment-grade',topic:'Credit ratings',sources:['credit'],
  front:'What is the lowest investment-grade rating on the S&P and Moody’s scales?',
  answer:'BBB− (S&P) and Baa3 (Moody’s). Lower ratings are high-yield (junk).',
  trap:'A BB-rated bond is investment grade.',
  explanation:'Below-investment-grade bonds pay higher yields for greater default risk.',
  contrast:{front:'Is a bond rated BB by S&P considered investment grade?',answer:'No. BB is below investment grade; the lowest investment grade is BBB−.'}},
 {section:18,key:'share-classes',topic:'Mutual fund share classes',sources:['shareClasses'],
  front:'How do Class A, Class B, and Class C mutual fund shares typically charge sales costs?',
  answer:'Class A: front-end load with lower ongoing fees. Class B: declining back-end sales charge. Class C: level, higher ongoing fees with a small early-redemption charge.',
  trap:'Class C shares usually have the lowest long-term cost for large, long-term investors.',
  explanation:'For large, long-term purchases, Class A with breakpoints is often cheapest. Class C can suit shorter holding periods.',
  contrast:{front:'For a large purchase held for many years, are Class C shares usually cheaper than Class A shares?',answer:'No. Class A with breakpoints and lower ongoing fees is usually cheaper over long periods.'}},
 {section:18,key:'breakpoints',topic:'Breakpoints and rights of accumulation',sources:['breakpoints'],
  front:'What are breakpoints, and how can rights of accumulation help an investor reach them?',
  answer:'Breakpoints are dollar levels where front-end sales charges drop. Rights of accumulation count existing fund-family holdings toward the next breakpoint.',
  trap:'Only the size of today’s single purchase counts toward a breakpoint.',
  explanation:'Firms must apply available discounts. Related accounts, such as household accounts, may count depending on the fund’s rules.',
  contrast:{front:'Must a new purchase alone reach the breakpoint, ignoring existing holdings in the same fund family?',answer:'No. Rights of accumulation can count existing holdings toward the breakpoint.'}},
 {section:18,key:'letter-of-intent',topic:'Letter of intent',sources:['breakpoints'],
  front:'How long does a mutual fund letter of intent give an investor to reach a breakpoint?',
  answer:'13 months; many funds allow it to be backdated up to 90 days.',
  trap:'A letter of intent lasts 24 months.',
  explanation:'The investor gets the reduced sales charge up front. If the promised amount is not invested, the higher charge applies, often from escrowed shares.',
  contrast:{front:'If an investor fails to complete a letter of intent, does the reduced sales charge still apply?',answer:'No. The fund collects the higher sales charge, commonly from escrowed shares.'}},
 {section:18,key:'breakpoint-sale',topic:'Breakpoint sales',sources:['breakpoints'],
  front:'What is a breakpoint sale?',
  answer:'Recommending a purchase just below a breakpoint, or splitting purchases, so the customer pays a higher sales charge. It is prohibited.',
  trap:'Selling just under a breakpoint is acceptable if the customer does not ask about discounts.',
  explanation:'Representatives should tell customers when a slightly larger purchase or a letter of intent would reduce the sales charge.',
  contrast:{front:'May a representative recommend $48,000 when a $50,000 breakpoint is within reach, without telling the customer?',answer:'No. Steering a customer just below a breakpoint to earn a higher charge is prohibited.'}},
 {section:18,key:'12b-1-fee',topic:'12b-1 fees',sources:['feesFunds'],
  front:'What is a 12b-1 fee, and what limit applies to calling a fund no-load?',
  answer:'An annual fee paid from fund assets for distribution and shareholder services. A fund whose 12b-1 fee exceeds 0.25% cannot call itself no-load.',
  trap:'A 12b-1 fee is a one-time sales charge deducted at purchase.',
  explanation:'12b-1 fees are part of the fund’s ongoing expense ratio.',
  contrast:{front:'Is a 12b-1 fee a one-time charge taken when shares are purchased?',answer:'No. It is an ongoing annual fee paid from fund assets.'}},
 {section:18,key:'expense-ratio',topic:'Expense ratio',sources:['feesFunds'],
  front:'What does a fund’s expense ratio include and exclude?',
  answer:'It includes ongoing operating costs such as management and 12b-1 fees as a percentage of assets; it excludes sales loads and portfolio trading commissions.',
  trap:'The expense ratio includes front-end sales charges.',
  explanation:'Loads are paid by the investor at purchase or redemption, separate from the fund’s annual operating expenses.',
  contrast:{front:'Does a mutual fund’s expense ratio include its front-end sales load?',answer:'No. Sales loads are separate from annual operating expenses.'}},
 {section:18,key:'uit',topic:'Unit investment trusts',sources:['uit'],
  front:'What distinguishes a UIT from a mutual fund?',
  answer:'A UIT holds a fixed portfolio that is not actively managed and terminates on a set date; units are redeemable.',
  trap:'A UIT’s manager actively trades its portfolio.',
  explanation:'A UIT has no board of directors and no investment adviser making ongoing trades.',
  contrast:{front:'Does a unit investment trust employ a manager to actively trade the portfolio?',answer:'No. Its portfolio is generally fixed and unmanaged until termination.'}},
 {section:19,key:'covered-call',topic:'Covered calls',sources:['optionRights'],
  front:'What does writing a covered call do to a stock position’s income, upside, and downside?',
  answer:'It adds premium income, caps upside at the strike price, and offers only premium-sized downside protection.',
  trap:'A covered call gives full downside protection.',
  explanation:'Covered call writers expect a flat or modestly rising price. A protective put is the hedge for a real price floor.',
  contrast:{front:'Does writing a covered call protect a stock owner against a large price decline?',answer:'No. Only the premium cushions the loss; the downside remains.'},
  application:{type:'calculation',front:'An investor buys 100 shares at $50 and sells one 55-strike call for $2. What are the maximum gain and the breakeven price at expiration?',answer:'Maximum gain $700; breakeven $48.',explanation:'Max gain = ($55 − $50 + $2) × 100 = $700. Breakeven = $50 − $2 = $48.'}},
 {section:19,key:'straddle',topic:'Long straddle',sources:['optionRights'],
  front:'What market view fits a long straddle, and what is its maximum loss?',
  answer:'Expecting a large price move in either direction; the maximum loss is the total premium paid.',
  trap:'A long straddle profits most when the stock stays flat.',
  explanation:'A long straddle buys a call and a put with the same strike and expiration. A short straddle profits from little movement.',
  contrast:{front:'Does a long straddle profit most when the underlying price stays near the strike?',answer:'No. That is where the long straddle loses the most; it needs a big move.'},
  application:{type:'calculation',front:'An investor buys a 50-strike call for $3 and a 50-strike put for $2. What are the breakeven prices at expiration?',answer:'$45 and $55.',explanation:'Total premium = $5. Upside breakeven = $50 + $5 = $55; downside = $50 − $5 = $45.'}},
 {section:19,key:'option-risk',topic:'Option risk',sources:['optionRights'],
  front:'What is the maximum loss for a call buyer, and for the writer of an uncovered (naked) call?',
  answer:'The call buyer can lose only the premium; the uncovered call writer faces unlimited loss.',
  trap:'An uncovered call writer’s loss is limited to the premium received.',
  explanation:'A stock’s price has no upper limit, so a naked call writer may have to buy shares at any price to deliver them.',
  contrast:{front:'Is an uncovered call writer’s maximum loss limited like a call buyer’s?',answer:'No. The writer’s risk is unlimited; the buyer’s maximum loss is the premium.'}},
 {section:19,key:'intrinsic-value',topic:'Intrinsic and time value',sources:['optionRights'],
  front:'When is a call option in the money, and what is its intrinsic value?',
  answer:'When the stock price is above the strike price; intrinsic value is stock price minus strike price.',
  trap:'A call is in the money when the stock price is below the strike price.',
  explanation:'Premium = intrinsic value + time value. A put is in the money when the stock is below the strike.',
  contrast:{front:'Is a call option in the money when the stock trades below the strike price?',answer:'No. That call is out of the money; a put would be in the money.'},
  application:{type:'calculation',front:'A stock trades at $62. A 55-strike call costs $9. What are its intrinsic value and time value?',answer:'Intrinsic value $7; time value $2.',explanation:'$62 − $55 = $7 intrinsic. $9 premium − $7 = $2 time value.'}},
 {section:19,key:'futures-obligation',topic:'Futures versus options',sources:['derivatives'],
  front:'How do the obligations of a futures contract differ from those of an option buyer?',
  answer:'Both futures parties are obligated to perform; an option buyer has a right but no obligation.',
  trap:'A futures buyer can walk away like an option buyer.',
  explanation:'The option writer is obligated if assigned. Futures are marked to market daily and require margin from both sides.',
  contrast:{front:'Can a futures buyer let the contract expire unused like an option buyer?',answer:'No. Futures obligate both sides unless the position is closed out.'}},

 // Client investment recommendations and strategies
 {section:17,key:'client-profile',topic:'Client profile',sources:['suitability'],
  front:'What client information should an adviser gather before making a recommendation?',
  answer:'Financial situation, tax status, investment objectives, time horizon, liquidity needs, risk tolerance, experience, and other holdings.',
  trap:'A target return figure alone is enough to make a suitable recommendation.',
  explanation:'Suitability depends on the whole profile. Financial (quantitative) and nonfinancial (qualitative) information both matter.',
  contrast:{front:'Is a client’s desired return alone enough information to make a suitable recommendation?',answer:'No. The adviser needs the full profile, including risk tolerance, horizon, liquidity, and taxes.'}},
 {section:17,key:'time-horizon',topic:'Time horizon',sources:['diversification'],
  front:'How does a longer time horizon generally affect how much volatility a portfolio can tolerate?',
  answer:'A longer horizon generally allows more exposure to volatile, growth-oriented assets such as stocks.',
  trap:'A short time horizon calls for the most volatile investments.',
  explanation:'More time lets a portfolio recover from short-term declines. Money needed soon should be in stable, liquid assets.',
  contrast:{front:'Is a portfolio for a goal two years away usually the best place for aggressive small-cap stocks?',answer:'No. Short horizons generally call for stable, liquid investments.'},
  application:{type:'application',front:'A client needs a $60,000 home down payment in 12 months. Which fits better: an emerging-market stock fund or Treasury bills?',answer:'Treasury bills.',explanation:'A 12-month need calls for principal stability and liquidity, not a volatile equity fund.'}},
 {section:17,key:'strategic-allocation',topic:'Strategic asset allocation',sources:['diversification'],
  front:'What is strategic asset allocation?',
  answer:'A long-term target mix of asset classes based on the client’s goals and risk, maintained by periodic rebalancing.',
  trap:'Strategic allocation means shifting weights often to chase short-term forecasts.',
  explanation:'Short-term shifts away from the long-term targets are tactical asset allocation.',
  contrast:{front:'Is frequently shifting weights to exploit short-term forecasts called strategic asset allocation?',answer:'No. That is tactical allocation; strategic allocation sets long-term targets.'}},
 {section:17,key:'tactical-allocation',topic:'Tactical asset allocation',sources:['diversification'],
  front:'What is tactical asset allocation?',
  answer:'Temporary departures from long-term target weights to take advantage of perceived market opportunities.',
  trap:'Tactical allocation never departs from the long-term targets.',
  explanation:'It is an active approach layered on a strategic mix, and it adds timing risk and costs.',
  contrast:{front:'Does tactical asset allocation keep weights fixed at the long-term targets?',answer:'No. It deliberately moves away from targets for short-term opportunities.'}},
 {section:17,key:'rebalancing',topic:'Rebalancing',sources:['diversification'],
  front:'What does rebalancing a portfolio to its target allocation involve?',
  answer:'Selling assets that have grown above target and buying those below target to restore the intended mix.',
  trap:'Rebalancing means buying more of whatever has risen most.',
  explanation:'Rebalancing keeps risk in line with the plan. In taxable accounts it can create capital gains.',
  contrast:{front:'Does rebalancing mean adding to the asset class that has already risen above target?',answer:'No. Rebalancing trims the overweight asset and adds to the underweight one.'},
  application:{type:'calculation',front:'A $100,000 portfolio targets 60% stocks and 40% bonds. It now holds $70,000 stocks and $30,000 bonds. How much stock should be sold to rebalance?',answer:'$10,000.',explanation:'Target stocks = 60% × $100,000 = $60,000. $70,000 − $60,000 = $10,000 moved into bonds.'}},
 {section:17,key:'dollar-cost-averaging',topic:'Dollar-cost averaging',sources:['dca'],
  front:'What is dollar-cost averaging, and what does it do to the average cost per share?',
  answer:'Investing a fixed dollar amount at regular intervals; the average cost per share ends up below the average price per share.',
  trap:'Dollar-cost averaging guarantees a profit.',
  explanation:'A fixed amount buys more shares when prices are low. It does not guarantee a profit or protect against loss in a declining market.',
  contrast:{front:'Does dollar-cost averaging guarantee a profit or protect against loss in a falling market?',answer:'No. It lowers average cost relative to average price but guarantees neither.'},
  application:{type:'calculation',front:'An investor invests $300 each month at prices of $10, $15, and $30. What are the average cost per share and the average price?',answer:'Average cost $15; average price about $18.33.',explanation:'Shares: 30 + 20 + 10 = 60 for $900, so cost = $15. Average price = ($10 + $15 + $30) ÷ 3 ≈ $18.33.'}},
 {section:17,key:'growth-value',topic:'Growth and value investing',sources:['statements'],
  front:'How do growth stocks and value stocks typically differ?',
  answer:'Growth stocks usually have high P/E ratios, low dividends, and above-average expected earnings growth; value stocks trade at low P/E or price-to-book ratios.',
  trap:'Growth stocks typically have low P/E ratios and high dividends.',
  explanation:'Value investors look for stocks priced below estimated worth. Growth investors pay more for expected earnings growth.',
  contrast:{front:'Do growth stocks typically have low P/E ratios and high dividend yields?',answer:'No. Those traits fit value or income stocks; growth stocks usually have high P/Es and low dividends.'}},
 {section:17,key:'active-passive',topic:'Active and passive management',sources:['funds'],
  front:'How does active management differ from passive management?',
  answer:'Active managers try to beat a benchmark through security selection or timing; passive managers try to match an index, usually at lower cost.',
  trap:'Passive index funds try to outperform their benchmark.',
  explanation:'Active strategies usually have higher fees and turnover. Passive strategies accept market returns minus small costs.',
  contrast:{front:'Is a passive index fund designed to outperform its benchmark index?',answer:'No. It seeks to track the index; active management seeks to beat it.'}},
 {section:17,key:'modern-portfolio-theory',topic:'Modern portfolio theory',sources:['diversification'],
  front:'How does modern portfolio theory evaluate an investment?',
  answer:'By its effect on the whole portfolio’s risk and return, using correlations to diversify.',
  trap:'Modern portfolio theory judges each security in isolation.',
  explanation:'Combining assets with low correlation can reduce portfolio risk without giving up expected return.',
  contrast:{front:'Under modern portfolio theory, is each security judged only on its own risk?',answer:'No. What matters is the security’s contribution to total portfolio risk and return.'}},
 {section:17,key:'efficient-frontier',topic:'Efficient frontier',sources:['diversification'],
  front:'What does the efficient frontier represent?',
  answer:'The set of portfolios offering the highest expected return for each level of risk.',
  trap:'Portfolios below the frontier are more efficient because they have lower returns.',
  explanation:'A portfolio below the frontier could earn more for the same risk, or take less risk for the same return.',
  contrast:{front:'Is a portfolio below the efficient frontier efficient?',answer:'No. Another portfolio offers a higher expected return for the same risk.'}},
 {section:17,key:'bond-ladder',topic:'Laddered and barbell portfolios',sources:['bonds'],
  front:'How does a laddered bond portfolio differ from a barbell portfolio?',
  answer:'A ladder spreads maturities evenly across time; a barbell holds only short and long maturities with nothing in between.',
  trap:'A barbell spreads maturities evenly across every year.',
  explanation:'Ladders reduce reinvestment and interest-rate timing risk by maturing a portion regularly. A bullet concentrates maturities around one date.',
  contrast:{front:'Does a barbell portfolio hold bonds maturing evenly in every year?',answer:'No. That is a ladder; a barbell holds short and long maturities only.'}},
 {section:17,key:'margin-account',topic:'Margin accounts',sources:['margin'],
  front:'Under Regulation T, what initial margin applies to a stock purchase, and what FINRA maintenance minimum applies?',
  answer:'Regulation T initial margin is 50% of the purchase; FINRA’s minimum maintenance requirement for long stock is 25% equity.',
  trap:'Margin losses cannot exceed the investor’s original deposit.',
  explanation:'Firms may set higher requirements. Losses on a margin account can exceed the amount deposited.',
  contrast:{front:'Can losses in a margin account exceed the cash the investor deposited?',answer:'Yes. Borrowed money magnifies losses, which can exceed the original deposit.'},
  application:{type:'calculation',front:'An investor buys $20,000 of stock on margin at 50% initial margin. How much must the investor deposit?',answer:'$10,000.',explanation:'50% × $20,000 = $10,000; the broker lends the other $10,000.'}},
 {section:17,key:'margin-call',topic:'Margin call',sources:['margin'],
  front:'When does a margin call occur on a long margin account?',
  answer:'When equity falls below the maintenance requirement.',
  trap:'A margin call occurs only after the account’s value falls to zero.',
  explanation:'If the call is not met, the firm may sell securities, often without contacting the customer first.',
  contrast:{front:'Must a brokerage firm wait for a customer’s approval before selling securities to meet a margin call?',answer:'No. The firm may liquidate positions to meet the call, often without notice.'},
  application:{type:'calculation',front:'A long margin account has a $10,000 debit balance. At what market value does equity equal the 25% maintenance minimum?',answer:'About $13,333.',explanation:'Market value = debit ÷ (1 − 0.25) = $10,000 ÷ 0.75 ≈ $13,333. Equity is then $3,333, which is 25%.'}},
 {section:17,key:'short-sale',topic:'Short selling',sources:['shortSales'],
  front:'How does a short sale work, and what is its maximum potential loss?',
  answer:'The investor borrows and sells shares, hoping to buy them back cheaper. The potential loss is unlimited.',
  trap:'A short seller’s loss is limited to the original sale proceeds.',
  explanation:'A stock’s price can rise without limit. Short sales are done in a margin account, and a buy stop can limit the loss.',
  contrast:{front:'Is a short seller’s maximum loss limited to the amount received from the sale?',answer:'No. The stock can keep rising, so the potential loss is unlimited.'}},
 {section:17,key:'limit-order',topic:'Market and limit orders',sources:['orderTypes'],
  front:'How does a limit order differ from a market order?',
  answer:'A market order executes promptly at the best available price. A limit order sets a maximum buy price or minimum sell price but may not execute.',
  trap:'A limit order guarantees execution.',
  explanation:'A buy limit is placed at or below the current price; a sell limit at or above it.',
  contrast:{front:'Does a limit order guarantee that the trade will execute?',answer:'No. It guarantees the price limit, not execution; a market order prioritizes execution.'}},
 {section:17,key:'stop-order',topic:'Stop orders',sources:['orderTypes'],
  front:'What happens when the stop price on a stop order is reached, and where is a sell stop placed?',
  answer:'It becomes a market order. A sell stop is placed below the current price to limit loss on a long position.',
  trap:'A sell stop guarantees execution at the stop price.',
  explanation:'In a fast market the execution price can be well below the stop. A stop-limit order becomes a limit order instead and may not fill.',
  contrast:{front:'Does a sell stop order guarantee a sale at exactly the stop price?',answer:'No. Once triggered it becomes a market order and may fill at a different price.'}},
 {section:17,key:'prudent-investor',topic:'Uniform Prudent Investor Act',sources:['prudentInvestor'],
  front:'Under the Uniform Prudent Investor Act, how are a trustee’s investment decisions evaluated?',
  answer:'In the context of the whole portfolio and overall strategy, with a duty to diversify; no investment is imprudent in itself.',
  trap:'Each investment is judged in isolation, and certain asset types are always imprudent.',
  explanation:'The Act follows modern portfolio theory. Trustees may delegate investment functions if they select and monitor the agent prudently.',
  contrast:{front:'Under the Uniform Prudent Investor Act, is each investment judged on its own, apart from the portfolio?',answer:'No. Decisions are judged in the context of the total portfolio.'}},
 {section:15,key:'holding-period',topic:'Long-term holding period',sources:['investments'],
  front:'How long must a capital asset be held for a gain to be long-term?',
  answer:'More than one year.',
  trap:'Holding for exactly one year makes a gain long-term.',
  explanation:'Count from the day after purchase through the sale date. Inherited property is treated as long-term regardless of holding period.',
  contrast:{front:'Is a stock bought and sold exactly one year later a long-term holding?',answer:'No. It must be held more than one year.'}},
 {section:15,key:'wash-sale',topic:'Wash sales',sources:['investments'],
  front:'What is the wash-sale rule, and what happens to the disallowed loss?',
  answer:'A loss is disallowed if substantially identical securities are bought within 30 days before or after the sale; the loss is added to the new shares’ basis.',
  trap:'Only purchases after the sale can create a wash sale.',
  explanation:'The window covers 30 days on both sides of the sale. The loss is deferred, not permanently lost.',
  contrast:{front:'Can buying the same stock 20 days before selling it at a loss create a wash sale?',answer:'Yes. The window covers 30 days before and after the sale.'},
  application:{type:'calculation',front:'An investor sells stock at a $2,000 loss and buys the same stock 10 days later for $8,000. What is the basis of the new shares?',answer:'$10,000.',explanation:'The $2,000 loss is disallowed and added to the $8,000 cost: $10,000.'}},
 {section:15,key:'cost-basis-fifo',topic:'Cost basis methods',sources:['investments'],
  front:'Without specific identification of shares sold, what cost-basis method generally applies to stock?',
  answer:'First in, first out (FIFO): the earliest shares bought are treated as sold first.',
  trap:'The most recently purchased shares are sold first by default.',
  explanation:'Investors can choose specific identification at the time of sale to pick higher-basis shares and reduce gains.',
  contrast:{front:'Absent specific identification, are the most recently bought shares treated as sold first?',answer:'No. The default is first in, first out.'}},
 {section:15,key:'step-up-basis',topic:'Inherited basis',sources:['inheritance'],
  front:'What basis does an heir generally receive in inherited property?',
  answer:'Fair market value at the date of death, and any gain is long-term.',
  trap:'An heir takes the decedent’s original purchase price as basis.',
  explanation:'Gifts during life generally carry over the donor’s basis; inheritances generally get a stepped-up (or down) basis.',
  contrast:{front:'Does an heir generally use the decedent’s original cost as basis?',answer:'No. Basis is generally fair market value on the date of death.'},
  application:{type:'calculation',front:'A parent bought stock for $20,000. It was worth $50,000 at death. The heir sells it for $55,000. What gain does the heir report?',answer:'$5,000 long-term gain.',explanation:'$55,000 − $50,000 stepped-up basis = $5,000, treated as long-term.'}},
 {section:15,key:'gift-exclusion',topic:'Gift tax annual exclusion',sources:['giftTax'],
  front:'How does the annual gift tax exclusion work, and who generally pays gift tax?',
  answer:'Gifts up to the inflation-indexed annual amount per recipient avoid gift-tax reporting; the donor generally pays any gift tax.',
  trap:'The recipient of a gift generally pays the gift tax.',
  explanation:'Gifts above the exclusion require Form 709 but usually just use part of the donor’s lifetime exemption. Gifts to a U.S.-citizen spouse qualify for an unlimited marital deduction.',
  contrast:{front:'Is the recipient of a large gift generally responsible for paying gift tax?',answer:'No. The donor is generally responsible for gift tax.'}},
 {section:15,key:'estate-tax',topic:'Federal estate tax',sources:['estateTax'],
  front:'Which estates owe federal estate tax, and how are assets left to a surviving U.S.-citizen spouse treated?',
  answer:'Only taxable estates above the lifetime exemption; transfers to a U.S.-citizen spouse qualify for the unlimited marital deduction.',
  trap:'Every estate owes federal estate tax on all assets.',
  explanation:'The marital deduction defers tax until the surviving spouse’s death. Probate and estate tax are separate issues.',
  contrast:{front:'Is property left to a surviving U.S.-citizen spouse generally subject to federal estate tax at the first death?',answer:'No. The unlimited marital deduction generally shelters it.'}},
 {section:15,key:'revocable-trust',topic:'Revocable and irrevocable trusts',sources:['trusts'],
  front:'How do revocable and irrevocable trusts differ in control and estate inclusion?',
  answer:'A revocable trust can be changed by the grantor, avoids probate, but stays in the grantor’s taxable estate. An irrevocable trust generally gives up control and can remove assets from the estate.',
  trap:'A revocable living trust removes assets from the grantor’s taxable estate.',
  explanation:'Because the grantor keeps control of a revocable trust, its assets are still counted for estate tax and offer little creditor protection.',
  contrast:{front:'Does moving assets into a revocable living trust remove them from the grantor’s taxable estate?',answer:'No. Revocable trust assets remain in the estate; it mainly avoids probate.'}},

 // Laws, regulations, and unethical business practices
 {section:9,key:'fiduciary-duty',topic:'Adviser fiduciary duty',sources:['fiduciaryAdviser'],
  front:'What fiduciary duty does an investment adviser owe its clients under federal law?',
  answer:'A duty of care and a duty of loyalty that applies to the entire relationship.',
  trap:'A client contract can waive the adviser’s fiduciary duty.',
  explanation:'Care includes suitable advice, best execution, and monitoring. Loyalty requires full disclosure of conflicts and never putting the adviser’s interests first.',
  contrast:{front:'Can an adviser’s contract waive its fiduciary duty to the client?',answer:'No. Disclosure and consent can address conflicts, but the duty cannot be waived.'}},
 {section:9,key:'hedge-clause',topic:'Hedge clauses',sources:['ethics'],
  front:'May an advisory contract include a clause that waives the client’s rights under securities laws?',
  answer:'No. A hedge clause purporting to waive compliance with the law or client rights is prohibited.',
  trap:'A signed hedge clause protects the adviser from liability for negligence.',
  explanation:'Language that could mislead clients into thinking they gave up legal claims is an unethical practice.',
  contrast:{front:'Does a client’s signature on a waiver clause release the adviser from its securities-law obligations?',answer:'No. Clients cannot waive those protections by contract.'}},
 {section:9,key:'soft-dollars',topic:'Soft dollars',sources:['softDollars'],
  front:'What can an adviser receive under the Section 28(e) soft-dollar safe harbor?',
  answer:'Research and brokerage services that help investment decisions, paid for with client commissions.',
  trap:'Soft dollars may pay for office rent and furniture.',
  explanation:'Overhead such as rent, salaries, and travel falls outside the safe harbor. Soft-dollar arrangements must be disclosed.',
  contrast:{front:'May an adviser use client commissions to pay its office rent under Section 28(e)?',answer:'No. The safe harbor covers research and brokerage services, not overhead.'},
  application:{type:'application',front:'An adviser uses client commissions for an independent research database and for staff travel to a resort conference. Which fits the Section 28(e) safe harbor?',answer:'The research database.',explanation:'Research that assists investment decisions qualifies; travel and entertainment are overhead outside the safe harbor.'}},
 {section:9,key:'wrap-fee',topic:'Wrap fee programs',sources:['wrapFee'],
  front:'What does a wrap fee program charge, and when can it be unsuitable?',
  answer:'One fee covering advice, trade execution, and custody. It can be unsuitable for accounts that trade rarely.',
  trap:'A wrap fee is always cheaper than paying commissions separately.',
  explanation:'Sponsors deliver a wrap fee program brochure. Low-activity clients may pay more than they would with separate commissions.',
  contrast:{front:'Is a wrap fee account always the cheapest choice for a client who trades a few times a year?',answer:'No. Low-trading accounts may pay less with separate commissions.'}},
 {section:9,key:'form-crs',topic:'Form CRS',sources:['formCrs'],
  front:'What is Form CRS, and who must deliver it?',
  answer:'A short plain-English relationship summary that SEC-registered broker-dealers and investment advisers give retail investors.',
  trap:'Form CRS is delivered only to institutional clients.',
  explanation:'It covers services, fees, conflicts, the standard of conduct, and disciplinary history. It is limited to two pages, or four for dual registrants.',
  contrast:{front:'Is Form CRS required only for institutional clients?',answer:'No. It is a relationship summary for retail investors.'}},
 {section:9,key:'reg-bi',topic:'Regulation Best Interest',sources:['regBi'],
  front:'Whom does Regulation Best Interest cover, and what are its four obligations?',
  answer:'Broker-dealers recommending securities or strategies to retail customers. Obligations: disclosure, care, conflict of interest, and compliance.',
  trap:'Regulation Best Interest replaces an investment adviser’s fiduciary duty.',
  explanation:'Advisers acting in an advisory capacity remain subject to their Advisers Act fiduciary duty.',
  contrast:{front:'Does Regulation Best Interest replace the fiduciary duty of an investment adviser giving advice?',answer:'No. It applies to broker-dealer recommendations; advisers keep their fiduciary duty.'}},
 {section:9,key:'reg-sp',topic:'Regulation S-P',sources:['regSp'],
  front:'What does Regulation S-P require of broker-dealers and advisers regarding customer information?',
  answer:'Privacy notices describing information-sharing policies, a chance to opt out of certain sharing with nonaffiliated third parties, and safeguards for customer records.',
  trap:'Firms may freely sell customer data to any nonaffiliated company without notice.',
  explanation:'A privacy notice is given when the relationship begins, with exceptions for certain required sharing, such as processing transactions.',
  contrast:{front:'May a firm share nonpublic customer information with a nonaffiliated marketer without notice or opt-out?',answer:'No. Regulation S-P requires notice and an opportunity to opt out of that sharing.'}},
 {section:9,key:'aml-stages',topic:'Money laundering stages',sources:['aml'],
  front:'What are the three stages of money laundering, in order?',
  answer:'Placement, layering, and integration.',
  trap:'Integration comes first, when cash enters the financial system.',
  explanation:'Placement puts illicit cash into the system; layering hides its source through transactions; integration returns it as seemingly legitimate funds.',
  contrast:{front:'Is integration the first stage, when illicit cash first enters the financial system?',answer:'No. Placement is first; integration is the final stage.'}},
 {section:9,key:'ctr-sar',topic:'CTRs and SARs',sources:['aml'],
  front:'What are the thresholds for a Currency Transaction Report and for a broker-dealer’s Suspicious Activity Report?',
  answer:'CTR: cash transactions over $10,000 in a day. SAR: suspicious transactions of $5,000 or more.',
  trap:'A SAR is filed only for cash over $10,000.',
  explanation:'The customer must not be told a SAR was filed. Firms also maintain AML programs under FINRA Rule 3310.',
  contrast:{front:'Must a firm tell a customer that it filed a Suspicious Activity Report?',answer:'No. Disclosing a SAR filing to the customer is prohibited.'}},
 {section:9,key:'structuring',topic:'Structuring',sources:['aml'],
  front:'What is structuring?',
  answer:'Breaking cash transactions into smaller amounts to avoid the $10,000 Currency Transaction Report. It is illegal even if the money is legitimate.',
  trap:'Splitting deposits to stay under $10,000 is legal when the funds are clean.',
  explanation:'Several deposits of just under $10,000 are a red flag that should be escalated.',
  contrast:{front:'Is deliberately splitting legitimate cash into $9,000 deposits to avoid a CTR legal?',answer:'No. Structuring is illegal regardless of the money’s source.'}},
 {section:9,key:'cip',topic:'Customer Identification Program',sources:['aml'],
  front:'What minimum information must a Customer Identification Program collect before opening an individual’s account?',
  answer:'Name, date of birth, address, and an identification number, such as a Social Security number.',
  trap:'A name and phone number are enough to open the account.',
  explanation:'The firm must verify identity and check government lists, such as OFAC’s sanctions list.',
  contrast:{front:'Is a customer’s name and email address enough to satisfy the Customer Identification Program?',answer:'No. Name, date of birth, address, and an ID number are required.'}},
 {section:9,key:'senior-hold',topic:'Senior investor protection',sources:['finra2165'],
  front:'Under FINRA Rule 2165, what may a firm do if it reasonably believes a senior customer is being financially exploited?',
  answer:'Place a temporary hold on disbursements of funds or securities, initially up to 15 business days, with extensions allowed under the rule.',
  trap:'The rule lets a firm freeze the account indefinitely without notice.',
  explanation:'The rule covers customers 65 and older, or 18 and older with a mental or physical impairment. Firms must notify authorized parties and investigate.',
  contrast:{front:'Does FINRA Rule 2165 let a firm freeze a senior customer’s account indefinitely without notice?',answer:'No. Holds are temporary, time-limited, and require notice and investigation.'}},
 {section:9,key:'trusted-contact',topic:'Trusted contact person',sources:['finra4512'],
  front:'What role does a trusted contact person have under FINRA Rule 4512?',
  answer:'A person the firm may contact about possible exploitation or to confirm the customer’s health or whereabouts; the contact cannot trade in the account.',
  trap:'A trusted contact can place trades for the customer.',
  explanation:'Firms must make reasonable efforts to get a trusted contact for noninstitutional accounts, but customers may decline.',
  contrast:{front:'Does naming a trusted contact give that person authority to trade the account?',answer:'No. The trusted contact has no trading authority.'}},
 {section:9,key:'insider-trading',topic:'Insider trading',sources:['insiderTrading'],
  front:'What is illegal insider trading, and can a tippee be liable?',
  answer:'Trading on material nonpublic information in breach of a duty. A tippee who knows the tip came from a breach can also be liable.',
  trap:'Only company employees can be liable for insider trading.',
  explanation:'Information is material if a reasonable investor would consider it important. It stops being nonpublic once widely disseminated.',
  contrast:{front:'Can someone who does not work at the company be liable for trading on a tip of material nonpublic information?',answer:'Yes. Tippees who know the information was improperly disclosed can be liable.'}},
 {section:9,key:'insider-penalty',topic:'Insider trading penalties',sources:['insiderTrading'],
  front:'What maximum civil penalty may the SEC seek for insider trading?',
  answer:'Up to three times the profit gained or loss avoided.',
  trap:'The civil penalty is capped at the profit gained.',
  explanation:'Criminal penalties and disgorgement can apply separately. Firms that fail to supervise can also face penalties.',
  contrast:{front:'Is the SEC’s insider-trading civil penalty limited to the profit gained?',answer:'No. It can be up to three times the profit gained or loss avoided.'}},
 {section:9,key:'code-of-ethics',topic:'Adviser code of ethics',sources:['codeOfEthics'],
  front:'What personal-trading reports does an SEC-registered adviser’s code of ethics require from access persons?',
  answer:'An initial and annual holdings report and quarterly transaction reports, plus preapproval for IPOs and private placements.',
  trap:'Access persons report their holdings only once, when hired.',
  explanation:'Rule 204A-1 aims to prevent employees from front-running or misusing client information.',
  contrast:{front:'Do access persons report personal holdings only once, when they join the firm?',answer:'No. Holdings are reported initially and annually, and transactions quarterly.'}},
 {section:9,key:'selling-away',topic:'Selling away',sources:['sellingAway'],
  front:'What is selling away?',
  answer:'An agent taking part in private securities transactions outside the firm without first giving the firm written notice and, if paid, getting its written approval. It is prohibited.',
  trap:'An agent may sell outside investments as long as the firm is not involved.',
  explanation:'The agent must give written notice first; if paid, the firm must approve and supervise the activity as its own.',
  contrast:{front:'May an agent sell a friend’s private offering to customers without telling the employing firm?',answer:'No. That is selling away; written notice and firm approval are required.'}},
 {section:9,key:'confidentiality',topic:'Client confidentiality',sources:['ethics'],
  front:'May an adviser disclose a client’s identity, holdings, or affairs to others?',
  answer:'Not without client consent, unless required by law, such as a regulatory request or court order.',
  trap:'An adviser may share client holdings with a prospect as a reference.',
  explanation:'Unauthorized disclosure is an unethical practice under NASAA’s model rule.',
  contrast:{front:'May an adviser show a prospect another client’s portfolio without that client’s consent?',answer:'No. Client information is confidential without consent or legal requirement.'}},
 {section:9,key:'investment-counsel',topic:'Investment counsel title',sources:['acts'],
  front:'When may an adviser call itself investment counsel?',
  answer:'Only if its principal business is giving investment advice and a substantial part is providing investment supervisory services.',
  trap:'Any registered adviser may use the title investment counsel.',
  explanation:'The restriction in Advisers Act Section 208(c) prevents misleading use of a title implying ongoing portfolio supervision.',
  contrast:{front:'May any SEC-registered adviser call itself investment counsel?',answer:'No. The title requires advice as the principal business plus substantial supervisory services.'}},
 {section:9,key:'performance-fee',topic:'Performance-based fees',sources:['qualifiedRule'],
  front:'Which advisory clients may be charged performance-based fees?',
  answer:'Qualified clients, subject to the rule’s conditions.',
  trap:'Any client who signs a consent may pay a performance fee.',
  explanation:'Performance fees can encourage excessive risk-taking, so they are limited to clients meeting qualified-client thresholds.',
  contrast:{front:'May an adviser charge a performance fee to any retail client who consents in writing?',answer:'No. Performance fees are generally limited to qualified clients.'}},
];
