import type { OfficialSource } from '../lib/model';
import { officialSources } from './official-sources';

/** Independently authored concepts requested September 13, 2026.
 * Vendor text is not an input to the importer. Every source below was inspected
 * for the precise provision; a NASAA-hosted comment or outline is not enough.
 * The source check enforces the host/type boundary, not substantive accuracy.
 */
export interface NasaaRule {
 section:number; key:string; source:OfficialSource; clause:string;
 front:string; answer:string; trap:string; explanation:string;
 contrast:{front:string;answer:string};
}
const at=(id:'usa'|'ethics'|'custody'|'financialReporting',clause:string,page:number):OfficialSource=>({
 ...officialSources[id],title:`${officialSources[id].title} — ${clause}`,url:`${officialSources[id].url}#page=${page}`,
});
const etf:OfficialSource={authority:'NASAA',kind:'guidance',title:'Leveraged/inverse ETF report — executive summary and footnote 1',url:'https://www.nasaa.org/wp-content/uploads/2019/07/2019-BD-Study-of-Exchange-Traded-Funds-FINAL.pdf#page=2'};
export function assertNasaaSource(source:OfficialSource,clause:string):void {
 const url=new URL(source.url);
 if(source.authority!=='NASAA'||url.protocol!=='https:'||url.hostname!=='www.nasaa.org'||url.username||url.password||source.kind==='outline'||!clause.trim()) {
  throw new Error('Supplement requires a precise, inspected NASAA source.');
 }
}
export const nasaaRules:NasaaRule[]=[
 {section:1,key:'nasaa-bd-advice',source:at('usa','401(f)(4)',33),clause:'401(f)(4)',
  front:'What two conditions let a broker-dealer use the incidental-advice exclusion under the Uniform Securities Act?',
  answer:'The advice is solely incidental to brokerage business, and there is no special compensation for it.',
  trap:'Broker-dealer registration covers separately paid advisory services automatically.',
  explanation:'Test the advisory activity separately when either condition fails. The brokerage exclusion is conditional.',
  contrast:{front:'A broker-dealer charges a separate fee for ongoing securities advice. Can it rely on the incidental-advice exclusion?',answer:'No. Special compensation defeats this exclusion; adviser requirements must be evaluated.'}},
 {section:1,key:'nasaa-economist',source:at('usa','401(f)(3)',33),clause:'401(f)(3)',
  front:'Does the Uniform Securities Act give economists the same named incidental-profession exclusion as lawyers and teachers?',
  answer:'No. The named professions are lawyer, accountant, engineer, and teacher; economist is not on that list.',
  trap:'Every profession that analyzes financial information gets the exclusion.',
  explanation:'Someone may qualify for a different exclusion, but the title economist alone supplies none under this provision.',
  contrast:{front:'An economist regularly charges clients for individualized securities recommendations. Does the professional title alone remove adviser status?',answer:'No. Evaluate the securities-advice business and compensation; economist is not a named professional exclusion.'}},
 {section:1,key:'nasaa-publisher',source:at('usa','401(f)(5)',33),clause:'401(f)(5)',
  front:'What distinguishes the Uniform Securities Act publisher exclusion from individualized advisory services?',
  answer:'A bona fide publication gives impersonal information, rather than advice tailored to each subscriber’s investment situation.',
  trap:'Putting personalized advice in a newsletter automatically creates an exclusion.',
  explanation:'The delivery format can be print or electronic. The service’s substance, including whether it is individualized, matters.',
  contrast:{front:'A paid newsletter sends each subscriber trades selected for that subscriber’s finances. Does calling it a newsletter establish the publisher exclusion?',answer:'No. Tailoring recommendations to each subscriber’s situation defeats this publisher exclusion.'}},
 {section:3,key:'nasaa-registration-filers',source:at('usa','305(a)',26),clause:'305(a)',
  front:'Who may file a securities registration statement under the Uniform Securities Act?',
  answer:'The issuer, another person on whose behalf the offering is made, or a registered broker-dealer.',
  trap:'Any registered agent has the same filing capacity as a broker-dealer.',
  explanation:'An agent’s registration alone does not put the individual into the broker-dealer category in this provision.',
  contrast:{front:'Must the issuer personally file every state securities registration statement?',answer:'No. A registered broker-dealer or another person on whose behalf the offering is made may also file.'}},
 {section:5,key:'nasaa-criminal-ceiling',source:at('usa','409(a)',48),clause:'409(a)',
  front:'What maximum fine and imprisonment does the 1956 Uniform Securities Act provide for a qualifying willful violation?',
  answer:'Up to $5,000, up to three years in prison, or both.',
  trap:'These are the maximum penalties under every state and federal securities law.',
  explanation:'This is the model Act’s criminal ceiling. Actual state statutes and federal law may differ; civil recovery is a separate question.',
  contrast:{front:'Under the 1956 Uniform Securities Act, must a court choose between a $5,000 fine and three years’ imprisonment?',answer:'No. The provision permits both, subject to its conditions.'}},
 {section:5,key:'nasaa-appeal-deadline',source:at('usa','411(a)',51),clause:'411(a)',
  front:'Under the Uniform Securities Act, how long does an aggrieved person have to seek court review of a final Administrator order?',
  answer:'File the petition within 60 days after entry of the final order.',
  trap:'Use the civil damages limitation period to appeal an administrative order.',
  explanation:'Judicial review of an order has its own filing clock; it is different from an investor’s damages lawsuit.',
  contrast:{front:'A final Administrator order was entered 45 days ago. Under the model Act’s ordinary review clock, how many days remain to file a petition?',answer:'15 days. The petition must be filed within 60 days after the order was entered.'}},
 {section:5,key:'nasaa-appeal-stay',source:at('usa','411(b)',52),clause:'411(b)',
  front:'Does filing for court review automatically pause a final Administrator order?',
  answer:'No. The order remains operative unless the court specifically orders a stay.',
  trap:'An appeal itself cancels the order’s effect.',
  explanation:'Asking a court to review an order and obtaining a pause in its enforcement are separate steps.',
  contrast:{front:'A registrant appeals a suspension but obtains no court-ordered stay. May the registrant resume the suspended activity just because review is pending?',answer:'No. Filing the appeal does not itself suspend the order.'}},
 {section:5,key:'nasaa-civil-recovery',source:at('usa','410(a)',49),clause:'410(a)',
  front:'Under the model Act, what can an eligible buyer generally recover by tendering a security in a civil rescission claim?',
  answer:'The purchase amount plus statutory interest, costs, and reasonable attorney fees, less income received from the security.',
  trap:'Civil recovery automatically equals three times the original investment.',
  explanation:'Tender means offering to return the security. The statute uses a separate damages computation when the buyer no longer owns it.',
  contrast:{front:'A buyer wins an eligible rescission claim after receiving dividends. Does the model Act let the buyer ignore that income when computing recovery?',answer:'No. Income received from the security reduces the statutory recovery.'}},
 {section:5,key:'nasaa-offer-jurisdiction',source:at('usa','414(a)–(d)',53),clause:'414(a)–(d)',
  front:'For the model Act’s offer rules, when is an offer made in a state?',
  answer:'When it originates there, or is directed there and received at its intended destination.',
  trap:'Only the issuer’s home state can have authority over the offer.',
  explanation:'Acceptance has a separate communication test. More than one state can have jurisdiction over one offering.',
  contrast:{front:'An offer originates in State A and is directed to and received by a buyer in State B. Can both states have jurisdiction over the offer?',answer:'Yes. State A is the origin; State B is where the directed offer was received.'}},
 {section:5,key:'nasaa-supervision',source:at('usa','204(a)(2)(J)',14),clause:'204(a)(2)(J)',
  front:'Can an investment adviser face discipline for failing reasonably to supervise its representatives?',
  answer:'Yes. Failure to supervise for compliance is a disciplinary ground under the model Act, with the required public-interest finding.',
  trap:'Only the representative who committed the violation can face consequences.',
  explanation:'The firm’s own supervision duty is distinct from the representative’s conduct. This card addresses the state model Act.',
  contrast:{front:'An advisory firm ignores repeated compliance violations by its representatives. Does employing registered people satisfy its supervision duty?',answer:'No. Registration does not replace reasonable supervision.'}},
 {section:5,key:'nasaa-insolvency',source:at('usa','204(a)(1), (2)(H)',12),clause:'204(a)(1), (2)(H)',
  front:'Can a firm’s insolvency support denial, suspension, or revocation under the model Act?',
  answer:'Yes, with a finding that the action is in the public interest and that the firm itself is insolvent.',
  trap:'A partner’s personal money problem automatically proves the firm is insolvent.',
  explanation:'Insolvency can mean liabilities exceed assets or the firm cannot meet obligations as they mature. Required procedures still apply.',
  contrast:{front:'One partner cannot pay a personal loan, but the adviser is solvent. Does that fact alone establish the firm-insolvency ground?',answer:'No. This ground requires an insolvency finding about the firm itself.'}},
 {section:5,key:'nasaa-conviction',source:at('usa','204(a)(1), (2)(C)',12),clause:'204(a)(1), (2)(C)',
  front:'Which convictions within the preceding ten years are specified disciplinary grounds in the Uniform Securities Act?',
  answer:'Any felony, or a misdemeanor involving a security or the securities business; the public-interest requirement also applies.',
  trap:'An accusation alone is a conviction under this provision.',
  explanation:'This is the state model Act’s conviction ground, not a complete account of federal statutory disqualification or every disclosure duty.',
  contrast:{front:'An applicant has only been accused of an offense. Does the accusation alone satisfy the model Act’s conviction ground?',answer:'No. An accusation is not a conviction; other properly established grounds must be evaluated separately.'}},
 {section:5,key:'nasaa-custody-separate',source:at('custody','102(e)(1)-1(a)(2)',1),clause:'102(e)(1)-1(a)(2)',
  front:'Under NASAA’s custody model, how must client assets be separated from the adviser’s own assets?',
  answer:'Use a qualified custodian and properly titled client accounts; client assets must not be mixed with the adviser’s money.',
  trap:'Keeping a spreadsheet makes a personal bank account acceptable for client funds.',
  explanation:'The model permits individual client accounts or accounts containing only client assets under the adviser as agent or trustee, with separate pooled-vehicle treatment.',
  contrast:{front:'An adviser temporarily deposits client investment money into its own operating account but tracks each deposit. Is recordkeeping enough to permit this?',answer:'No. Accurate records do not make commingling client and adviser assets permissible.'}},
 {section:5,key:'nasaa-custody-statements',source:at('custody','102(e)(1)-1(a)(4)',1),clause:'102(e)(1)-1(a)(4)',
  front:'Under NASAA’s ordinary custody model, how often must the qualified custodian send client account statements?',
  answer:'At least quarterly, identifying holdings, funds, and transactions during the period.',
  trap:'A statement every six months satisfies the ordinary quarterly requirement.',
  explanation:'The adviser must have a reasonable basis, after due inquiry, for believing the custodian sends the statements. Special pooled-fund exceptions require their own analysis.',
  contrast:{front:'A custodian sends statements only twice a year. With no applicable exception, does this satisfy NASAA’s ordinary custody model?',answer:'No. The ordinary requirement is at least quarterly.'}},
 {section:5,key:'nasaa-custody-return',source:at('custody','102(e)(1)-1(d)(2)(A)(i)',8),clause:'102(e)(1)-1(d)(2)(A)(i)',
  front:'What must an adviser do with inadvertently received client assets to use NASAA’s three-business-day custody exception?',
  answer:'Return them to the sender within three business days and keep the required records.',
  trap:'The exception allows the adviser to retain an accidental receipt indefinitely.',
  explanation:'This exception requires inadvertent receipt, timely return, and records. It does not authorize deliberately accepting custody.',
  contrast:{front:'An adviser inadvertently receives a client’s investment check payable to the adviser. Can it keep the check for a week while relying on the inadvertent-receipt exception?',answer:'No. The exception requires return to the sender within three business days, plus the required records.'}},
 {section:5,key:'nasaa-custody-forward',source:at('custody','102(e)(1)-1(d)(2)(B)',8),clause:'102(e)(1)-1(d)(2)(B)',
  front:'When does receiving a client check payable to a third party avoid custody under NASAA’s check-forwarding rule?',
  answer:'When the adviser forwards it to the third party within three business days and keeps the required records.',
  trap:'A check payable to the adviser is treated the same as one payable to a third party.',
  explanation:'Read the payee first. The third-party forwarding rule and the inadvertent-receipt return rule are distinct.',
  contrast:{front:'An adviser receives a check payable to the client’s custodian, forwards it the next business day, and keeps the required records. Does receiving this check alone create custody?',answer:'No. Those facts satisfy NASAA’s third-party check-forwarding exception.'}},
 {section:5,key:'nasaa-custody-exam',source:at('custody','102(e)(1)-1(a)(6)',2),clause:'102(e)(1)-1(a)(6)',
  front:'Absent an exception, how often does NASAA’s custody model require an independent examination of client assets?',
  answer:'At least once each calendar year, at an unannounced time chosen by the independent accountant.',
  trap:'The adviser may pick the examination date to make it predictable.',
  explanation:'A written engagement and irregular timing are required. Under this state model, the accountant files Form ADV-E with the Administrator; federal filing rules are separate.',
  contrast:{front:'An adviser has custody only through qualifying fee deductions. Must you ignore custody-model exceptions and automatically demand a surprise examination?',answer:'No. Test the applicable exception and its safeguards before deciding whether an examination is required.'}},
 {section:5,key:'nasaa-custody-balance',source:at('financialReporting','203(c)-1(a)',1),clause:'203(c)-1(a)',
  front:'Under NASAA’s financial-reporting model, can custody trigger an audited balance sheet even without substantial prepaid fees?',
  answer:'Yes. Custody is a separate trigger for the adviser’s fiscal-year-end audited balance sheet.',
  trap:'Both custody and substantial prepayment must occur together.',
  explanation:'The model uses alternative triggers. This financial statement reports on the adviser; it is distinct from a surprise examination of client assets.',
  contrast:{front:'A state adviser has custody but bills after providing services. Does the absence of prepaid fees alone remove the model’s audited-balance-sheet requirement?',answer:'No. Custody independently triggers that financial-reporting requirement.'}},
 {section:6,key:'nasaa-isolated-sale',source:at('usa','402(b)(1)',39),clause:'402(b)(1)',
  front:'Does the model Act’s isolated nonissuer transaction exemption require use of a broker-dealer?',
  answer:'No. An isolated nonissuer transaction can qualify whether or not a broker-dealer is involved.',
  trap:'An isolated transaction makes every later sale of the same security exempt.',
  explanation:'The exemption concerns that transaction. Nonissuer means the transaction does not directly or indirectly benefit the issuer.',
  contrast:{front:'An investor makes a qualifying isolated nonissuer sale without a broker. Does the lack of a broker defeat this transaction exemption?',answer:'No. The isolated nonissuer exemption does not require a broker-dealer.'}},
 {section:6,key:'nasaa-unsolicited-sale',source:at('usa','402(b)(3)',41),clause:'402(b)(3)',
  front:'What unsolicited-order transaction does the Uniform Securities Act specifically exempt?',
  answer:'A nonissuer transaction through a registered broker-dealer pursuant to an unsolicited order or offer to buy.',
  trap:'A salesperson can solicit a purchase and then label the resulting order unsolicited.',
  explanation:'The Administrator may require a signed customer acknowledgment and retention of that record. The transaction exemption does not waive seller registration.',
  contrast:{front:'A registered broker-dealer recommends a purchase and the customer agrees. Does customer agreement make it an unsolicited transaction?',answer:'No. The firm solicited the purchase; customer agreement does not change that.'}},
 {section:6,key:'nasaa-underwriting-sale',source:at('usa','402(b)(4)',41),clause:'402(b)(4)',
  front:'Is an issuer-to-underwriter transaction an exempt transaction under the Uniform Securities Act?',
  answer:'Yes. The Act also exempts transactions among underwriters under this provision.',
  trap:'The underwriter’s later retail distribution automatically has the same exemption.',
  explanation:'Each transaction needs its own analysis. The issuer-to-underwriter exemption does not carry over to every subsequent buyer.',
  contrast:{front:'An underwriter buys from an issuer and then sells to retail investors. Does the first transaction’s exemption automatically exempt those retail sales?',answer:'No. The retail transactions require a separate registration or exemption analysis.'}},
 {section:6,key:'nasaa-estate-sale',source:at('usa','402(b)(6)',41),clause:'402(b)(6)',
  front:'Does the Uniform Securities Act specifically exempt transactions by an executor or estate administrator?',
  answer:'Yes. Both are included in the listed fiduciary transaction exemption.',
  trap:'Anyone claiming to be an heir automatically has the executor’s authority or exemption.',
  explanation:'The listed capacity matters. This securities exemption does not establish who has legal authority to act for a particular estate.',
  contrast:{front:'An estate’s duly appointed administrator sells estate securities in that capacity. Does the model Act identify this as an exempt transaction?',answer:'Yes. Transactions by an administrator fall within the listed exemption.'}},
 {section:6,key:'nasaa-pledgee-sale',source:at('usa','402(b)(7)',41),clause:'402(b)(7)',
  front:'What condition qualifies a pledgee’s transaction for the model Act’s collateral-sale exemption?',
  answer:'It must be a bona fide pledgee transaction, without a purpose of evading the Act.',
  trap:'Calling an arranged securities sale a loan liquidation guarantees an exemption.',
  explanation:'A pledgee holds collateral for a genuine obligation. An arrangement designed to evade registration does not meet this exemption.',
  contrast:{front:'A lender sells genuinely pledged securities after default, without a scheme to evade registration. Which transaction exemption fits?',answer:'The bona fide pledgee transaction exemption.'}},
 {section:6,key:'nasaa-commercial-paper',source:at('usa','402(a)(10)',39),clause:'402(a)(10)',
  front:'What maturity, denomination, and rating conditions define the commercial-paper exemption in the model Act?',
  answer:'Payment within nine months, denominations of at least $50,000, and a rating in one of the top three categories.',
  trap:'A short maturity alone is enough.',
  explanation:'These conditions operate together. The Act states nine months; do not replace this state test with a different federal offering exemption.',
  contrast:{front:'A note matures in seven months and has a top-category rating, but its denomination is $20,000. Does it meet this model Act exemption?',answer:'No. The denomination must be at least $50,000.'}},
 {section:6,key:'nasaa-charity-security',source:at('usa','402(a)(9)',39),clause:'402(a)(9)',
  front:'Under the model Act, can securities of a qualifying nonprofit charitable issuer be exempt from state securities registration?',
  answer:'Yes. The issuer must be organized and operated not for private profit and exclusively for a listed purpose.',
  trap:'Donating part of a for-profit company’s revenue makes its securities exempt.',
  explanation:'The exemption turns on the issuer’s organization and operation, not merely a charitable use of some sales proceeds. Antifraud duties remain.',
  contrast:{front:'A for-profit company gives 5% of revenue to charity. Does that fact alone establish the nonprofit-issuer securities exemption?',answer:'No. Occasional charitable giving does not make the issuer a qualifying nonprofit organization.'}},
 {section:6,key:'nasaa-insurer-security',source:at('usa','402(a)(5)',38),clause:'402(a)(5)',
  front:'For the model Act’s insurance-company securities exemption, what state authorization matters?',
  answer:'The insurer is organized under a state’s laws and authorized to do business in the state where the exemption is claimed.',
  trap:'Authorization in its home state alone is sufficient everywhere.',
  explanation:'This objective concerns the insurer’s ordinary stock or debt. Do not generalize it to every variable insurance contract; the model text treats those separately.',
  contrast:{front:'An insurer seeks the exemption for its ordinary debt in State B but is authorized only in State A. Does home-state authorization alone satisfy the State B condition?',answer:'No. It must be authorized to do business in State B for that condition to be met.'}},
 {section:9,key:'nasaa-third-party-orders',source:at('ethics','102(a)(4)-1(e)',2),clause:'102(a)(4)-1(e)',
  front:'Before an adviser acts on a third party’s trade instruction for a client, what authorization must it obtain?',
  answer:'The client’s written third-party trading authorization, obtained before the order.',
  trap:'A close relationship to the client substitutes for written authority.',
  explanation:'The separate ten-business-day accommodation for the adviser’s oral discretion does not waive this third-party requirement.',
  contrast:{front:'A client’s sibling requests a sale, but no written third-party authority is on file. May the adviser act merely because the sibling knows the account details?',answer:'No. Obtain the client’s written third-party trading authorization first.'}},
 {section:9,key:'nasaa-borrow-client',source:at('ethics','102(a)(4)-1(f)',2),clause:'102(a)(4)-1(f)',
  front:'Under NASAA’s adviser model, which client categories can fall within the exception to borrowing from clients?',
  answer:'A broker-dealer, an adviser affiliate, or a financial institution in the lending business.',
  trap:'Every wealthy client who agrees to lend qualifies.',
  explanation:'This is the adviser model’s borrowing provision. Do not assume broker-dealer agents have identical exceptions.',
  contrast:{front:'An adviser wants a personal loan from an ordinary individual client who is not an affiliate. Does the client’s willingness make it permissible under this provision?',answer:'No. Consent alone does not place the client in a permitted lender category.'}},
 {section:9,key:'nasaa-lend-client',source:at('ethics','102(a)(4)-1(g)',2),clause:'102(a)(4)-1(g)',
  front:'Under NASAA’s adviser model, when may an adviser fall within the exception to lending money to a client?',
  answer:'When the adviser is a financial institution in the lending business, or the client is an adviser affiliate.',
  trap:'The borrowing exception and lending exception have identical wording.',
  explanation:'Identify who lends and who borrows before selecting the exception.',
  contrast:{front:'An ordinary advisory firm lends to an unrelated retail client and obtains written consent. Does consent alone satisfy the model’s lending exception?',answer:'No. The stated facts meet neither the financial-institution nor affiliate exception.'}},
 {section:9,key:'nasaa-excessive-trading',source:at('ethics','102(a)(4)-1(c)',1),clause:'102(a)(4)-1(c)',
  front:'What makes trading excessive under NASAA’s adviser conduct model?',
  answer:'Its size or frequency is excessive for the account’s resources, objectives, and character, while the adviser can benefit from the transactions.',
  trap:'A longstanding relationship or discretionary authority makes excessive trading acceptable.',
  explanation:'Repeated trading to increase compensation is commonly called churning. Evaluate the activity against the client’s circumstances.',
  contrast:{front:'An adviser repeatedly trades a conservative client’s account to generate more compensation. Does having served the client for years excuse the activity?',answer:'No. The length of the relationship does not excuse excessive trading.'}},
 {section:9,key:'nasaa-conflict-timing',source:at('ethics','102(a)(4)-1(k)',2),clause:'102(a)(4)-1(k)',
  front:'Under NASAA’s adviser model, when and how must a material conflict capable of impairing objective advice be disclosed?',
  answer:'In writing, before the advice is given.',
  trap:'Disclosure after the client trades is always sufficient.',
  explanation:'Conflicts can involve the adviser or employees, including additional compensation connected with the advice. The source addresses material conflicts, not every incidental personal preference.',
  contrast:{front:'An adviser will receive extra compensation connected with its recommendation. May it wait until after giving the advice to disclose this material conflict?',answer:'No. Written disclosure must precede the advice under this model provision.'}},
 {section:9,key:'nasaa-individual-fit',source:at('ethics','102(a)(4)-1(a)',1),clause:'102(a)(4)-1(a)',
  front:'Before recommending the same security to several clients, what must an adviser establish for each client?',
  answer:'Reasonable grounds for suitability based on inquiry into that client’s objectives, finances, needs, and other known information.',
  trap:'One investment is suitable for everyone simply because it is suitable for one client.',
  explanation:'Several clients can receive the same suitable recommendation. Skipping the individual assessment is the problem.',
  contrast:{front:'An adviser recommends one fund to every client without reviewing their circumstances. Does the fund’s good performance make that process adequate?',answer:'No. Performance does not replace the required client-specific suitability assessment.'}},
 {section:9,key:'nasaa-no-guarantee',source:at('ethics','102(a)(4)-1(l)',2),clause:'102(a)(4)-1(l)',
  front:'May an adviser guarantee that its securities advice will produce a gain or prevent a loss?',
  answer:'No. NASAA’s adviser model prohibits guaranteeing those specific investment results.',
  trap:'Confidence in the strategy or client consent makes a result guarantee acceptable.',
  explanation:'Describe an investment’s actual contractual protections accurately; do not turn them into the adviser’s promise of an investment result.',
  contrast:{front:'An adviser promises that a recommended stock strategy cannot lose money. Does using a diversified portfolio make that promise permissible?',answer:'No. Diversification does not permit the adviser to guarantee no loss.'}},
 {section:9,key:'nasaa-covered-fraud',source:at('ethics','Introduction — federal covered advisers',1),clause:'Introduction — federal covered advisers',
  front:'Does federal covered adviser status eliminate state authority over fraudulent or deceptive conduct?',
  answer:'No. State antifraud authority remains, within federal preemption limits.',
  trap:'SEC registration prevents every state investigation.',
  explanation:'The model expressly limits its application to federal covered advisers to fraud, deception, or other conduct permitted by federal law. It does not create general state registration authority over the firm.',
  contrast:{front:'A federally registered adviser claims the state cannot investigate alleged client fraud because the firm is SEC-registered. Is that claim correct?',answer:'No. Federal registration does not erase state antifraud authority.'}},
 {section:18,key:'nasaa-inverse-daily',source:etf,clause:'Executive summary and footnote 1, PDF page 2',
  front:'What does a daily inverse ETF seek to do?',
  answer:'Produce the opposite of its benchmark’s daily return, before fees and tracking differences.',
  trap:'Its daily objective guarantees the opposite return over a month or year.',
  explanation:'The daily reset matters. Compounding can make a longer holding period differ substantially from the stated daily objective.',
  contrast:{front:'A daily inverse ETF tracks an index that falls over a month. Must the fund gain exactly the opposite percentage over that month?',answer:'No. A daily objective does not guarantee the corresponding monthly return.'}},
 {section:18,key:'nasaa-leverage-direction',source:etf,clause:'Executive summary footnote 1, PDF page 2',
  front:'Does leveraged ETF necessarily mean inverse ETF?',
  answer:'No. Leverage targets a multiple; inverse describes the opposite direction. A fund may have either feature or both.',
  trap:'Every leveraged fund profits when its benchmark falls.',
  explanation:'A positive daily multiple and a negative daily multiple have different directional objectives. Neither promises the same multiple over a longer holding period.',
  contrast:{front:'One daily ETF targets +2 times an index’s return; another targets −2 times. Which one is inverse?',answer:'The −2-times fund is inverse. Both are leveraged.'}},
];
