import type { ApplicationSeed } from './applications';

/** Independent authoring for the user's September 13, 2026 review checklist.
 * Supplements the unchanged canonical sheet; does not purport to be extracted from it.
 * Every rule has a recall and a complete contrast pair. Sources are mapped by key.
 * All wording and numerical examples are original; all cards remain draft.
 */
export interface ReviewRule {
 section:number; key:string; point:number; front:string; answer:string;
 trap:string; explanation:string; contrast:{front:string;answer:string};
 memoryHook?:string;
 application?:Omit<ApplicationSeed,'section'|'key'>;
}
export const reviewRules:ReviewRule[] = [
 {section:6,key:'registration-approval',point:1,
  front:'Does registration mean a regulator has approved the investment or endorsed the professional?',
  answer:'No. Registration is not approval, endorsement, or a guarantee of investment merit.',
  trap:'An effective registration proves that the regulator recommends the investment.',
  explanation:'A regulator can process a registration without vouching for the security, the registrant, or the accuracy of every filed statement. Claiming otherwise is misleading.',
  contrast:{front:'A salesperson says a registered offering is recommended by the state Administrator. Is that claim permitted?',answer:'No. State registration does not mean the Administrator recommends or approves the offering.'}},
 {section:6,key:'exemption-scope',point:2,
  front:'What is exempt in an exempt security, and what is exempt in an exempt transaction?',
  answer:'An exempt security has a registration exemption based on its class. An exempt transaction exempts only the particular transaction.',
  trap:'One exempt sale permanently exempts the security and everyone who sells it.',
  explanation:'Test the security, the transaction, and the seller separately. An exemption from registration does not remove antifraud duties.',
  contrast:{front:'Ordinary corporate shares are sold in an exempt transaction. Is every later resale automatically exempt too?',answer:'No. Each later transaction needs its own registration basis or exemption.'}},
 {section:6,key:'municipal-issuer',point:3,
  front:'A city issues bonds exempt from state securities registration. Who is the issuer?',
  answer:'The city. The registration exemption does not eliminate the issuer.',
  trap:'An exempt municipal bond is a security without an issuer.',
  explanation:'An issuer issues or proposes to issue the security. Governmental identity can support the exemption; it does not erase that role.',
  contrast:{front:'A municipal bond changes hands between two investors. Does this secondary trade mean the bond no longer has an issuer?',answer:'No. The municipality remains the issuer; the resale is a nonissuer transaction.'}},
 {section:1,key:'bd-retail',point:4,
  front:'A broker-dealer has no office in a state and solicits one new resident retail client. With no other exclusion, must it register there?',
  answer:'Yes. One resident retail client is enough; broker-dealers have no five-client de minimis allowance.',
  trap:'A broker-dealer can serve five resident retail clients before registering.',
  explanation:'The adviser five-client rule does not extend to broker-dealers. Separate exclusions can apply to an out-of-state broker-dealer serving only institutions or an eligible visiting existing customer.',
  contrast:{front:'Can a broker-dealer avoid state registration solely because it serves only four resident retail clients?',answer:'No. Four is not a broker-dealer exemption; registration is required unless a separate exclusion applies.'}},
 {section:1,key:'issuer-muni',point:5,
  front:'Under the 1956 Uniform Securities Act, are a city employee selling city bonds and a broker-dealer salesperson selling those bonds both excluded as agents?',
  answer:'No. The issuer representative can be excluded for this municipal sale. The broker-dealer salesperson generally must register as an agent.',
  trap:'The security exemption excludes every salesperson, regardless of whom the person represents.',
  explanation:'The issuer-side exclusion for specified exempt securities differs from the broker-dealer agent test. Identify the employer before applying the exclusion.',
  contrast:{front:'A broker-dealer salesperson sells only municipal bonds. Does the issuer-representative exclusion remove that salesperson’s agent registration duty?',answer:'No. The salesperson represents the broker-dealer, not the municipal issuer.'}},
 {section:1,key:'issuer-security-scope',point:5,
  front:'Does every exempt security automatically qualify its issuer’s representative for the exempt-security agent exclusion?',
  answer:'No. That exclusion covers specified exempt classes, not every exempt security. Other issuer-side exclusions must be analyzed separately.',
  trap:'Any exempt security creates an identical issuer-representative exclusion.',
  explanation:'Section 401(b) names section 402(a)(1), (2), (3), (10), and (11), and separately covers specified exempt transactions and covered-security transactions. The existing-employee route has its own compensation condition.',
  contrast:{front:'An issuer representative sells a security in a transaction exempt under section 402(b). Must the security itself also be exempt for that issuer-side exclusion?',answer:'No. A qualifying exempt transaction is a separate issuer-representative exclusion.'}},
 {section:4,key:'aum-entry-buffer',point:6,
  front:'At $95 million in regulatory assets under management, can a new federal applicant and an existing SEC adviser both use the ordinary AUM eligibility route?',
  answer:'No. The existing adviser may generally remain; the new applicant needs at least $100 million to elect this route.',
  trap:'The $90 million retention threshold also permits a new SEC application.',
  explanation:'Assume no other federal eligibility basis or exemption. Entry may begin at $100 million, generally becomes mandatory at $110 million, and retention generally ends below $90 million.',
  contrast:{front:'An existing SEC adviser reports exactly $90 million in regulatory assets under management. Must it withdraw solely because of that amount?',answer:'No. The ordinary withdrawal trigger is below $90 million, not exactly $90 million.'}},
 {section:7,key:'client-residence',point:7,
  front:'Does the value of a client’s primary residence count toward the federal qualified-client net-worth test?',
  answer:'No. The primary residence is excluded; qualifying net worth must exceed $2.7 million under the current dollar test.',
  trap:'A valuable home automatically supplies the missing qualified-client net worth.',
  explanation:'As of June 29, 2026, the alternative dollar test is at least $1.4 million managed by the adviser. Residence-related debt has special rules, including excess debt and certain recent borrowing.',
  contrast:{front:'A client has $2.5 million outside a debt-free primary home and $900,000 with the adviser. Does adding the home’s $1 million value satisfy either dollar test?',answer:'No. The home is excluded, and neither the $2.7 million net-worth boundary nor the $1.4 million managed-assets minimum is met.'}},
 {section:22,key:'market-cap',point:13,
  front:'Which share count is multiplied by the current share price to calculate market capitalization?',
  answer:'Outstanding shares. Authorized but unissued shares and treasury shares are excluded.',
  trap:'Use all authorized shares or all issued shares even when some are held in treasury.',
  explanation:'For a single common-share class, outstanding shares equal issued shares minus treasury shares. Authorized shares are the maximum permitted issuance, not current investor ownership.',
  contrast:{front:'A company has issued 7 million shares and holds 1 million in treasury. Does market capitalization use all 7 million?',answer:'No. It uses the 6 million outstanding shares.'},
  application:{type:'calculation',front:'A single-class company has 12 million authorized shares, 8 million issued, and 2 million in treasury. At $25 per share, what is its market capitalization?',answer:'$150 million.',explanation:'Outstanding shares = 8 million − 2 million = 6 million. Market capitalization = 6 million × $25 = $150 million. The authorized count is irrelevant.'}},
 {section:21,key:'tips-coupon',point:14,
  front:'For TIPS, does inflation change the coupon rate or the principal used to calculate interest?',
  answer:'The principal changes. The coupon rate is fixed, so interest dollars vary with the inflation-adjusted principal.',
  trap:'TIPS reset their coupon rate whenever inflation changes.',
  explanation:'Treasury Inflation-Protected Securities apply a fixed annual rate to adjusted principal and pay interest semiannually. Deflation can reduce interim principal and interest; the original-principal floor applies at maturity.',
  contrast:{front:'If TIPS principal rises with inflation, does a fixed coupon rate mean the next interest payment must stay the same?',answer:'No. The same rate applied to a higher principal produces a larger dollar payment.'},
  application:{type:'calculation',front:'A Treasury inflation-protected bond has a 2% annual coupon and $1,080 of adjusted principal on the payment date. What is its semiannual interest payment?',answer:'$10.80.',explanation:'$1,080 × 2% ÷ 2 = $10.80. The rate stays 2%; the principal used for the payment is the adjusted amount.'}},
 {section:21,key:'rates-prices',point:15,
  front:'All else equal, what happens to an existing fixed-rate bond’s price when market yields rise?',
  answer:'Its price falls. When market yields fall, its price rises.',
  trap:'A fixed coupon means the bond’s market price cannot change.',
  explanation:'An older fixed payment becomes less attractive when new bonds offer higher yields. Its price must fall to offer a competitive yield; the contractual coupon itself stays fixed.',
  contrast:{front:'Market yields fall after a fixed-rate bond is issued. Does its coupon rate fall with them?',answer:'No. The coupon rate stays fixed; the bond’s market price generally rises.'}},
 {section:21,key:'duration-long-low',point:16,
  front:'For otherwise comparable option-free fixed-rate bonds, which combination generally produces higher duration?',
  answer:'Longer maturity and a lower coupon. Higher duration means greater sensitivity to yield changes.',
  trap:'A higher coupon always makes a bond more sensitive to changing rates.',
  explanation:'Later cash flows carry more interest-rate sensitivity. Compare otherwise similar bonds, including yield; embedded options can change the usual relationship.',
  memoryHook:'Long and low: long maturity, low coupon, high duration.',
  contrast:{front:'Two option-free bonds have the same maturity and yield. Does the one with the higher coupon have higher duration?',answer:'No. The lower-coupon bond has higher duration because more of its value arrives later.'}},
 {section:21,key:'preferred-priority',point:17,
  front:'In liquidation, where does preferred stock rank relative to common stock and creditors?',
  answer:'Ahead of common stock, but behind all creditors, including unsecured and subordinated creditors.',
  trap:'Preferred stock outranks unsecured debt because it is called preferred.',
  explanation:'Preferred is an equity claim. Its preference is over common equity, not over the company’s debt obligations.',
  contrast:{front:'A company owes subordinated unsecured debt and has preferred shares outstanding. Which claim ranks ahead in liquidation?',answer:'The subordinated debt. Even subordinated creditors rank ahead of preferred shareholders.'}},
 {section:19,key:'protect-long',point:18,
  front:'Which purchased option protects a long stock position against a price decline?',
  answer:'A long put on the same stock. It provides the right to sell at the strike price during the option’s term.',
  trap:'Buy a call to protect shares already owned against falling prices.',
  explanation:'Match the option’s underlying, share coverage, and expiry to the exposure. A protective put preserves stock upside, less the premium; it does not promise a profit.',
  contrast:{front:'An investor owns stock and wants a downside floor while retaining uncapped upside. Is selling a covered call equivalent to buying a put?',answer:'No. A long put creates the floor; a covered call supplies premium income but caps upside and leaves substantial downside.'},
  application:{type:'calculation',front:'You buy 100 shares at $48 and one put covering 100 shares with a $45 strike for $2 per share. What is the maximum loss at expiration, ignoring fees and dividends?',answer:'$500.',explanation:'Total cost = 100 × ($48 + $2) = $5,000. The put provides a $4,500 sale floor. Maximum loss = $5,000 − $4,500 = $500.'}},
 {section:19,key:'protect-short',point:18,
  front:'Which purchased option protects a short stock position against a price rise?',
  answer:'A long call on the same stock. It provides the right to buy shares at the strike price to cover the short.',
  trap:'Buy a put to protect a short seller against rising stock prices.',
  explanation:'The short seller needs a purchase-price ceiling. A matching call supplies it during the option’s term; the premium is part of the hedge cost.',
  contrast:{front:'A short seller fears a sharp rally. Would buying a put cap the cost of buying back the shares?',answer:'No. A long call supplies that purchase-price ceiling; a put benefits from a decline.'},
  application:{type:'calculation',front:'You short 100 shares at $60 and buy one call covering them with a $65 strike for $3 per share. What is the maximum loss at expiration, ignoring fees, dividends, and borrowing costs?',answer:'$800.',explanation:'Maximum share loss = ($65 − $60) × 100 = $500. Add the $300 call premium: $800.'}},
 {section:19,key:'futures-hedge',point:19,
  front:'For an asset owner, how does a matched short futures hedge differ from buying a protective put?',
  answer:'Futures offset both favorable and unfavorable price moves. A put limits downside while preserving upside, for a premium.',
  trap:'A futures hedge removes losses but leaves all favorable price gains untouched.',
  explanation:'With an effective hedge, a futures gain offsets a cash-market loss and a futures loss offsets a cash-market gain. Actual hedges can have basis risk; a perfect price lock is a simplifying assumption.',
  contrast:{front:'An asset owner has a perfectly matched short futures hedge and the asset price rises. Does the owner retain that entire rise as an added net gain?',answer:'No. The asset’s gain is offset by a loss on the short futures hedge.'}},
 {section:19,key:'hedge-direction',point:19,
  front:'Which futures direction hedges a producer’s falling sale price, and which hedges a buyer’s rising purchase price?',
  answer:'The producer sells futures; the future buyer buys futures.',
  trap:'Both a producer and a future buyer should sell futures whenever prices are uncertain.',
  explanation:'Choose a futures position that gains when the underlying business exposure loses. A producer fears falling prices; a buyer fears rising prices.',
  contrast:{front:'A manufacturer must purchase a commodity in three months and fears higher prices. Should it sell futures as its directional hedge?',answer:'No. It should buy futures; a long futures position gains when that commodity’s futures price rises.'}},
 {section:21,key:'etn-credit',point:20,
  front:'What issuer risk does an ETN add to its linked investment exposure?',
  answer:'Unsecured issuer credit risk. Payment depends on the issuer’s ability to meet its debt obligation.',
  trap:'An ETN investor owns a separate fund portfolio backing the note.',
  explanation:'An exchange-traded note is debt, not an ownership interest in a fund portfolio. A rising tracked index cannot eliminate the issuer’s default risk.',
  contrast:{front:'An ETN’s tracked index rises, but the issuer defaults. Is the investor guaranteed the positive index return?',answer:'No. The note is an unsecured promise of the issuer; default can cause a loss despite index gains.'}},
 {section:18,key:'traded-fund-price',point:21,
  front:'How do retail prices differ between mutual funds, exchange-traded funds (ETFs), and closed-end funds?',
  answer:'Mutual funds use the next computed NAV, with applicable charges. Exchange-traded closed-end funds and ETFs trade at market prices.',
  trap:'Every fund investor always trades at the last published NAV.',
  explanation:'Market prices can be above or below net asset value. The comparison concerns conventional open-end mutual funds versus exchange-traded shares, not an ETF’s creation-unit process.',
  contrast:{front:'An ETF has a $40 NAV but your exchange purchase executes at $40.30. Before fees, what do you pay per share?',answer:'$40.30. The executed market price controls; this trade is at a premium to NAV.'}},
 {section:18,key:'etf-structure',point:21,
  front:'If an ETF is legally an open-end investment company, must an ordinary retail exchange trade receive the next NAV?',
  answer:'No. Its retail shares still trade at market prices. The open-end mutual-fund pricing shortcut does not describe ETF exchange trades.',
  trap:'An open-end legal structure makes all retail trades use mutual-fund forward pricing.',
  explanation:'Many ETFs have an open-end investment-company structure; some are unit investment trusts. Legal structure and the retail trading mechanism are separate distinctions.',
  contrast:{front:'Does an ETF’s daily NAV calculation guarantee that its exchange price equals NAV throughout the day?',answer:'No. The market price can differ from NAV, even though arbitrage often keeps them close.'}},
 {section:18,key:'etf-active',point:22,
  front:'Does ETF mean the fund must follow a passive index strategy?',
  answer:'No. ETFs can be actively managed or passively track an index.',
  trap:'Exchange trading proves that a fund is passive.',
  explanation:'An exchange-traded fund describes a product and trading structure. Read the investment strategy to learn whether the manager tracks an index or selects investments actively.',
  contrast:{front:'An ETF manager selects holdings without trying to track an index. Does active management disqualify the fund from being an ETF?',answer:'No. An actively managed ETF is permitted.'}},
 {section:15,key:'gift-dual',point:23,
  front:'A gift’s fair market value is below the donor’s adjusted basis. Which basis applies to a later gain and which to a later loss?',
  answer:'Use the donor’s basis for gain and the lower gift-date value for loss. A sale between them produces neither gain nor loss.',
  trap:'The lower gift-date value replaces the donor’s basis for every possible sale.',
  explanation:'Assume no later basis adjustments. First compare proceeds with both figures; selecting just one basis can create a gain or loss that the dual-basis rule does not permit.',
  contrast:{front:'Gift-date value is $8,000 and donor basis is $12,000. If the recipient sells for $15,000, is the taxable gain $7,000?',answer:'No. The gain is $3,000: $15,000 minus the donor’s $12,000 basis.'}},
 {section:13,key:'conversion-clock',point:24,
  front:'Is the Roth earnings five-year clock the same as the early-withdrawal clock for each taxable conversion?',
  answer:'No. Each conversion has a separate five-tax-year clock for potential early-distribution tax; qualified earnings use the first-Roth-contribution clock.',
  trap:'Satisfying the Roth earnings clock automatically removes every conversion-related early-distribution tax.',
  explanation:'Roth ordering uses regular contributions first, then conversions oldest first, then earnings. For a conversion, the taxable portion comes before its nontaxable portion. Early withdrawal of taxable converted amounts can trigger the 10% additional tax unless an exception applies.',
  contrast:{front:'An owner under 59½ has no regular contributions left and withdraws a taxable conversion after two tax years. Does a ten-year-old Roth account alone prevent the conversion-related 10% additional tax?',answer:'No. That conversion has its own five-year clock; another exception would be needed.'}},
 {section:13,key:'roth-clock',point:25,
  front:'When does the five-tax-year clock for qualified Roth IRA earnings begin?',
  answer:'January 1 of the first tax year for which a contribution was made to any Roth IRA for the owner.',
  trap:'Count five years from the exact deposit date or restart the clock for each Roth account.',
  explanation:'A conversion can establish the first Roth contribution year. The earnings test also needs age 59½, death, disability, or a qualifying first-home distribution, subject to its $10,000 lifetime limit.',
  contrast:{front:'A first Roth contribution is made in April 2027 for tax year 2026. Does the earnings clock begin in April 2027?',answer:'No. It begins January 1, 2026, the tax year of the contribution.'},
  application:{type:'application',front:'An owner first contributed to a Roth for tax year 2022 and turns 60 in 2026. Is a 2026 earnings withdrawal qualified solely from those facts?',answer:'No. The five-tax-year period ends after 2026; the earliest qualifying date is January 1, 2027.',explanation:'The five tax years are 2022, 2023, 2024, 2025, and 2026. Age 59½ is satisfied, but the time requirement is not yet complete.'}},
 {section:9,key:'time-price-expiry',point:28,
  front:'Under FINRA Rule 3260, how long does ordinary oral time-and-price authority for a definite security and amount last?',
  answer:'Through the end of that business day. Extending it generally requires the customer’s specific written, signed, and dated instruction.',
  trap:'Time-and-price authority automatically remains open indefinitely.',
  explanation:'The customer fixes the security, buy/sell action, and amount; the agent chooses execution time or price. Rule 3260 has a limited institutional not-held-order exception to the daily limit.',
  contrast:{front:'A retail customer orally authorizes timing for today’s purchase of 50 specified shares. With no written extension, can the agent carry that authority into tomorrow?',answer:'No. The ordinary oral time-and-price authority expires at the end of today’s business day.'}},
 {section:9,key:'durable-authority',point:29,
  front:'Does a durable power of attorney survive the principal’s incapacity, death, or both?',
  answer:'Incapacity, not death. Authority under the power of attorney ends when the principal dies.',
  trap:'Durable means the agent can continue acting after death until the estate is settled.',
  explanation:'The document and applicable state law still limit the agent’s powers. Being an attorney-in-fact does not automatically appoint the person as executor or estate representative.',
  contrast:{front:'A client dies while an agent holds durable financial authority. Can the agent place a new trade solely under that power of attorney?',answer:'No. The power ended at death; estate authority must be established separately.'}},
 {section:9,key:'pay-play-status',point:30,
  front:'As of September 13, 2026, has the SEC’s proposed pay-to-play rescission taken effect?',
  answer:'No. It is a proposal, not an effective repeal. The existing pay-to-play rule still applies.',
  trap:'The September 3 proposal immediately removed the rule’s restrictions.',
  explanation:'The SEC proposed rescinding adviser Rule 206(4)-5 on September 3, 2026. A proposal and comment period do not change an effective rule; separate state and other pay-to-play provisions also need independent analysis.',
  contrast:{front:'As of September 13, 2026, can an adviser ignore the existing pay-to-play rule solely because the SEC proposed rescinding it?',answer:'No. The proposal has not repealed the rule or its applicable two-year compensation restriction.'}},
];
