/** User-requested review scope, September 13, 2026. Rule IDs survive wording edits. */
export const reviewChecklist = [
 { number:1, title:'Registration is not approval', rules:['s65-06-registration-approval'] },
 { number:2, title:'Exempt security versus exempt transaction', rules:['s65-06-exemption-scope','s65-06-security-exempt','s65-06-transaction-exempt','s65-06-fraud'] },
 { number:3, title:'A municipal security still has an issuer', rules:['s65-06-municipal-issuer'] },
 { number:4, title:'No five-retail-client allowance for broker-dealers', rules:['s65-01-bd-retail','s65-01-bd-office','s65-01-bd-institution','s65-01-bd-visitor'] },
 { number:5, title:'Issuer representatives versus broker-dealer agents', rules:['s65-01-issuer-muni','s65-01-issuer-security-scope','s65-01-issuer-employee','s65-01-exempt-agent'] },
 { number:6, title:'Adviser registration: $100M / $110M / below $90M', rules:['s65-04-aum-buffer','s65-04-aum-must','s65-04-aum-exit','s65-04-aum-entry-buffer','s65-04-withdraw-clock'] },
 { number:7, title:'Qualified client: at least $1.4M managed or over $2.7M qualifying net worth', rules:['s65-07-client-managed','s65-07-client-worth','s65-07-client-version','s65-07-client-residence'] },
 { number:8, title:'Rule 144 holding periods and continuing affiliate conditions', rules:['s65-10-affiliate-reporting','s65-10-affiliate-nonreporting','s65-10-affiliate-conditions','s65-10-unrestricted-clock','s65-10-lookback','s65-10-nonaffiliate-reporting'] },
 { number:9, title:'Material but nonpervasive audit problem: qualified', rules:['s65-24-qualified'] },
 { number:10, title:'Pervasive misstatement versus missing audit evidence', rules:['s65-24-adverse','s65-24-disclaimer'] },
 { number:11, title:'Quick assets exclude inventory and prepaids', rules:['s65-22-quick-ratio'] },
 { number:12, title:'Dividend declaration versus payment', rules:['s65-21-dividend-declare','s65-21-dividend-pay','s65-21-dividend-current'] },
 { number:13, title:'Market capitalization uses outstanding shares', rules:['s65-22-market-cap'] },
 { number:14, title:'TIPS: fixed coupon rate, variable interest dollars', rules:['s65-21-tips-coupon'] },
 { number:15, title:'Interest rates and fixed-rate bond prices move inversely', rules:['s65-21-rates-prices'] },
 { number:16, title:'Long maturity and low coupon increase duration', rules:['s65-21-duration-long-low'] },
 { number:17, title:'Preferred stock ranks between creditors and common stock', rules:['s65-21-preferred-priority'] },
 { number:18, title:'Long stock plus long put; short stock plus long call', rules:['s65-19-protect-long','s65-19-protect-short'] },
 { number:19, title:'Futures lock price exposure; puts retain upside for a premium', rules:['s65-19-futures-hedge','s65-19-hedge-direction'] },
 { number:20, title:'ETNs carry unsecured issuer credit risk', rules:['s65-21-etn-credit'] },
 { number:21, title:'Mutual-fund next NAV versus exchange-traded market prices', rules:['s65-18-forward-price','s65-18-traded-fund-price','s65-18-etf-structure'] },
 { number:22, title:'ETFs can be active or passive', rules:['s65-18-etf-active'] },
 { number:23, title:'Gift dual basis: gain, loss, and the middle band', rules:['s65-15-gift-dual','s65-15-gift-gain','s65-15-gift-loss','s65-15-gift-middle'] },
 { number:24, title:'Roth ordering: contributions, conversions, earnings', rules:['s65-13-roth-order','s65-13-roth-contributions','s65-13-conversion-clock'] },
 { number:25, title:'Qualified Roth earnings require five tax years and a qualifying event', rules:['s65-13-roth-earnings','s65-13-roth-clock'] },
 { number:26, title:'Passive losses generally do not offset salary', rules:['s65-16-passive-offset','s65-16-loss-gates','s65-16-release-loss'] },
 { number:27, title:'JTWROS survivorship versus tenancy-in-common estate transfer', rules:['s65-15-jtwros','s65-15-tic','s65-15-jtwros-retest'] },
 { number:28, title:'Time and price alone are not full discretion', rules:['s65-09-time-price','s65-09-agent-written','s65-09-time-price-expiry'] },
 { number:29, title:'Durable authority survives incapacity, not death', rules:['s65-09-durable-authority'] },
 { number:30, title:'Pay-to-play rescission is proposed, not effective', rules:['s65-09-pay-play-status'] },
] as const;
