/** Original authoring ledger. IDs identify concepts, never wording or row position.
 * Each row: key | literal source locator | original prompt | concise rule/answer | false neighboring-rule claim.
 * Source locators are internal only; the browser receives the source heading, not authoring notes.
 */
export const ruleText: Record<number,string> = {
1: `state-office|State-registered IA or its IAR|What state connection requires a state adviser or its representative to register even with five or fewer retail clients?|A place of business in the state. The five-client allowance applies only when there is no local office.|An office is allowed without registration until client six.
state-sixth|State-registered IA or its IAR|A state adviser has no office in a state. What retail-client count triggers registration?|The sixth noninstitutional client during the preceding 12 months triggers registration.|Only clients served in the current calendar year count.
federal-notice|Federal covered IA firm|An SEC-registered advisory firm has no local office. When does its retail client count generally trigger a state filing?|At the sixth noninstitutional resident client in 12 months, the firm generally notice-files; it stays SEC-registered.|The sixth client makes the federal firm a state-registered adviser.
federal-office|in-state place of business|What filing does an in-state office generally trigger for a federal covered advisory firm?|A state notice filing, rather than state adviser registration.|An SEC registration eliminates every state filing.
federal-iar|IAR of a federal covered IA|What state connection determines registration for a representative of a federal covered adviser?|The representative registers where the representative has a place of business; client count alone is insufficient.|The representative must register in every state with six retail clients.
bd-office|Broker-dealer |Can a broker-dealer with an office use a five-retail-client allowance?|No. A broker-dealer has no five-client allowance and must register where it has an office.|Broker-dealers share the state adviser's de minimis allowance.
bd-institution|dealing exclusively with|When may an out-of-state broker-dealer with no local office qualify for an exclusion based on counterparties?|When its business there is exclusively with issuers, other broker-dealers, or institutions.|Serving five local retail clients is an equivalent exclusion.
bd-visitor|temporarily visiting|What distinguishes the visiting-customer broker-dealer exclusion from a new local retail relationship?|The customer already lives outside the state and is only temporarily visiting; the broker-dealer has no local office.|Any retail customer qualifies if the visit to the office is brief.
agent-limit|Agent |Does an agent have the adviser's five-client allowance?|No. Someone meeting the agent definition who transacts business in the state must register.|An agent can serve five retail customers without registration.
institutions|Institutional clients do not count|Which clients are omitted from the state adviser five-client count?|Institutional clients are excluded from the noninstitutional-client count.|A large number of institutions alone consumes the five-client allowance.
firm-individual|Separate the firm|Why can a federal firm owe a notice filing while its representative owes no registration in that state?|The firm's retail count can trigger notice filing; its representative's test is the representative's office location.|Firm and representative always have identical state filing duties.
exempt-agent|BD salesperson generally|Does selling an exempt security normally remove a broker-dealer salesperson's agent status?|No. The salesperson generally remains an agent despite the security exemption.|An exempt bond automatically exempts its salesperson.
issuer-employee|Issuer employee exception|What two conditions support the narrow issuer-employee agent exclusion in the cram sheet?|Sales only to existing employees, partners, or directors, with no sales commission.|No commission alone exempts every issuer salesperson.
late-incidental|LATE:|When can a lawyer, accountant, teacher, or engineer be excluded from the adviser definition?|Advice must be solely incidental to the profession and receive no special compensation.|Professional credentials alone establish the exclusion.
late-holding-out|Holding out as an adviser|What happens to the incidental-professional exclusion when the professional holds out as an adviser?|Holding out as an adviser defeats that exclusion.|Incidental advice remains excluded even when advertised as advisory services.
government-only|government securities|Must a firm advising solely on qualifying U.S. government securities register as a state adviser?|No. It is federally excluded from the adviser definition and treated as federal covered for state registration, even with a local office.|An office necessarily makes this excluded firm a state adviser.
individual-capacity|person's capacity|An individual represents an advisory firm and crosses a state client threshold. Which capacity is registered?|The individual registers as an investment adviser representative, not as a separate adviser firm.|Every individual giving advice registers as an adviser firm.
each-state|Registration in State X|Does registration in one state authorize business in every other state?|No. Assess the registration obligation separately in each state.|One state registration is a national professional license.
truthful-ad|Truthful, nonmisleading|Is general advertising by an adviser inherently prohibited?|No. Truthful, nonmisleading general advertising is not automatically prohibited.|All general adviser advertising is forbidden.
adviser-elements|three elements|What three elements form the federal investment-adviser definition?|Securities advice, being in the business of providing it, and direct or indirect compensation.|Only a separately itemized advisory fee can satisfy compensation.
business-regular|regular activity is enough|Must advisory activity be a person's principal business to meet the federal business element?|No. Regular advisory activity can be enough even when another activity is the principal business.|Advice counts only when it is the main source of business.
bond-authority|Administrator may require a bond|What authority does a state Administrator have when a registrant has discretion or applicable custody?|The Administrator may require a bond; bonding is a separate issue from registration.|Meeting a registration requirement resolves every bonding obligation.`,
2: `state-employment|firm** notifies|Who gives the Administrator employment notice for a state adviser's representative?|The state-registered advisory firm gives the notice.|The representative always personally files the employment notice.
federal-employment|IAR** notifies|Who gives employment notice for a federal covered adviser's representative?|The representative gives the Administrator the notice.|Federal covered status transfers this duty to the firm.
agent-departure|Agent leaves|Who must notify the Administrator when an agent leaves a broker-dealer?|Both the agent and broker-dealer notify promptly, whether departure is voluntary or for cause.|Only a firing creates the agent's notification duty.
ce-split|12 credits annually|How many annual continuing-education credits must an investment adviser representative earn in an adopting jurisdiction?|12 credits: 6 in Products and Practice and 6 in Ethics and Professional Responsibility.|Any mix of 12 credits satisfies both categories.
ce-carry|do not carry forward|Can surplus continuing-education credits cover the following year?|No. Excess credits expire, and earlier deficiencies still must be completed.|Surplus credits erase a previous-year deficiency.`,
3: `adv-one|ADV Part 1|What is the purpose of Form ADV Part 1?|The regulatory filing describes ownership, business, activities, assets under management, and disciplinary matters.|Part 1 is the client-facing personal supplement.
adv-two-a|firm brochure|Which Form ADV document describes the advisory firm to clients?|Part 2A is the firm's brochure.|Part 2B is the firm brochure.
adv-two-b|person/supervised-person supplement|Which Form ADV document covers the supervised individual?|Part 2B is the individual's brochure supplement.|Part 2A replaces the supervised-person supplement.
assignment-contract|Client consent before|Which document must require client consent before an advisory contract is assigned?|The advisory contract. Form ADV background disclosures do not replace that consent requirement.|Disclosure in Form ADV alone substitutes for contractual assignment consent.
act-1933|Securities Act of 1933|Which federal act chiefly regulates new public offerings and their registration disclosures?|The Securities Act of 1933.|The 1934 Act created the primary new-issue registration framework.
act-1934|Securities Exchange Act of 1934|Which act regulates secondary markets and created the SEC?|The Securities Exchange Act of 1934.|The 1933 Act created the SEC and regulates exchanges.
state-security-term|registration statement:|How long is a state securities registration statement generally effective?|One year, with a possible extension for an underwriter's unsold allotment.|Every securities registration expires on December 31 regardless of effectiveness.
coordination-clocks|Registration by coordination:|Before state registration by coordination becomes effective, how long must the filing and final pricing be on file?|The filing: at least 10 days. Final pricing: at least 2 full business days. The Administrator may shorten these periods.|Both clocks use business days and start with final pricing.
federal-civil|Federal Securities Act civil liability|In the tested federal Securities Act civil-action comparison, what are the discovery and outside filing deadlines?|The earlier of one year after discovery or three years after the action.|The discovery date can extend the outside three-year limit.
state-civil|Uniform Securities Act|What is the Uniform Securities Act civil-action deadline comparison?|The earlier of two years after discovery or three years after the action.|The state discovery period is the federal one-year period.
civil-scope|not a universal deadline|Does the federal one-year/three-year comparison govern every federal securities claim?|No. It is the specified Securities Act exam comparison, not a universal deadline.|All federal securities claims have the same limitation period.
bankruptcy-trustee|Trustee in bankruptcy|Which trustee is specifically identified in the fiduciary transaction exemption?|A trustee in bankruptcy; an ordinary private trustee is not automatically covered.|Any person using the title trustee qualifies.
underlying-offer|right, warrant, or convertible|Why is issuing a right, warrant, or convertible treated as an offer of the underlying security?|The holder must pay value to acquire the underlying security.|Only delivery of the underlying shares can constitute an offer.
non-offers|stock dividend, bona fide loan|Name three events that are not treated as offers in the same way as a paid right or warrant?|A stock dividend, a bona fide loan, and a statutory merger.|Every event involving stock creates the same offer consequence.
fundamental-policy|fundamental investment-policy change|Whose approval generally authorizes a registered fund's fundamental investment-policy change?|A majority of its outstanding voting securities.|The portfolio manager can unilaterally change a fundamental policy.`,
4: `tested-act|1956|Which Uniform Securities Act version is the exam framework?|The 1956 Act as amended by NASAA, not the 2002 Act.|The newest model Act automatically controls the exam.
state-effective|noon on the 30th|How long after filing does state professional registration generally become effective?|At noon on the 30th day after filing.|It is effective at midnight on the filing date.
state-expiry|expires **December 31|When does state professional registration expire unless renewed?|December 31.|It always lasts exactly twelve months after filing.
sec-application|45 days|How long does the SEC have to grant an adviser application or begin denial proceedings?|45 days.|An application automatically becomes approved after 30 days.
adv-update|90 days|What is the deadline for the annual Form ADV updating amendment?|Within 90 days after the fiscal year ends.|The annual brochure's 120-day window also applies to ADV.
brochure-annual|120 days|When is the annual brochure or material-change summary generally delivered?|Within 120 days after fiscal year-end.|The client's anniversary date starts the annual filing clock.
brochure-initial|48 hours before|What are the two permitted timings for the tested initial state brochure delivery?|At least 48 hours before contracting, or at signing with five business days to cancel without penalty.|Delivery at signing never requires a cancellation opportunity.
prompt-amendment|Amend **promptly|How should a materially inaccurate filing be corrected when its item requires amendment?|Amend it promptly instead of waiting for the annual update.|Every correction can wait until fiscal year-end.
records-ordinary|5 years|How long are ordinary state adviser records generally retained?|Five years from fiscal year-end of the last entry, with the first two generally at the principal office.|Five years runs from the record's original creation in every case.
records-formation|3 years after termination|How long are adviser formation and governance records kept at the principal office?|Until three years after the enterprise terminates.|The ordinary five-year rule permits destruction during the firm's life.
aum-below|Below **$100M|Where does an ordinary adviser below $100 million generally register?|With the state, unless another federal registration basis applies.|No adviser below $100 million can ever register federally.
aum-buffer|$100M to under $110M|What choice is available at $100 million to below $110 million of regulatory AUM?|An ordinary adviser in this buffer may elect SEC registration.|SEC registration becomes compulsory at exactly $100 million.
aum-must|$110M or more|At what ordinary regulatory AUM threshold does federal registration generally become mandatory?|$110 million or more.|The mandatory threshold is $100 million.
aum-exit|below **$90M|How low can an already SEC-registered ordinary adviser generally go before losing the AUM basis?|It may remain until regulatory AUM falls below $90 million.|It must withdraw as soon as AUM drops below $100 million.
registered-fund|registered investment company =|What special federal registration basis applies to an adviser to a registered investment company?|It is federal covered regardless of the ordinary AUM thresholds.|A small registered-fund adviser must use state registration.
withdraw-clock|180 days|After an adviser reports loss of SEC eligibility in its annual update, what is its withdrawal deadline?|Within 180 days of fiscal year-end, with state registration arranged for the transition.|The 180 days starts whenever the annual update is actually filed.`,
5: `termination-prompt|Agent terminates|What timing controls an agent's termination notice under the tested Uniform Act rule?|Agent and firm or issuer notify promptly.|A generic 30-day Form U5 deadline replaces the prompt-notice duty.
prepay-state|State IA prepaid fee|What prepaid-fee combination triggers the tested state adviser's financial reporting requirement?|More than $500 per client paid at least six months in advance.|Exactly $500 paid five months ahead meets both tests.
prepay-federal|Federal covered IA prepaid fee|What prepaid-fee combination triggers the federal adviser's tested brochure balance-sheet requirement?|More than $1,200 per client paid at least six months in advance.|The state $500 threshold also controls federal covered firms.
prepay-boundary|Exactly $500|How are the dollar and time boundaries treated in the prepaid-fee tests?|The dollar amount must be exceeded; exactly six months meets the time condition.|Both the dollar amount and six months must be strictly exceeded.
prepay-consequence|do **not** prohibit|Does crossing a prepaid-fee threshold prohibit collecting the fee?|No. It triggers the applicable financial reporting and disclosure obligations.|Crossing the threshold makes the fee illegal or changes registration status.
fee-custody|Fee-deduction authority|Is authority to deduct advisory fees custody?|Yes, though safeguards may support an exception from the annual surprise examination.|An examination exception means the adviser has no custody.
bill-custody|Bill-paying/check-writing|Does bill-paying authority qualify for the fee-deduction-only surprise-exam exception?|No. It is custody beyond fee deduction and that specific exception does not apply.|Client permission to pay bills preserves the fee-only exception.
consent-custody|Client consent does not|Can client consent remove custody status or override a custody prohibition?|No. Consent does not erase the classification or supersede the rule.|A signed consent form removes all custody obligations.
custody-worth|$35,000 net worth|What is the tested minimum net worth for a state adviser with custody?|$35,000, subject to applicable exceptions.|The $35,000 figure is a universal fixed surety-bond amount.
discretion-worth|$10,000 net worth|What is the tested minimum net worth for a state adviser with discretion but no custody?|$10,000.|Discretion without custody always requires the custody minimum.
prepay-worth|Positive net worth|What minimum net-worth condition applies when a state adviser receives over $500 per client at least six months in advance?|Positive net worth.|The prepayment trigger always requires $35,000 net worth.
deficiency-bond|rounded up to the next|How is the tested surety bond calculated for a net-worth deficiency?|Use the deficiency below the applicable minimum, rounded up to a $5,000 increment.|The bond always equals the full minimum net worth.
general-bond|general bonding authority|Are the custody and discretion net-worth minimums universal fixed bond amounts?|No. Separate general bonding authority can take client count and AUM into account.|Every adviser with custody posts an identical $35,000 bond.
enforcement|cease-and-desist order|Who issues a cease-and-desist order, and who issues an injunction in state securities enforcement?|The Administrator issues the cease-and-desist order; a court issues the injunction.|The Administrator personally issues a court injunction or makes an arrest.
hearing|final suspension ordinarily|What process ordinarily precedes a final registration suspension?|Notice and an opportunity for a hearing.|Every final suspension can bypass notice and hearing.`,
6: `security-exempt|Exempt security |What does an exempt-security classification remove?|State registration of the security itself.|It also automatically removes the salesperson's registration duty.
transaction-exempt|Exempt transaction |What is the scope of a transaction exemption?|It exempts that particular transaction from registration requirements.|It permanently exempts every future sale of the security.
covered-security|Federal covered security |What does federal-covered security status preempt?|Full state securities registration, although notice filings and fees may remain.|Federal covered securities eliminate all state notice fees.
fraud|Antifraud rules |Do antifraud requirements apply to exempt persons, securities, and transactions?|Yes. Exempt status does not eliminate antifraud requirements.|An exempt transaction is outside antifraud law.
person-separate|person registration|How should an agent's or broker-dealer's registration be evaluated when a security is exempt?|Separately from the security or transaction exemption.|A security's exemption automatically travels to every person selling it.
placement-count|10 noninstitutional offerees|How many noninstitutional offerees may a state private placement approach under the tested exemption?|No more than ten in that state during 12 months. Count offerees, not just buyers; institutions do not count.|Count only the investors who actually buy.
placement-investment|purchase for investment|What purchase intent is required of noninstitutional buyers in the tested state private placement?|They buy for investment.|A prearranged immediate resale meets the investment-intent condition.
placement-pay|no commission for soliciting|Under the tested state private-placement exemption, may commissions be paid for soliciting noninstitutional buyers?|No. Commissions for soliciting those buyers are prohibited.|A commission is allowed because the offering is private.
placement-federal|Do not import|Can state private-placement limits be substituted for federal Regulation D conditions?|No. They are different legal tests.|The state's ten-offeree cap defines every Regulation D safe harbor.
notification|Notification |Which state registration method is associated with an established, seasoned issuer?|Notification.|Notification is the method defined by a simultaneous federal offering filing.
coordination|Coordination |Which state registration method accompanies a federal Securities Act registration for the same offering?|Coordination.|A separate state qualification order always substitutes for the federal filing.
qualification|Qualification |Which state securities registration method can be used for any security and becomes effective by Administrator order?|Qualification.|Qualification becomes effective automatically at the ordinary professional registration time.`,
7: `accredited|Accredited investor |Which investor label primarily addresses Regulation D private-offering eligibility?|Accredited investor.|Accredited status by itself answers the performance-fee test.
qualified-client|Qualified client |Which investor label chiefly addresses performance-fee eligibility?|Qualified client; it also matters to the non-venture-capital private-fund adviser exemption in the sheet.|Qualified purchaser and qualified client always mean the same thing.
qualified-purchaser|Qualified purchaser |Which investor standard is associated with a section 3(c)(7) private fund?|Qualified purchaser.|Every accredited investor automatically meets the purchaser standard.
client-managed|$1.4M managed|What assets managed by the adviser satisfy the federal qualified-client dollar test effective June 29, 2026?|At least $1.4 million managed by that adviser.|The client must have more than $1.4 million, so equality fails.
client-worth|over $2.7M|Under the 2026 federal qualified-client net-worth test, what boundary applies?|Net worth over $2.7 million, generally excluding the primary residence.|Exactly $2.7 million satisfies the net-worth test.
client-version|Effective June 29, 2026|What are the federal qualified-client dollar thresholds effective June 29, 2026?|At least $1.4 million managed by the adviser, or net worth over $2.7 million, generally excluding the primary residence.|The older $1.1 million and $2.2 million figures remain current.`,
8: `fund-exclusion|Investment Company Act exclusion|Why is a qualifying private fund not a registered investment company?|It relies on an exclusion from the Investment Company Act definition.|Every pooled investment vehicle must register as an investment company.
fund-one|no more than 100|What is the traditional section 3(c)(1) beneficial-owner limit?|No more than 100 beneficial owners.|The standard permits 100 owners plus unlimited additional retail owners.
fund-seven|investors must be qualified purchasers|Which investor qualification distinguishes a 3(c)(7) private fund from the traditional 3(c)(1) owner-count test?|Qualified-purchaser status. Section 3(c)(7) does not use the traditional 100-owner ceiling.|The 100-owner ceiling governs both exclusions.
adviser-private|less than $150M|What asset test may support the private-fund-adviser exemption for a solely private-fund adviser?|Less than $150 million in total U.S. private-fund assets under management.|Each individual fund gets its own $150 million exemption allowance.
adviser-exact|Exactly $150M|Does exactly $150 million of U.S. private-fund AUM meet the less-than-$150-million exemption?|No. The threshold is strictly less than $150 million.|Exactly $150 million still qualifies.
reporting-adviser|still files portions|Does an exempt reporting adviser avoid all Form ADV filing?|No. It still files the required portions of Form ADV.|Exempt from registration means exempt from all reporting.`,
9: `time-price|time-and-price authority|When is a broker-dealer agent's authority limited to time and price rather than full discretion?|The customer has fixed the security, buy/sell action, and amount.|Choosing the security can be treated as time-and-price discretion.
agent-written|broader discretion generally|Before a broker-dealer agent exercises discretion beyond time and price, what client authorization is generally required?|Prior written authorization.|The agent can borrow the adviser's ten-business-day accommodation.
adviser-written|10 business days|Under the tested adviser oral-discretion accommodation, when must written authority follow?|Within ten business days after the first discretionary transaction.|Ten calendar days applies equally to advisers and broker-dealer agents.
minority-partner|Minority partnership|What does a minority partnership membership change generally require?|Notice to clients within a reasonable time.|Every minority membership change necessarily requires assignment consent.
control-consent|transfer of control/assignment|What client action is required before an advisory assignment or control transfer?|Obtain client consent.|A notice after the transfer always suffices.
contract-terms|contract states its term|Which basic terms belong in an advisory contract?|Its term, fee and termination-refund treatment, and assignment restriction.|Only the fee rate matters in the contract.
renew-writing|Renewal or extension|How must an advisory contract's renewal or extension be documented?|In writing.|An oral renewal always satisfies the requirement.
pledge-assignment|pledge of client contracts|How is a pledge of client contracts classified?|As an assignment.|A pledge avoids assignment requirements because no outright sale occurs.
oral-offer|Ordinary oral offer|Is an ordinary oral securities offer a prospectus?|No. An ordinary oral offer is not a prospectus.|Every oral offer is a prospectus.
media-prospectus|Written, radio, or television|Can a radio or television securities offering communication be a prospectus?|Yes, as can a written offering communication.|Only printed material can be a prospectus.
tombstone|properly limited tombstone|Is a properly limited tombstone offering notice treated as a prospectus?|No. A properly limited tombstone is an excluded notice.|Any advertisement called a tombstone qualifies regardless of contents.
cooling-off|Cooling-off period:|What communications may occur during the cooling-off period?|Oral offers, a preliminary prospectus, and permitted tombstones.|Nothing may be communicated before effectiveness.
no-completion|no completed sale, payment|What transaction steps must wait until registration is effective?|Completed sale, payment, confirmation, and securities delivery.|A preliminary prospectus permits immediate payment and completion.
principal|Principal trade:|What must an adviser do before completing a principal transaction with its client?|Disclose in writing that it is trading for its own account and obtain client consent.|General disclosure after settlement meets the requirement.
agency-cross|Agency cross:|In an agency cross, to how many sides may the adviser recommend the transaction?|One side, not both; it also must satisfy the applicable disclosure and consent requirements.|Acting as broker for both permits recommending to both.
broker-pay|broker/agent|What transaction compensation is associated with a broker acting as agent?|A commission.|A broker acting as agent earns a principal markup.
dealer-pay|dealer/principal|What transaction compensation is associated with a dealer acting as principal?|A markup or markdown.|A principal trade is compensated only by a commission.
trade-error|trade error|What should an agent do upon discovering a trading error?|Immediately report it to the designated supervisor.|Personally make an offsetting trade to conceal or repair it first.
solicitor-iar|solicits advisory clients|What status generally applies to an advisory-firm employee who solicits advisory clients?|Investment adviser representative.|Solicitation can never create representative status.
bd-active|registration is in force|When is an agent's registration effective relative to the employing broker-dealer?|Only while the employing broker-dealer's registration is in force.|The agent may continue transacting after the firm's registration ceases.
dual-compensation|also a BD can receive|What is required when a dual adviser/broker-dealer may earn transaction compensation from its recommendation?|Written conflict disclosure and client consent.|The advisory fee makes additional transaction compensation immaterial.
forecast-device|difficulties and limitations|What must advertising disclose about forecasting charts or formulas?|The difficulties and limitations of using them.|A history of how many years the device was used satisfies the rule.
testimonial|testimonial = current|What distinguishes a testimonial from an endorsement under the SEC marketing rule?|A testimonial comes from a current client; an endorsement comes from a nonclient.|Any compensated statement is necessarily a testimonial.
promoter-oversight|Disclose compensation/conflicts|What duties accompany compensated promotional statements under the marketing rule?|Disclose compensation and conflicts and oversee compliance.|Payment removes the need for disclosure if the statement is accurate.
promoter-agreement|$1,000 or less|What de minimis compensation exception can apply to the written promoter agreement requirement?|Compensation of $1,000 or less over the preceding twelve months.|The exception uses less than $1,000 and is tested per statement.`,
10: `restricted-clock|Restricted security:|Which acquisition characteristic creates the Rule 144 holding-period clock?|Acquiring restricted securities in an unregistered or private transaction.|Affiliate status alone creates a holding period for publicly bought shares.
unrestricted-clock|Unrestricted security:|Is there a Rule 144 holding period for unrestricted shares acquired publicly?|No. Publicly acquired unrestricted shares have no Rule 144 holding period.|Every share held by an affiliate must first be held six months.
control|Control security:|What makes a security a control security?|It is held by an affiliate, whether restricted or unrestricted.|Only privately issued affiliate shares are control securities.
nonaffiliate-public|Nonaffiliate + unrestricted|How does a nonaffiliate ordinarily sell unrestricted securities?|Through an ordinary public sale; Rule 144 is generally unnecessary.|Rule 144 notice is required for every public sale.
nonaffiliate-reporting|Nonaffiliate + restricted, reporting|Under Rule 144, how long must a nonaffiliate hold restricted shares of a reporting issuer, and what changes after one year?|Hold for six months. Current public information is required until one year; after one year, no Rule 144 conditions remain.|All conditions disappear immediately at six months.
nonaffiliate-nonreporting|Nonaffiliate + restricted, nonreporting|Under Rule 144, how long must a nonaffiliate hold restricted shares of a nonreporting issuer?|At least one year. After that, no Rule 144 conditions remain for the nonaffiliate.|Six months applies regardless of the issuer's reporting status.
affiliate-public|Affiliate + unrestricted/publicly bought|What Rule 144 conditions remain for an affiliate's publicly purchased shares?|Current information, volume, manner, and notice, but no holding period.|No holding period means no remaining affiliate conditions.
affiliate-reporting|Affiliate + restricted, reporting|Under Rule 144, how long must an affiliate hold restricted shares of a reporting issuer before resale?|At least six months. Affiliate resale conditions still apply after the holding period.|Six months eliminates the affiliate volume restriction.
affiliate-nonreporting|Affiliate + restricted, nonreporting|Under Rule 144, how long must an affiliate hold restricted shares of a nonreporting issuer before resale?|At least one year. Affiliate resale conditions still apply after the holding period.|A one-year hold removes all conditions even for an affiliate.
lookback|preceding **3 months|How long must a seller have been free of affiliate status to use Rule 144's nonaffiliate treatment?|The seller must not be an affiliate now or during the preceding three months.|Resigning yesterday immediately establishes nonaffiliate status.
affiliate-conditions|Affiliate conditions:|What four categories of Rule 144 conditions apply to affiliate resales?|Current information, volume, manner of sale, and notice.|The holding period is the only affiliate condition.
listed-volume|Exchange-listed equity volume|What is the exchange-listed equity volume ceiling under the tested affiliate rule?|The greater of 1% outstanding or the four-week average weekly trading volume.|Use the smaller of those two amounts.
otc-volume|OTC|What volume measure applies to the tested over-the-counter affiliate equity sale?|1% of outstanding shares.|A large four-week trading average always increases the OTC allowance.
form144|5,000 shares OR $50,000|What three-month affiliate-sale thresholds trigger the tested Form 144 notice requirement?|More than 5,000 shares or more than $50,000. Either threshold is enough.|Both the share count and value must be exceeded.
gift-tack|Gift:|How does a gift affect a restricted security's holding period?|The recipient can tack the donor's holding period.|Every gift restarts the restricted-share clock.`,
11: `plan-million|At least $1 million|When does an employee benefit plan count as institutional for the tested state adviser five-client limit?|When it has at least $1 million in assets. It then does not count toward the noninstitutional-client limit.|The $1 million threshold qualifies its adviser for federal pension-consultant registration.
pension-consultant|At least $200 million|What plan-asset threshold can support the special federal pension-consultant registration basis?|Aggregate advised employee-benefit, government, or church plan assets of at least $200 million.|Each advised plan must separately have $200 million.
plan-distinction|numbers answer different questions|Why are the $1 million and $200 million plan thresholds not interchangeable?|$1 million classifies a state-law client; $200 million can establish the consultant's federal registration eligibility.|Both numbers measure the adviser's ordinary regulatory AUM.`
};
