export const remainingRules: Record<number,string> = {
12: `erisa-law|ERISA is a federal law|Is ERISA a law or a type of retirement plan?|A federal law. It governs most private-employer retirement plans.|ERISA is itself a defined-contribution plan.
erisa-excluded|government and most church|Which employer plans are generally outside ERISA?|Government plans and most church plans.|All tax-favored retirement plans are ERISA-covered.
fiduciary|ERISA fiduciary:|What core conduct does ERISA require of a plan fiduciary?|Loyalty, prudence, diversification, and compliance with plan documents; no self-dealing or personal use of plan assets.|Personal use is permitted if the fiduciary plans to repay the plan.
participant-choice|§404(c)|What participant-directed investment decision may ERISA section 404(c) protect a fiduciary from?|The participant's own investment choice in a compliant plan. It does not excuse the fiduciary's misconduct.|Participant choice releases the fiduciary from every duty.
defined-benefit|Defined benefit |Who bears funding and investment risk in a defined-benefit plan?|The employer, because a benefit is promised.|The employee bears all funding risk because the benefit is fixed.
defined-contribution|Defined contribution |Who bears investment risk in a defined-contribution plan?|The employee, whose individual account depends on investment results.|A fixed contribution guarantees a fixed retirement benefit.
plan-401|401(k)|What is the basic employer and contribution pattern of a 401(k)?|A private-employer plan using salary deferrals, often with a match.|A 401(k) is limited to public-school employees.
plan-403|403(b)|Which employers are associated with a 403(b)?|Public schools and qualifying nonprofit or church organizations.|A 403(b) is the ordinary corporate salary-deferral plan.
plan-457|457(b)|Which employers use 457(b) plans?|State or local governments and certain tax-exempt employers; governmental plans generally fall outside ERISA.|Every 457(b) is a private corporate ERISA plan.
profit-sharing|Profit-sharing |Are employer contributions to a profit-sharing plan mandatory each year?|No. Employer contributions are discretionary.|Profit-sharing contributions must follow a fixed annual funding formula.
money-purchase|Money-purchase pension|How does a money-purchase pension contribution differ from profit-sharing?|The employer contribution is required and fixed by formula.|A money-purchase contribution can always be skipped at the employer's discretion.
sep|Simplified Employee Pension|Who primarily contributes to a SEP IRA?|The employer; it is commonly used by small businesses and self-employed people.|A SEP primarily relies on employee salary deferrals.
simple|Savings Incentive Match|What contribution combination characterizes a SIMPLE IRA?|Employee deferrals plus a required employer contribution.|The employer contribution is always optional.
traditional|Traditional IRA |What is the basic traditional IRA tax pattern?|A possible contribution deduction, tax-deferred growth, and taxable distributions.|All traditional IRA contributions are automatically deductible for everyone.
roth|Roth IRA |What is the basic Roth IRA tax and lifetime-distribution pattern?|After-tax contributions, tax-free qualified withdrawals, and no owner lifetime RMD.|Roth IRA owners must take lifetime RMDs like traditional IRA owners.
keogh|Keogh |What does the older term Keogh describe?|A qualified self-employed plan that can be defined benefit or defined contribution.|Keogh always means only one specific contribution-plan design.
nonqualified|Nonqualified plan |What creditor position may an employee have in a nonqualified retirement arrangement?|The employee may be an unsecured creditor, without qualified-plan protections.|Nonqualified benefits always have the same protections as qualified-plan assets.
qdro|qualified domestic relations order|Which divorce document divides qualified employer-plan benefits?|A qualified domestic relations order; IRA division follows separate IRA divorce-transfer rules.|The employer-plan QDRO framework applies identically to IRAs.
qualified-erisa|Tax-qualified does not|Does tax-qualified status establish ERISA coverage?|No. A government plan may receive favorable tax treatment while remaining outside ERISA.|Tax-qualified and ERISA-covered are interchangeable labels.
government-design|not automatically a defined benefit|Does the label governmental 457(b) establish that a plan promises a defined benefit?|No. Governmental 457(b) status does not by itself make a plan a defined-benefit plan.|A government employer makes every 457(b) a defined-benefit pension.`,
13: `early-tax|Before **59½|What taxes generally apply to a taxable retirement distribution before age 59½ if no exception applies?|Ordinary income tax plus a 10% additional tax.|The 10% additional tax replaces ordinary income tax.
simple-early|first **2 years|What additional early-distribution tax can apply to a SIMPLE IRA in its first two years?|25%.|The SIMPLE early-distribution tax is always 10%.
457-exception|Governmental 457(b):|What is the early-distribution treatment of governmental 457(b) funds?|They generally avoid the 10% additional tax; rolled-in qualified-plan money can remain subject to it.|Rolling other qualified-plan money into a 457(b) always removes its penalty exposure.
rule55|Rule of 55|When can separation from employment support the age-55 exception?|Separation during or after the year turning 55 can qualify for an employer-plan distribution; the rule does not apply to IRAs.|An IRA withdrawal at 55 automatically qualifies after leaving a job.
general-exceptions|Common exceptions:|Which common events can qualify for an exception to the early-retirement-distribution additional tax?|Death, disability, substantially equal periodic payments, qualifying medical expenses, and an IRS levy.|Every personal financial hardship automatically qualifies.
ira-education|IRA-only high-frequency|Which education expense can support an IRA early-distribution exception?|Qualifying higher-education expenses.|The IRA education exception automatically applies to employer plans.
ira-health|unemployed health-insurance|What health-insurance situation is identified as an IRA early-distribution exception?|Qualifying premiums while unemployed.|Any insurance premium creates a universal employer-plan exception.
ira-home|$10,000 lifetime|What is the IRA first-home exception's lifetime dollar limit?|$10,000.|The $10,000 allowance renews every year.
qdro-exception|QDRO penalty exception|Where does the QDRO additional-tax exception apply?|Qualified employer plans, not IRAs.|Any IRA payment described in a divorce decree uses the QDRO penalty exception.
roth-order|Roth ordering:|In what order are Roth IRA withdrawals generally allocated?|Contributions, then conversions, then earnings.|Earnings must be withdrawn first from a Roth IRA.
roth-contributions|Contributions come out|How are withdrawn Roth IRA contributions treated?|They come out free of income tax and penalty.|Every withdrawal before 59½ is penalized even if entirely contributions.
roth-earnings|Qualified Roth earnings|What two-part test makes Roth IRA earnings distributions qualified?|Five tax years plus age 59½, death, disability, or a qualifying first-home distribution, subject to its $10,000 lifetime limit.|The five-year period alone qualifies every earnings withdrawal.
rmd-penalty|Missed RMD excise tax|What is the general tax rate for a missed required minimum distribution, and how can timely correction reduce it?|Generally 25%, reduced to 10% when corrected within the applicable correction window, described here as within two years.|A missed RMD still always carries the old 50% tax.
rmd-working|Traditional IRA RMD cannot|Can continued employment postpone a traditional IRA owner's required minimum distribution?|No. Continued work does not postpone the traditional IRA requirement.|An IRA owner can postpone RMDs indefinitely while working.
rmd-employer|Current-employer plan may|When may continued work defer a current-employer plan RMD?|The plan may permit it, except for an owner of more than 5%.|All current employees qualify regardless of ownership.
ira-loans|do not permit participant loans|Can a participant borrow from a personal, SEP, or SIMPLE IRA?|No. An employer plan may permit participant loans; those IRAs do not.|A SIMPLE IRA may lend because an employer contributes.
irmaa|income-related monthly adjustment|Which Medicare parts receive the income-related monthly adjustment surcharge?|Parts B and D.|It is a surcharge on every Medicare part without distinction.
ira-deadline|prior-year IRA contribution|Does extending an income-tax return extend the prior-year IRA contribution deadline?|No. The contribution is generally due by the original filing deadline, normally April 15.|A tax extension automatically extends the IRA contribution deadline.`,
14: `529-control|Account owner keeps control|Who controls a 529 account and can generally select another eligible family beneficiary?|The account owner.|The originally named child irrevocably owns the 529 funds.
529-tax|qualified education withdrawals|What is the basic 529 federal tax pattern?|After-tax contributions and tax-free qualified education withdrawals; state benefits may be available.|Contributions automatically produce a federal income-tax deduction.
529-roth|$35,000 lifetime|What limits apply to a beneficiary's 529-to-Roth IRA rollover?|$35,000 lifetime, annual contribution limits, a 15-year account, and exclusion of contributions from the preceding five years.|The entire 529 balance can roll to a Roth immediately without limits.
coverdell-limit|$2,000 total|What is the annual Coverdell contribution limit measured per beneficiary?|$2,000 total across contributors, subject to contributor income limits.|Each contributor gets a separate $2,000 allowance for the same child.
coverdell-age|generally contribute by 18|What ages generally frame Coverdell funding and use?|Contribute by age 18 and use or distribute by age 30.|Coverdell has no general age boundaries.
coverdell-use|K–12|Can a Coverdell account fund qualifying school expenses before college?|Yes. It supports kindergarten through grade 12 as well as higher education.|Coverdell can fund only college expenses.
coverdell-beneficiary|Custodian manages for beneficiary|May a Coverdell account's beneficiary generally be changed to an eligible family member?|Yes. Its rules generally permit an eligible family beneficiary change.|The beneficiary can never change as with an irrevocable custodial gift.
minor-owner|minor owns it|Who owns an UGMA or UTMA gift before the child reaches the age for taking control?|The named minor owns it immediately. The custodian manages it until the state termination age.|The custodian owns the property until the child becomes an adult.
minor-purpose|Not limited to education|Are UGMA or UTMA assets limited to education expenses?|No. They may be used for the named minor's benefit beyond education.|Only qualified education spending is allowed like a tax-favored education withdrawal.
minor-property|UGMA mainly holds|What property distinction separates UGMA from UTMA?|UGMA mainly holds financial property; UTMA can hold broader property.|UTMA is restricted to publicly traded securities only.
utma-retest|RETEST — UTMA|May a custodian reclaim an UTMA gift or redirect it to a sibling?|No. The gift is irrevocable: it permanently belongs to the named minor.|Managing the account gives the custodian the right to choose a new beneficiary.`,
15: `capital-rates|0%, 15%, or 20%|What basic federal rates apply to long-term capital gains depending on taxable income?|0%, 15%, or 20%.|Every long-term gain receives one flat rate.
qualified-dividends|Qualified dividends generally|What tax-rate treatment do qualified dividends generally receive?|The preferential long-term capital-gain rates.|All dividends must be taxed at ordinary income rates.
iso-holding|more than 1 year after exercise|What holding periods support qualifying incentive stock option treatment?|More than one year after exercise and more than two years after grant.|Meeting either holding period alone is enough.
iso-amt|Exercise generally creates|What is the basic tax distinction at incentive stock option exercise?|Generally no regular taxable income, but the spread can be an alternative minimum tax preference item.|No regular income tax means the spread has no possible tax effect.
loss-netting|Capital losses first|What is the first use of capital losses?|Offset capital gains, including cross-netting short- and long-term results.|Deduct them from salary before offsetting gains.
loss-ordinary|$3,000|How much net capital loss can generally offset ordinary income annually?|Up to $3,000; unused loss carries forward.|The unused balance disappears at year-end.
loss-character|larger side determines|After short- and long-term capital results are cross-netted, what determines final character?|The larger remaining side determines the net result's character.|The most recent sale always determines character.
gift-loss|below FMV|A gift's value was below the donor's basis, and it sells below that gift-date value. Which basis determines the loss?|The gift-date fair market value, assuming no later basis adjustments.|The donor's higher basis is always the loss basis.
gift-gain|above donor basis|A gift's value was below the donor's basis, and it later sells above the donor's basis. Which basis determines the gain?|The donor's basis, assuming no later basis adjustments.|Gift-date fair market value is always the gain basis.
gift-middle|between → no gain/loss|What results when a gift sells between its lower gift-date value and the donor's higher basis?|No recognized gain or loss.|The difference from either basis must create a taxable result.
tod|Transfer on death|What does a transfer-on-death designation avoid, without automatically avoiding tax?|Probate for the designated asset; estate or inheritance tax is a separate question.|Avoiding probate automatically removes the asset from estate taxation.
tic|Tenancy in common|What ownership and succession features characterize tenancy in common?|Unequal percentages are allowed and there is no automatic survivorship; a deceased owner's share follows the estate plan.|All joint ownership automatically includes survivorship.
jtwros|Joint tenants with right|What ownership and succession features characterize JTWROS?|Equal undivided interests and automatic transfer of a deceased owner's interest to the surviving joint owners.|The deceased owner's will controls the survivorship interest.
jtwros-retest|RETEST — JTWROS|Do unequal contributions change a properly established JTWROS account's equal interests and survivorship?|No. They do not override the title, though separate gift-tax questions can arise.|The contributor of more money can redirect the survivorship share through a will.
will-title|Will-versus-title rule|How does a will interact differently with TIC and JTWROS property?|A TIC interest can follow the will through the estate; a JTWROS interest goes directly to the survivor outside probate.|A will supersedes an existing survivorship designation.
entirety|Tenancy by the entirety|What features are generally associated with tenancy by the entirety?|Spouses, survivorship, and possible protection from one spouse's separate creditor, subject to state law.|It guarantees identical creditor protection in every state.`,
16: `sole|Sole proprietorship |What are the basic liability and tax features of a sole proprietorship?|Unlimited personal liability and taxation passed directly to the owner.|Pass-through tax treatment guarantees limited liability.
general-partner|General partnership |What liability and tax treatment apply to general partners?|Unlimited liability with pass-through taxation.|General partners are protected from business liabilities like corporate shareholders.
limited-partner|Limited partnership |How do general and limited partners differ in the basic partnership model?|The general partner manages with unlimited liability; the limited partner is passive with limited liability; taxation passes through.|Every partner has limited liability because the entity is a limited partnership.
llc|Limited liability company|What are the basic LLC liability and tax features?|Members generally have limited liability; tax treatment is flexible and commonly pass-through.|An LLC must always be taxed as a C corporation.
c-corp|C corporation |What is the C-corporation double-taxation pattern?|Corporate income tax plus possible shareholder tax on distributed dividends, with generally limited shareholder liability.|Corporate dividends eliminate the corporation's income tax.
s-corp|S corporation |What is the S-corporation tax shortcut?|Generally pass-through taxation with limited shareholder liability.|S corporations ordinarily use the same double-tax pattern as C corporations.
tax-liability|Pass-through taxation does not|Does pass-through taxation establish limited liability?|No. Tax treatment and liability protection are separate characteristics.|Every pass-through entity protects every owner from liability.
march-return|Entity tax-return deadlines|What is the general calendar-year return deadline for partnerships, partnership-taxed LLCs, and S corporations?|March 15.|They generally share the C corporation's April 15 deadline.
april-return|calendar-year C-corporation|What is the general calendar-year C-corporation return deadline?|April 15.|It generally files on the partnership's March 15 deadline.
loss-gates|DPP loss gates:|In what order are direct-participation-program loss limitations applied?|Basis, then at risk, then passive-activity limitations.|The largest of the three limits determines the deduction.
passive-offset|Passive losses generally|What income can passive losses generally offset?|Passive income, not salary or portfolio income; otherwise they are suspended.|Passive losses can freely offset interest and wage income.
release-loss|Complete taxable sale|What disposition generally releases suspended passive losses?|A complete taxable sale to an unrelated buyer.|Any partial tax-free transfer releases every suspended loss.
ptp-silo|Each publicly traded|Can passive income from one publicly traded partnership generally offset a loss from another?|No. Each publicly traded partnership is treated separately for these passive-loss limits.|Passive income from any partnership automatically absorbs every other partnership's loss.`,
17: `correlation|lowest correlation|Which correlation offers the greatest diversification benefit, other factors equal?|The lowest correlation; negative correlation provides more benefit than zero.|Zero correlation is always more diversifying than negative correlation.
systematic|Systematic/market risk|Which risk class cannot be removed by diversification?|Systematic market risk.|Holding enough securities eliminates all market risk.
specific-risk|Security-specific business|How are individual-security business, credit, and liquidity risks generally classified in the exam taxonomy?|Unsystematic and diversifiable.|Every liquidity risk is necessarily market-wide and nondiversifiable.
total-return|Total return =|What belongs in a stock's holding-period total return?|Dividends plus the price gain or loss, divided by initial value for a percentage.|Price appreciation alone measures total return even when dividends are paid.
weak-emh|Weak |Which analysis should not consistently succeed under weak-form efficiency?|Technical analysis, because past prices and volume are reflected.|Weak-form efficiency assumes all private information is already reflected.
semi-emh|Semi-strong |Under semi-strong market efficiency, which information is reflected in prices?|All public information. Technical and public fundamental analysis should not consistently outperform.|Public fundamental analysis remains a consistent route to excess returns.
strong-emh|Strong |What does strong-form efficiency assume about information?|Both public and nonpublic information is reflected, including inside information.|Strong form leaves private information systematically exploitable.`,
18: `nav-value|What you **own|How is the value of existing mutual-fund shares measured?|Shares held multiplied by net asset value.|Use the original public offering price to value existing shares.
pop-pay|initially **pay|Which price represents what an investor initially pays for mutual-fund shares?|The public offering price.|NAV always includes every sales charge in the purchase price.
forward-price|Forward pricing:|Which price applies to a mutual-fund purchase or redemption?|The next computed offering price or NAV, not the previous published price.|An order locks in the last NAV visible on the screen.
fractional|fractional as well as|Must an open-end fund redeem fractional shares?|Yes, fractional as well as whole shares.|Only whole shares are redeemable.
daily-nav|Open-end funds and unit|How often do open-end funds and unit investment trusts compute NAV?|Daily, because they issue redeemable securities.|Their NAV is required only when a shareholder places an order.
closed-nav|Closed-end funds can|How often is a closed-end fund commonly tested as calculating net asset value?|At least weekly, although it may calculate it daily.|The common minimum distinction is monthly.
sec-report|file reports with the SEC|Under the tested reporting comparison, how often do registered investment companies file reports with the SEC?|At least annually.|Every individual portfolio trade requires an immediate SEC report.
shareholder-report|shareholders at least semiannually|How often are registered investment-company shareholder reports sent?|At least semiannually.|One report each year always satisfies shareholder reporting.
coverage-three|300% asset coverage|What minimum asset coverage is required for an open-end fund's bank debt?|300%: assets must be at least three times bank debt under the stated simplified model.|Assets must merely equal bank debt.
repay-equation|both assets and debt fall|When a fund repays debt to reach 300% coverage, what equation preserves both changes?|Solve (assets − repayment) ÷ (debt − repayment) = 3.|Subtract the repayment from debt while leaving assets unchanged.
borrow-equation|both assets and debt rise|If newly borrowed cash remains in an open-end fund, what equation finds its maximum borrowing at 300% coverage?|Solve (assets + borrowing) ÷ (debt + borrowing) = 3, assuming no other liabilities.|Increase debt for the new borrowing while leaving assets unchanged.`,
19: `right|Preemptive right |What is the purpose and usual duration of a preemptive right?|A short-term right for existing shareholders to maintain ownership percentage by buying new issuer shares.|It is an exchange-written option unrelated to an existing shareholder's ownership.
warrant|Warrant |What distinguishes a warrant's issuer and exercise effect?|It is generally longer-term and corporation-issued; exercise normally creates new shares.|Warrant exercise ordinarily transfers an existing share without new issuance.
listed-call|Listed call |Does exercise of an ordinary listed call create new corporate shares?|No. It is a market contract, and the corporation is not the option issuer.|Every call exercise raises new equity for the corporation.
derivative|A **derivative**|What distinguishes a derivative from ordinary common stock or a straight bond?|Its value derives from an underlying asset, rate, index, or event; examples include options, futures, forwards, and swaps.|All financial instruments are derivatives merely because their prices change.
options-approval|designated options-qualified|What approval must precede trading in an options account?|Approval from the designated options-qualified supervisor.|A client's signed order alone replaces account approval.
odd-timing|Options Disclosure Document|When must the options disclosure document be delivered?|No later than account opening.|It can wait until fifteen days after the first trade.
agreement-timing|15 days after account approval|When is the signed options agreement due?|Within fifteen days after account approval.|Fifteen days starts at the first exercise date.
buyer-call|future buyer fearing|Which option should a future buyer purchase to protect against rising prices?|A call. It protects against a higher future purchase price.|A future buyer should buy a put to cap the purchase price.
seller-put|future seller fearing|Which option should a future seller purchase to protect against falling prices?|A put. It protects against a lower future sale price.|A future seller needs a call to establish a sale-price floor.`,
20: `annuity-default|Unless the stem|If a card does not identify a qualified plan or contract, should you assume the annuity is qualified or nonqualified?|Nonqualified.|Every annuity is automatically part of a qualified retirement plan.
annuity-basis|premium is after-tax basis|What is the contribution and growth tax pattern of a nonqualified annuity?|Premiums are after-tax basis and growth is tax-deferred.|All nonqualified annuity premiums are deductible.
annuity-lifo|earnings first|How are nonqualified annuity withdrawals generally allocated before annuitization?|Earnings first, taxable as ordinary income, before recovery of basis.|Tax-free basis comes out before earnings.
exchange-basis|§1035 exchange|What happens to tax basis in a qualifying section 1035 exchange?|The exchange is nontaxable and carries the old basis into the new contract.|The new contract's market value becomes a fresh tax basis.
exclusion-ratio|exclusion ratio =|How is the annuity exclusion ratio calculated?|Investment in the contract divided by expected return; that fraction is basis recovery until basis is exhausted.|Expected return divided by premium determines the tax-free fraction.
period-certain|Life with period certain|What does life with period certain guarantee?|Lifetime payments plus at least the stated period of payments to the annuitant or beneficiary.|Payments stop at the period's end even if the annuitant is alive.
fixed-annuity|Fixed annuity |Which account and guarantee characterize a fixed annuity?|The insurer's general account and a stated benefit or rate subject to claims-paying ability.|The owner directly bears separate-account market risk.
variable-annuity|Variable annuity |What makes a variable annuity different from a fixed annuity?|A separate account, owner investment risk, and security status.|A variable annuity promises the same fixed benefit from the general account.
indexed-annuity|Equity-indexed annuity|Does an equity-indexed annuity give its owner shares of the underlying index securities?|No. Interest is linked partly to an index using caps, spreads, or participation rates.|An indexed crediting formula makes the owner a shareholder in the index.
term-life|**Term**|Does term life provide cash value that can support a policy loan?|No. Term life is temporary protection with no cash value or cash-value loan.|Low premiums mean term policies offer a small guaranteed cash account.
whole-life|**Whole**|What premium and cash-value features identify whole life?|Level or fixed premiums and guaranteed cash value, with permanent coverage.|Flexible premiums and fluctuating separate-account cash value identify whole life.
universal-life|**Universal**|What premium and cash-value features identify traditional universal life?|Flexible premiums and interest-sensitive cash value.|Universal life necessarily uses fixed premiums and separate-account market exposure.
variable-life|**Variable**|Who bears the investment risk in variable life, and is the policy a security?|The owner bears the separate account's investment risk. Yes, variable life is a security.|Variable life guarantees its cash value like ordinary whole life.
policy-loan|policy loan is borrowing|What supports a policy loan, and what happens if it is not repaid?|Cash value supports borrowing; unpaid principal and interest generally reduce the eventual payout.|A policy loan directly withdraws part of the death benefit without further consequence.
life-security|ordinary term, whole|Are ordinary term, whole, and traditional universal life policies securities?|No. Variable life is a security; those ordinary policies are not.|Every permanent cash-value policy is a security.`,
21: `discount-yields|Discount bond:|For the tested discount bond, which is highest: coupon rate, current yield, or yield to maturity?|Yield to maturity, followed by current yield, then coupon rate.|The coupon rate is highest because the bond is discounted.
maturity-spread|Term/maturity spread:|What must be held constant when identifying a term or maturity spread?|Credit quality; the compared maturities differ.|A term spread is defined by different ratings at the same maturity.
credit-spread|Credit/quality spread:|What must be held constant when identifying a credit or quality spread?|Maturity; the compared ratings differ.|Different maturities alone establish a credit spread.
dividend-declare|declaration reduces equity|What happens to equity and working capital when a cash dividend payable within one year is declared?|Both decrease. Declaration reduces equity and creates a current dividend payable; cash has not yet changed.|Cash falls immediately on declaration even before payment.
dividend-pay|Later payment reduces|What happens to working capital and equity when an already-declared cash dividend is paid?|Cash and current liabilities fall equally; working capital and equity are unchanged.|Payment reduces equity a second time.
dividend-current|current ratio rises|A company's current ratio is above one. What happens to that ratio when it pays a declared dividend using current assets?|It rises, assuming current liabilities remain positive. Cash and the dividend payable fall by the same amount.|Paying equal current assets and liabilities always raises the ratio at every starting ratio.
risk-labels|One security's liquidity|How are single-security liquidity risk and purchasing-power risk distinguished?|Individual liquidity risk is diversifiable; purchasing-power, market, and interest-rate risks are systematic.|Inflation risk can be eliminated simply by holding more issuers.
bond-rating|Higher bond rating|What does a higher bond rating generally signal?|Lower credit or default risk, potentially reflecting collateral, issuer resources, and relevant tax base.|A higher rating guarantees a higher investment return.
after-tax|After-tax taxable yield =|How is after-tax taxable yield calculated?|Stated taxable yield multiplied by one minus the tax rate.|Divide the stated yield by one minus the tax rate.
tax-equivalent|Tax-equivalent yield|How is a tax-free municipal yield converted to a taxable-equivalent yield?|Divide the tax-free yield by one minus the tax rate.|Multiply the tax-free yield by one minus the tax rate.`,
22: `balance-sheet|Balance sheet |Which statement reports financial position at a particular date?|The balance sheet: assets equal liabilities plus owners' equity.|The income statement shows all assets and liabilities at a date.
income-statement|Income statement |Which statement reports revenue, expenses, and accounting profit over a period?|The income statement, whose earnings need not equal cash flow.|Reported earnings always equal cash received minus cash paid.
cash-flow|Statement of cash flows |Which statement organizes actual cash movements over a period?|The cash-flow statement, divided into operating, investing, and financing activities.|A balance sheet alone reports every cash flow during the period.
cash-basis|Cash-basis accounting:|When does cash-basis accounting recognize revenue and expense?|When cash is received or paid.|An unpaid invoice is immediately revenue under cash-basis accounting.
accrual|Accrual accounting:|When does accrual accounting recognize revenue and expense?|When earned or incurred, even if cash moves later.|Cash receipt is required before accrual revenue can be recognized.
quick-ratio|Quick ratio =|What assets enter the quick-ratio numerator?|Cash, marketable securities, and receivables; divide by current liabilities and exclude inventory and prepayments.|Inventory belongs in the quick ratio because it is a current asset.
capitalization|long-term debt ÷|What ratio is long-term debt divided by the sum of long-term debt and shareholders' equity?|Debt to total capital. Debt to equity uses equity alone in the denominator.|Debt divided by equity and debt divided by total capital are identical.
equity|equity = assets|How can shareholders' equity be derived from assets and liabilities?|Assets minus liabilities.|Equity equals assets plus liabilities.`,
23: `leading|Leading:|Are initial unemployment claims, the S&P 500, and new durable-goods orders leading or lagging indicators?|Leading indicators.|Average unemployment duration is a leading indicator.
lagging|Lagging:|Are the average prime rate and average duration of unemployment leading or lagging indicators?|Lagging indicators.|Initial unemployment claims are a lagging measure because unemployment already occurred.
claims-duration|Do not confuse|How do initial claims differ from average unemployment duration as indicators?|Initial claims lead; average duration lags.|Both are lagging simply because both concern unemployment.
mode|Mode =|What does the mode measure?|The most frequent value.|Mode means the middle value after sorting.
range|range =|How is a data set's range calculated?|Maximum minus minimum.|The range is maximum divided by minimum.
deviation|standard deviation =|What does standard deviation describe?|Dispersion around the mean.|It measures only the most frequent observation.
npv|Net present value|In the tested net-present-value convention, which rate discounts cash flows and serves as the reinvestment rate?|The required or market discount rate.|NPV always discounts at the project's internal rate of return.
irr|internal rate of return|In the tested internal-rate-of-return convention, at what rate are interim cash flows assumed to be reinvested?|At the internal rate of return itself.|IRR assumes reinvestment at whatever market discount rate the analyst chooses.
bond-cashflow|normally semiannual|What timing convention commonly applies to bond coupon cash flows?|Semiannual payments.|Every annual coupon rate implies one annual cash payment.
capm|capital asset pricing model|What market and investor assumptions underlie the capital asset pricing model?|Frictionless markets, common risk-free borrowing and lending, diversified investors, and rational risk-return preferences.|The model assumes persistent trading costs and undiversified specific risk.
capm-specific|Specific risk is assumed|How does the capital asset pricing model treat security-specific risk?|It assumes investors have diversified that risk away.|Specific risk must receive the same compensation as systematic risk.`,
24: `clean|No material problem|Which audit opinion corresponds to no material problem?|Unmodified, unqualified, or clean.|A clean opinion guarantees the company is a good investment.
qualified|Material, not pervasive|What audit opinion fits a material problem that is not pervasive?|Qualified, meaning except for the identified matter.|Every material problem requires an adverse opinion.
adverse|Known misstatement|What opinion fits a known material and pervasive misstatement?|Adverse.|A known pervasive misstatement merely means the auditor cannot express any opinion.
disclaimer|Insufficient evidence|What opinion fits insufficient evidence with possible material and pervasive effects?|Disclaimer: no opinion.|Missing evidence is automatically proof of a known misstatement.`,
25: `blackout-test|3 consecutive business days|What duration and participation thresholds define the tested pension blackout?|Generally more than three consecutive business days affecting at least 50% of participants' ability to trade employer securities.|Exactly three days and fewer than half of participants satisfy the stated test.
blackout-officers|directors and executive officers|During a qualifying pension blackout, which employer securities are directors and executive officers generally restricted from trading?|Employer securities they acquired through service or employment.|The blackout bans every security owned by those officers.`,
26: `affiliate-reminder|Rule 144:|An affiliate bought unrestricted shares on the market. Which restriction is absent and which remain?|No holding clock; the affiliate resale conditions still apply.|Public acquisition eliminates every Rule 144 condition.
gift-reminder|gift tacks|Does gifting restricted stock reset the holding period?|No. The recipient adds the donor's holding period.|A gift always starts a new holding clock.
agent-reminder|Agent test:|Does an exempt-security sale automatically exempt a broker-dealer salesperson from registration?|No. Agent registration is evaluated separately.|Security exemption alone exempts the salesperson.
issuer-reminder|no commission alone|Is receiving no commission enough to exclude every issuer salesperson from agent status?|No. The narrow exception also requires sales only to existing employees, partners, or directors.|Every unpaid issuer salesperson is excluded.
audit-reminder|Missing audit evidence:|How does the pervasiveness of missing audit evidence affect the opinion?|Material but not pervasive supports qualified; possible material and pervasive effects support disclaimer.|All unavailable evidence produces an adverse opinion.
fund-reminder|Mutual fund = next price|Does a mutual-fund order use the last published price?|No. It uses the next computed price.|The last displayed NAV is guaranteed for a new order.
bond-reminder|discount bond = YTM highest|Which yield is highest on the tested discount bond?|Yield to maturity, above current yield and coupon.|Coupon is highest because interest is fixed.
payment-reminder|cash and payable fall together|What two balances fall together when a declared cash dividend is paid?|Cash and dividends payable.|The payment creates a second charge against equity.
risk-tolerance|risk tolerance|Can age and income alone establish that a recommendation is suitable?|No. The adviser must understand the client's risk tolerance.|High income proves high willingness to accept risk.
free-service|free|What must an advisory service advertised as free exclude?|Both monetary charges and other obligations.|A free service can require a separate purchase as long as no fee is itemized.`,
27: `successor-consent|Successor firm:|What filing accompanies a successor firm's registration?|A consent to service of process.|A predecessor's filing always eliminates the successor's consent requirement.
successor-fee|no new registration fee|When is a successor firm generally next required to pay a registration fee?|At renewal, rather than a new fee immediately on succession.|Succession always requires a second full registration fee immediately.
dni-components|Distributable net income|Do taxable interest, dividends, and tax-exempt interest generally enter a trust's distributable net income?|Yes. All three generally enter distributable net income.|Tax-exempt interest is always omitted from DNI.
dni-character|keeps its tax-free character|What character does tax-exempt interest retain when distributed through the trust?|It generally remains tax-exempt.|A trust distribution automatically converts tax-exempt interest to taxable interest.
dni-gains|reinvested capital gains|Are reinvested capital gains generally included in a trust's distributable net income?|No. They are generally excluded.|Every reinvested capital gain automatically enters DNI.
mass-ad|more than 10 people|What recipient-record exception applies to an adviser advertisement sent to more than ten people?|The adviser generally need not retain every recipient's name and address.|It may destroy the advertisement itself because there were many recipients.
mailing-source|named mailing list|What must accompany a retained advertisement when a named mailing list was used?|A memorandum describing the list and its source.|The recipient exception eliminates the need to identify a mailing list's source.`
};
