'use client';
import { useRef,useState } from 'react';
import { Download,Upload,RotateCcw } from 'lucide-react';
import { backupSchema,type Snapshot } from '@/lib/model';
import { useStudy } from './study-provider';
export function BackupControls(){
  const {data,busy,dispatch}=useStudy();const file=useRef<HTMLInputElement>(null);const dialog=useRef<HTMLDialogElement>(null);
  const [pending,setPending]=useState<Snapshot|null>(null);const [scope,setScope]=useState<'deck'|'all'|null>(null);const [error,setError]=useState('');
  const exportData=()=>{if(!data)return;const blob=new Blob([JSON.stringify({app:'series65-review',exportedAt:new Date().toISOString(),data},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=`series65-progress-${new Date().toISOString().slice(0,10)}.json`;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  const importData=async(f:File|undefined)=>{setError('');if(!f)return;if(f.size>20_000_000){setError('Choose a progress export smaller than 20 MB.');return;}try{const parsed=backupSchema.parse(JSON.parse(await f.text()) as unknown);setPending(parsed.data);setScope(null);dialog.current?.showModal();}catch{setError('This is not a valid Series 65 progress export. Nothing was changed.');}finally{if(file.current)file.current.value='';}};
  const reset=(which:'deck'|'all')=>{setScope(which);setPending(null);dialog.current?.showModal();};
  return <section className="settings-card"><h2>Your data, your control.</h2><p className="muted">Export a backup before changing browsers or clearing site data. Imports replace local progress and settings.</p><div className="data-buttons"><button className="button secondary" disabled={!data||busy} onClick={exportData}><Download aria-hidden="true"/>Export JSON</button><button className="button secondary" disabled={!data||busy} onClick={()=>file.current?.click()}><Upload aria-hidden="true"/>Import JSON</button><input type="file" accept="application/json,.json" ref={file} className="sr-only" aria-label="Import progress file" onChange={e=>void importData(e.target.files?.[0])}/></div>{error&&<p className="inline-error" role="alert">{error}</p>}<div className="reset-options"><button className="text-button" onClick={()=>reset('deck')} disabled={!data||busy}><RotateCcw aria-hidden="true"/>Reset this deck</button><button className="text-button danger-text" onClick={()=>reset('all')} disabled={!data||busy}>Reset all progress & settings</button></div><dialog ref={dialog} className="dialog" aria-labelledby="data-confirm-title"><h2 id="data-confirm-title">{pending?'Replace local progress?':scope==='all'?'Reset everything?':'Reset this deck?'}</h2><p>{pending?`The backup contains ${Object.keys(pending.states).length} card states and ${pending.events.length} reviews. It will replace this device’s saved progress, settings, session, and issue reports.`:scope==='all'?'All study progress, bookmarks, settings, sessions, and locally saved reports will be cleared.':'Study history, bookmarks, suspended cards, the session, and reports for this deck will be cleared. Your settings stay the same.'}</p><p>Export a backup first if you may want to restore it.</p><div className="dialog-buttons"><button className="button secondary" onClick={()=>dialog.current?.close()}>Cancel</button><button className="button danger" disabled={busy} onClick={async()=>{const ok=pending?await dispatch({type:'import',data:pending}):scope?await dispatch({type:'reset',scope}):false;if(ok)dialog.current?.close();}}>{pending?'Replace progress':'Confirm reset'}</button></div></dialog></section>;
}
