'use client';
import { useRef,useState,useEffect } from 'react';
import { Bookmark,Pause,Flag,Play } from 'lucide-react';
import type { Card } from '@/lib/model';
import manifest from '@/content/source-manifest.json';
import { useStudy } from './study-provider';
export function CardActions({card}:{card:Card}){
  const {data,busy,dispatch}=useStudy();const state=data?.states[card.id];
  const dialog=useRef<HTMLDialogElement>(null);const [text,setText]=useState('');const focus=useRef<HTMLTextAreaElement>(null);
  useEffect(()=>{const d=dialog.current;const listener=()=>setText('');d?.addEventListener('close',listener);return()=>d?.removeEventListener('close',listener);},[]);
  const toggle=(flag:'bookmarked'|'suspended')=>void dispatch({type:'flag',cardId:card.id,flag,value:!state?.[flag],now:new Date().toISOString()});
  return <><div className="card-actions"><button className="icon-button" aria-label={state?.bookmarked?'Remove bookmark':'Bookmark card'} aria-pressed={!!state?.bookmarked} disabled={busy} onClick={()=>toggle('bookmarked')}><Bookmark aria-hidden="true" fill={state?.bookmarked?'currentColor':'none'}/><span>Bookmark</span></button><button className="icon-button" aria-label={state?.suspended?'Resume card':'Suspend card'} aria-pressed={!!state?.suspended} disabled={busy} onClick={()=>toggle('suspended')}>{state?.suspended?<Play aria-hidden="true"/>:<Pause aria-hidden="true"/>}<span>{state?.suspended?'Resume':'Suspend'}</span></button><button className="icon-button" aria-label="Report content issue" onClick={()=>{dialog.current?.showModal();focus.current?.focus();}}><Flag aria-hidden="true"/><span>Report</span></button></div><dialog ref={dialog} className="dialog" aria-labelledby={`issue-title-${card.id}`}><form onSubmit={async e=>{e.preventDefault();if(await dispatch({type:'issue',cardId:card.id,text:text.trim(),now:new Date().toISOString()}))dialog.current?.close();}}><h2 id={`issue-title-${card.id}`}>Report a content issue</h2><p className="muted">Saved locally with the card ID. Export progress to share it with a reviewer.</p><label htmlFor={`issue-${card.id}`}>What needs checking?</label><textarea ref={focus} id={`issue-${card.id}`} value={text} onChange={e=>setText(e.target.value)} required minLength={1} maxLength={2000} rows={5}/><div className="dialog-buttons"><button type="button" className="button secondary" onClick={()=>dialog.current?.close()}>Cancel</button><button className="button primary" disabled={busy||!text.trim()}>Save issue</button></div></form></dialog></>;
}
export function AnswerDetails({card}:{card:Card}){return <div className="answer-details"><details><summary>Governing rule</summary><p>{card.governingRule}</p></details><details><summary>Common trap</summary><p><strong>Incorrect claim:</strong> {card.trap}</p></details><details open={card.type==='calculation'}><summary>{card.type==='calculation'?'Worked calculation':'Explanation'}</summary><p>{card.explanation}</p></details>{card.memoryHook&&<details><summary>Memory hook</summary><p>{card.memoryHook}</p></details>}<details><summary>Source & review status</summary><p>{card.sourceHeading}</p><p className="micro">{card.reviewStatus} · Canonical cram sheet, revision {manifest.sourceRevision}. Human review pending.</p></details></div>;}
