'use client';
import Link from 'next/link';
import { useStudy } from './study-provider';
import { deck,sections,cardById } from '@/lib/deck';
import { statistics,activity,currentStreak } from '@/lib/metrics';
import { BackupControls } from './backup-controls';
import { categories, type Category } from '@/lib/model';
export function Progress(){
  const {data,now}=useStudy();if(!data)return <div className="page" role="status">Opening progress…</div>;
  const stats=statistics(deck,data,now);const days=activity(data,now);const maximum=Math.max(1,...days.map(d=>d.count));
  const hardest=Object.values(data.states).filter(s=>s.lapses>0&&cardById.has(s.cardId)).sort((a,b)=>b.lapses-a.lapses||a.ease-b.ease).slice(0,5);
  const retest=statistics(deck.filter(c=>c.retest),data,now);
  const weak=sections.map(s=>({...s,...statistics(deck.filter(c=>c.section===s.number),data,now)})).filter(s=>s.reviews>0).sort((a,b)=>(a.accuracy??100)-(b.accuracy??100)||b.lapses-a.lapses).slice(0,4);
  return <div className="page"><div className="page-heading"><div><p className="eyebrow">EVERY REVIEW COUNTS</p><h1>See what is sticking.</h1><p className="muted">{data.session ? `${data.session.completed.length} of ${data.session.initialCount} cards viewed in this deck.` : "Choose a deck on Study to begin."} Previous rating streak: {currentStreak(data,now)} days.</p></div></div><div className="progress-stats">{[{label:'Recalled',value:stats.accuracy===null?'—':`${stats.accuracy}%`},{label:'Reviews',value:stats.reviews},{label:'Mature',value:stats.mature},{label:'Learning',value:stats.learning},{label:'New',value:stats.new},{label:'Lapses',value:stats.lapses}].map(s=><div key={s.label}><strong>{s.value}</strong><span>{s.label}</span></div>)}</div><p className="micro muted metric-explanation">Tap-through study saves your place. These recall statistics reflect ratings from earlier versions. Mature = review interval of at least 21 days. {stats.suspended} suspended cards are excluded from active learning counts.</p><section className="settings-card"><div className="section-heading"><h2>The last seven days</h2><span className="muted">{days.reduce((sum,d)=>sum+d.count,0)} reviews</span></div><ol className="activity-chart" aria-label="Seven-day review activity">{days.map(d=><li key={d.day}><span className="activity-value">{d.count}</span><div className="activity-bar-area"><span style={{height:`${Math.max(3,d.count/maximum*100)}%`}}/></div><time dateTime={d.day}>{new Date(`${d.day}T12:00:00Z`).toLocaleDateString('en-US',{weekday:'short',timeZone:'UTC'})}</time><span className="sr-only">{d.day}: {d.count} reviews</span></li>)}</ol></section>
    <section className="section-block"><div className="section-heading"><h2>Study areas</h2><span>{stats.due} due · {retest.due} retest due</span></div><div className="table-wrap"><table><caption className="sr-only">Mastery by study area</caption><thead><tr><th scope="col">Area</th><th scope="col">Mastery</th><th scope="col">Mature</th></tr></thead><tbody>{(Object.keys(categories) as Category[]).map(category=>{const s=statistics(deck.filter(c=>c.category===category),data,now);return <tr key={category}><th scope="row"><Link href={`/browse/?category=${category}`}>{categories[category].title}</Link></th><td>{s.mastery}%</td><td>{s.mature}/{s.total}</td></tr>;})}</tbody></table></div></section>
    {weak.length>0&&<section className="section-block"><h2 className="spaced-heading">Weakest sections</h2><div className="section-list">{weak.map(s=><Link key={s.number} href={`/browse/?section=${s.number}`} className="section-row"><span>{s.title}<small>{s.accuracy}% recalled · {s.reviews} reviews</small></span></Link>)}</div></section>}
    <section className="section-block"><div className="section-heading"><h2>Section by section</h2><span className="muted">Self-rated recall</span></div><div className="table-wrap"><table><caption className="sr-only">Review accuracy and counts for every cram-sheet section</caption><thead><tr><th scope="col">Section</th><th scope="col">Recalled</th><th scope="col">Reviews</th><th scope="col">Mature</th></tr></thead><tbody>{sections.map(section=>{const s=statistics(deck.filter(c=>c.section===section.number),data,now);return <tr key={section.number}><th scope="row"><Link href={`/browse/?section=${section.number}`}>{section.number}. {section.title}</Link></th><td>{s.accuracy===null?'—':`${s.accuracy}%`}</td><td>{s.reviews}</td><td>{s.mature}/{s.total}</td></tr>;})}</tbody></table></div></section>
    <section className="section-block"><h2 className="spaced-heading">Hardest cards</h2><div className="section-list">{hardest.length?hardest.map(s=><div className="section-row" key={s.cardId}><span className="section-number">{s.lapses} lapses</span><span>{cardById.get(s.cardId)!.front}<small>{s.totalReviews} reviews · ease {s.ease.toFixed(2)}</small></span></div>):<p className="baseline muted">No recorded lapses yet. Cards you miss after their first review will appear here.</p>}</div></section><BackupControls/>
  </div>;
}
