'use client';
import { useState } from 'react';
import { useStudy } from './study-provider';
import { settingsSchema,type Settings as SettingsModel } from '@/lib/model';
import { BackupControls } from './backup-controls';
export function Settings(){const {data}=useStudy();return <div className="page narrow"><div className="page-heading"><div><p className="eyebrow">MAKE IT YOURS</p><h1>A rhythm that fits.</h1><p className="muted">Small, consistent sessions. Settings stay on this device.</p></div></div>{data?<SettingsForm key={JSON.stringify(data.settings)} initial={data.settings}/>:<p role="status">Opening settings…</p>}<BackupControls/><section className="settings-card"><h2>Install & study offline</h2><p>Use your browser’s Install app option. On iPhone or iPad, open in Safari and choose Share → Add to Home Screen.</p><p className="muted">Wait for “Available offline on this device” in the footer before disconnecting. Offline installation is enabled in the production build. Browser storage can be removed by the browser or device, so keep an exported backup.</p></section></div>;}
function SettingsForm({initial}:{initial:SettingsModel}){
  const {busy,dispatch}=useStudy();const [settings,setSettings]=useState(initial);const [error,setError]=useState('');
  return <form className="settings-card" onSubmit={async e=>{e.preventDefault();const parsed=settingsSchema.safeParse(settings);if(!parsed.success){setError('Use whole numbers within the limits shown.');return;}setError('');await dispatch({type:'settings',settings:parsed.data});}}><h2>Daily practice</h2><div className="settings-fields"><label>New cards per day<input type="number" min={0} max={500} step={1} value={settings.dailyNew} onChange={e=>setSettings({...settings,dailyNew:Number(e.target.value)})}/><small>0–500 · New cards introduced in a UTC day</small></label><label>Review cards per day<input type="number" min={0} max={2000} step={1} value={settings.dailyReviews} onChange={e=>setSettings({...settings,dailyReviews:Number(e.target.value)})}/><small>0–2,000 · Relearning stays in the active session</small></label><label>Session length<input type="number" min={1} max={200} step={1} value={settings.sessionLength} onChange={e=>setSettings({...settings,sessionLength:Number(e.target.value)})}/><small>1–200 unique cards · Again can add another attempt</small></label><label>Appearance<select value={settings.theme} onChange={e=>setSettings({...settings,theme:e.target.value as SettingsModel['theme']})}><option value="system">Use device setting</option><option value="light">Light</option><option value="dark">Dark</option></select></label></div><label className="checkbox-label"><input type="checkbox" checked={settings.reduceMotion} onChange={e=>setSettings({...settings,reduceMotion:e.target.checked})}/>Reduce motion</label><p className="micro muted">Your device’s reduced-motion preference is always respected.</p>{error&&<p className="inline-error" role="alert">{error}</p>}<button className="button primary" disabled={busy} type="submit">Save settings</button></form>;
}
