import type { Metadata } from 'next';
export const disclaimer='Independent educational study aid. Not affiliated with or endorsed by NASAA, FINRA, Kaplan, or any examination provider. Passing results are not guaranteed.';
const raw=process.env.PUBLIC_SITE_URL?.trim();
export const siteOrigin=raw ? new URL(raw).origin : undefined;
if(raw && (!raw.startsWith('https://') || new URL(raw).pathname!=='/'))throw new Error('PUBLIC_SITE_URL must be a real HTTPS origin without a path.');
export function pageMetadata(title:string,description:string,route:string):Metadata{return {title,description,alternates:siteOrigin?{canonical:new URL(route,siteOrigin).href}:undefined,openGraph:{title:`${title} | Series 65 Review`,description,type:'website',siteName:'Series 65 Review',...(siteOrigin?{url:new URL(route,siteOrigin).href}:{})},twitter:{card:'summary',title:`${title} | Series 65 Review`,description}};}
export const faqItems=[
  {q:'What is Series 65 Review?',a:'Series 65 Review is a focused final-review flashcard prototype for people preparing for the Series 65 examination. It teaches a compact study outline through original recall, application, contrast, and calculation cards. It is a supplement to broader preparation, not a complete textbook or an official examination product.'},
  {q:'What subjects does the deck cover?',a:'The deck is organized into the four exam categories: laws and ethics, client investment recommendations and strategies, investment vehicles, and economics and business information. Its 27 source sections emphasize practical distinctions such as registration versus notice filing, ownership versus account control, and similar rules with different deadlines.'},
  {q:'How does spaced repetition work?',a:'Reveal a card, then select Again, Hard, Good, or Easy. Again deliberately returns the card in the current session. Successful ratings schedule a later review, with longer intervals as recall improves. Due cards are selected before new cards, subject to the daily limits you choose.'},
  {q:'Can I study offline?',a:'Yes, in the production build after its initial download completes. Wait for “Available offline on this device” in the footer before disconnecting. Cards, app pages, and progress then remain available on that device. Offline storage can still be removed by the browser or device, so export a backup periodically.'},
  {q:'Where is my study progress stored?',a:'Progress is stored in IndexedDB in your current browser. This prototype has no account service or cloud synchronization. Refreshing preserves progress, but another browser or device does not automatically have it. Use Settings to export a JSON backup or import one you already saved.'},
  {q:'Are these official or recalled Series 65 exam questions?',a:'No. Prompts and examples were independently authored to teach rules from a local study outline. The importer does not read commercial question banks or recalled live examination questions. All cards remain drafts pending human provenance and subject-matter review.'},
  {q:'Does a high mastery percentage predict a passing exam score?',a:'No. Mastery here means a card has reached a review interval of at least 21 days. Recall accuracy is calculated from your self-ratings. Neither is an exam score or a validated probability of passing.'},
  {q:'Can I subscribe or take full practice exams?',a:'Not in this prototype. Paid access, accounts, cloud sync, coupon codes, sample-deck entitlements, and four full-length practice exams are future features. Commercial release is blocked until human accuracy and copyright/provenance reviews are complete.'},
];
