import 'fake-indexeddb/auto';
import { it,expect } from 'vitest';
import { IndexedDbStudyRepository } from '../../lib/repository';
import { deck } from '../../lib/deck';
import { emptySnapshot } from '../../lib/model';
it('persists reviews across repository recreation and serializes independent tab writes',async()=>{
 const name=`test-${crypto.randomUUID()}`;const repo=new IndexedDbStudyRepository(deck,name);const now='2026-09-12T15:00:00Z';let s=await repo.execute({type:'start',now});const id=s.session!.queue[0];s=await repo.execute({type:'rate',cardId:id,rating:'good',sessionId:s.session!.id,now});repo.close();const reopened=new IndexedDbStudyRepository(deck,name);expect((await reopened.read()).states[id].totalReviews).toBe(1);const second=new IndexedDbStudyRepository(deck,name);await Promise.all([reopened.execute({type:'flag',cardId:id,flag:'bookmarked',value:true,now}),second.execute({type:'flag',cardId:deck[1].id,flag:'suspended',value:true,now})]);s=await reopened.read();expect(s.states[id].bookmarked).toBe(true);expect(s.states[deck[1].id].suspended).toBe(true);reopened.close();second.close();
});
it('imports a validated snapshot and retains progress when card wording changes',async()=>{const name=`test-${crypto.randomUUID()}`;const original=new IndexedDbStudyRepository(deck,name);const now='2026-09-12T15:00:00Z';await original.execute({type:'flag',cardId:deck[0].id,flag:'bookmarked',value:true,now});const backup=await original.read();await original.execute({type:'reset',scope:'all'});expect(Object.keys((await original.read()).states)).toHaveLength(0);await original.execute({type:'import',data:backup});original.close();const changed=new IndexedDbStudyRepository(deck.map(c=>({...c,front:c.front+' Revised.'})),name);expect((await changed.read()).states[deck[0].id].bookmarked).toBe(true);changed.close();});
it('failed validation does not overwrite existing stored data',async()=>{const repo=new IndexedDbStudyRepository(deck,`test-${crypto.randomUUID()}`);const s=emptySnapshot();s.settings.dailyNew=-10;await expect(repo.execute({type:'import',data:s})).rejects.toThrow();expect((await repo.read()).settings.dailyNew).toBe(20);repo.close();});
