import { describe,it,expect } from 'vitest';
import { deck } from '../../lib/deck';
import { emptySnapshot,backupSchema,cardSchema } from '../../lib/model';
import { freshState,schedule,dueInDays,utcDay } from '../../lib/scheduler';
import { reduceSnapshot,makeSession } from '../../lib/engine';
import { statistics,currentStreak } from '../../lib/metrics';
const now=new Date('2026-09-12T15:00:00Z');const first=deck[0];
describe('scheduler',()=>{
 it('increases successful intervals and sends a lapse to same-session relearning',()=>{let state=freshState(first.id,now);const intervals:number[]=[];for(let i=0;i<5;i++){state=schedule(state,'good',now);intervals.push(state.interval);}expect(intervals.every((v,i)=>i===0||v>intervals[i-1])).toBe(true);const failed=schedule(state,'again',now);expect(failed.interval).toBe(0);expect(failed.stage).toBe('learning');expect(failed.lapses).toBe(1);expect(new Date(failed.due).getTime()-now.getTime()).toBe(60000);expect(schedule(failed,'good',now).interval).toBe(1);});
 it('clamps ease for repeated hard reviews and uses a longer easy interval',()=>{let s=freshState(first.id,now);for(let i=0;i<40;i++)s=schedule(s,'hard',now);expect(s.ease).toBe(1.3);expect(schedule(freshState(first.id,now),'easy',now).interval).toBeGreaterThan(schedule(freshState(first.id,now),'good',now).interval);});
 it('uses the same UTC date for equivalent instants across DST offsets',()=>{const a=new Date('2026-11-01T01:30:00-04:00');const b=new Date('2026-11-01T05:30:00Z');expect(dueInDays(a,1)).toBe(dueInDays(b,1));expect(dueInDays(a,1)).toBe('2026-11-02T00:00:00.000Z');expect(utcDay(a)).toBe('2026-11-01');});
});
describe('sessions',()=>{
 it('rejects an out-of-date same-card retry from a second tab',()=>{const initial=emptySnapshot();initial.settings.sessionLength=1;const s=reduceSnapshot(initial,{type:'start',now:now.toISOString()},deck);const command={type:'rate' as const,cardId:s.session!.queue[0],rating:'again' as const,sessionId:s.session!.id,expectedRatings:0,now:now.toISOString()};const updated=reduceSnapshot(s,command,deck);expect(updated.session!.queue[0]).toBe(command.cardId);expect(()=>reduceSnapshot(updated,command,deck)).toThrow('another tab');});
 it('selects due cards before new, excludes suspended, and enforces limits',()=>{const s=emptySnapshot();s.settings={...s.settings,dailyNew:1,dailyReviews:1,sessionLength:4};s.states[deck[0].id]={...freshState(deck[0].id,now),totalReviews:3,stage:'review',due:'2026-09-01T00:00:00Z'};s.states[deck[1].id]={...freshState(deck[1].id,now),suspended:true};const session=makeSession(deck,s,now);expect(session.queue[0]).toBe(deck[0].id);expect(session.queue).not.toContain(deck[1].id);expect(session.queue).toHaveLength(2);expect(new Set(session.queue).size).toBe(session.queue.length);});
 it('requeues only Again and protects against stale double rating',()=>{let s=emptySnapshot();s.settings.sessionLength=3;s=reduceSnapshot(s,{type:'start',now:now.toISOString()},deck);const initial=s.session!.queue[0];const id=s.session!.id;s=reduceSnapshot(s,{type:'rate',cardId:initial,rating:'again',sessionId:id,now:now.toISOString()},deck);expect(s.session!.queue.filter(x=>x===initial)).toHaveLength(1);expect(s.session!.queue.at(-1)).toBe(initial);expect(()=>reduceSnapshot(s,{type:'rate',cardId:initial,rating:'good',sessionId:id,now:now.toISOString()},deck)).toThrow();for(let i=0;i<3;i++)s=reduceSnapshot(s,{type:'rate',cardId:s.session!.queue[0],rating:'good',sessionId:id,now:now.toISOString()},deck);expect(s.session!.queue).toHaveLength(0);expect(new Set(s.session!.completed).size).toBe(3);});
 it('counts new introductions across multiple sessions in the same UTC day',()=>{let s=emptySnapshot();s.settings.dailyNew=1;s=reduceSnapshot(s,{type:'start',now:now.toISOString()},deck);s=reduceSnapshot(s,{type:'rate',cardId:s.session!.queue[0],rating:'good',sessionId:s.session!.id,now:now.toISOString()},deck);expect(makeSession(deck,s,now).queue).toHaveLength(0);expect(makeSession(deck,s,new Date('2026-09-13T15:00:00Z')).queue.length).toBeGreaterThan(0);});
 it('resumes the same queue and removes a newly suspended current card',()=>{let s=reduceSnapshot(emptySnapshot(),{type:'start',now:now.toISOString()},deck);expect(reduceSnapshot(s,{type:'start',now:new Date(now.getTime()+5000).toISOString()},deck)).toBe(s);const id=s.session!.queue[0];s=reduceSnapshot(s,{type:'flag',cardId:id,flag:'suspended',value:true,now:now.toISOString()},deck);expect(s.session!.queue).not.toContain(id);});
 it('reset deck keeps settings, while reset all restores defaults',()=>{const s=emptySnapshot();s.settings.dailyNew=7;expect(reduceSnapshot(s,{type:'reset',scope:'deck'},deck).settings.dailyNew).toBe(7);expect(reduceSnapshot(s,{type:'reset',scope:'all'},deck).settings.dailyNew).toBe(20);});
});
describe('content and backups',()=>{
 it('covers the September 13 ERISA retests with original applications',()=>{for(const key of ['fiduciary','plan-403','government-design']){const card=deck.find(c=>c.ruleId===`s65-12-${key}`&&c.type==='application');expect(card).toBeDefined();expect(card?.retest).toBe(true);}expect(deck.find(c=>c.id==='s65-12-government-design-recall')?.answer).toContain('does not by itself');});
 it('has every section, unique IDs, drafts, and a contrast for every high-priority or retest rule',()=>{expect(new Set(deck.map(c=>c.section)).size).toBe(27);expect(new Set(deck.map(c=>c.id)).size).toBe(deck.length);expect(deck.every(c=>c.reviewStatus==='draft'&&cardSchema.safeParse(c).success)).toBe(true);for(const c of deck.filter(c=>c.type==='recall'&&(c.priority==='high'||c.retest)))expect(deck.some(d=>d.ruleId===c.ruleId&&d.type==='contrast')).toBe(true);for(const id of ['s65-14-utma-retest','s65-15-jtwros-retest'])expect(deck.some(c=>c.ruleId===id&&c.type==='application')).toBe(true);expect(deck.filter(c=>c.type==='calculation').length).toBeGreaterThan(15);});
 it('rejects corrupt versions, negative settings, mismatched card IDs and duplicate queues',()=>{const wrap=(data:unknown)=>({app:'series65-review',exportedAt:now.toISOString(),data});expect(backupSchema.safeParse(wrap({...emptySnapshot(),version:2})).success).toBe(false);const s=emptySnapshot();s.settings.dailyNew=-1;expect(backupSchema.safeParse(wrap(s)).success).toBe(false);s.settings.dailyNew=20;s.states[first.id]=freshState(deck[1].id,now);expect(backupSchema.safeParse(wrap(s)).success).toBe(false);});
 it('does not bundle private scores or vendor questions',()=>{const visible=deck.map(c=>[c.front,c.answer,c.trap,c.explanation].join(' ')).join('\n');expect(visible).not.toMatch(/Kaplan|65\.7%|85\.3%|112\/140|108\/140/);});
 it('measures self-rated recall and a streak continuing from yesterday',()=>{const s=emptySnapshot();s.events=[{id:'1',cardId:first.id,at:'2026-09-11T12:00:00Z',rating:'good',wasNew:true},{id:'2',cardId:first.id,at:'2026-09-10T12:00:00Z',rating:'again',wasNew:false}];expect(currentStreak(s,now)).toBe(2);expect(statistics(deck,s,now).accuracy).toBe(50);});
});
